processed 7 tasks

init:
A: object(0,0)

task 1 'run-graphql'. lines 7-11:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 2 'run-graphql'. lines 13-43:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 29
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 3 'run-graphql'. lines 45-49:
Response: {
  "data": {}
}

task 4 'run-graphql'. lines 51-55:
Response: {
  "data": {
    "chainIdentifier": "f818fd31"
  }
}

task 5 'run-graphql'. lines 57-61:
Response: {
  "data": {
    "chainIdentifier": "f818fd31"
  }
}

task 6 'run-graphql'. lines 63-67:
Response: {
  "data": {}
}
