processed 8 tasks

init:
A: object(0,0)

task 1, lines 7-11:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 2, lines 13-43:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 28
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 3, lines 45-51:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 25
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 4, lines 53-57:
//# run-graphql
Response: {
  "data": {}
}

task 5, lines 59-63:
//# run-graphql
Response: {
  "data": {
    "chainIdentifier": "e50daeb7"
  }
}

task 6, lines 65-69:
//# run-graphql
Response: {
  "data": {
    "chainIdentifier": "e50daeb7"
  }
}

task 7, lines 71-75:
//# run-graphql
Response: {
  "data": {}
}
