processed 16 tasks

task 1, lines 7-15:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false
      }
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 3,
      "outputNodes": 3,
      "depth": 3,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 254
    }
  }
}

task 2, lines 17-27:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 42,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 359
    }
  }
}

task 3, lines 29-43:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "transactionBlocks": {
            "edges": [
              {
                "txns": {
                  "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 6,
      "outputNodes": 842,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 484
    }
  }
}

task 4, lines 45-66:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notOne": {
            "edges": [
              {
                "txns": {
                  "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
                }
              }
            ]
          },
          "isOne": {
            "edges": [
              {
                "txns": {
                  "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 922,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 735
    }
  }
}

task 5, lines 68-89:
//# run-graphql --show-usage
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notZero": {
            "edges": [
              {
                "txns": {
                  "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
                }
              }
            ]
          },
          "isZero": {
            "edges": []
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 882,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 733
    }
  }
}

task 6, lines 91-101:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 323
    }
  }
}

task 7, lines 103-113:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 322
    }
  }
}

task 8, lines 115-143:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD",
            "first": null,
            "last": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 14,
      "outputNodes": 1762,
      "depth": 8,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1077
    }
  }
}

task 9, lines 145-172:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD",
          "first": null,
          "last": null
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 13,
      "outputNodes": 1742,
      "depth": 7,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1030
    }
  }
}

task 10, lines 174-229:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD",
            "a": null,
            "b": null
          }
        }
      ]
    },
    "events": {
      "edges": [
        {
          "node": {
            "timestamp": "1970-01-01T00:00:00Z",
            "sendingModule": {
              "name": "nft"
            },
            "type": {
              "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::DisplayCreated<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
            }
          }
        },
        {
          "node": {
            "timestamp": "1970-01-01T00:00:00Z",
            "sendingModule": {
              "name": "nft"
            },
            "type": {
              "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::VersionUpdated<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
            }
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 28,
      "outputNodes": 46464,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 2483
    }
  }
}

task 11, lines 231-256:
//# run-graphql --show-usage
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD",
            "a": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 12,
      "outputNodes": 17302,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1029
    }
  }
}

task 12, lines 258-279:
//# run-graphql --show-usage
Response: {
  "data": {
    "fragmentSpread": {
      "nodes": [
        {
          "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
        }
      ]
    },
    "inlineFragment": {
      "nodes": [
        {
          "digest": "Cpgs1hPAQs2nfbQkD2ZsEfEAvmtTjb7QT5mtXaMQwhgD"
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 8,
      "outputNodes": 44,
      "depth": 4,
      "variables": 0,
      "fragments": 1,
      "queryPayload": 562
    }
  }
}

task 13, lines 281-293:
//# run-graphql --show-usage
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 62,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 394
    }
  },
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 14, lines 295-305:
//# run-graphql --show-usage
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 42,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 141
    }
  },
  "errors": [
    {
      "message": "Invalid value for argument \"first\", expected type \"Int\"",
      "locations": [
        {
          "line": 3,
          "column": 21
        }
      ]
    }
  ]
}

task 15, lines 307-317:
//# run-graphql --show-usage
Response: {
  "data": null,
  "errors": [
    {
      "message": "Estimated output nodes exceeds 100000",
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
