processed 34 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 20-47:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 49:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 51-53:
//# programmable --sender A --inputs object(1,5) 100 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3990000,  storage_rebate: 3990000, non_refundable_storage_fee: 0

task 4, line 55:
//# create-checkpoint
Checkpoint created: 2

task 5, line 57:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 6, line 59:
//# create-checkpoint
Checkpoint created: 3

task 7, line 61:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 9, line 65:
//# create-checkpoint
Checkpoint created: 4

task 11, line 69:
//# create-checkpoint
Checkpoint created: 5

task 13, line 73:
//# create-checkpoint
Checkpoint created: 6

task 15, line 77:
//# create-checkpoint
Checkpoint created: 7

task 16, lines 79-100:
//# run-graphql --cursors {"c":2,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 17, lines 102-123:
//# run-graphql --cursors {"c":3,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 18, lines 125-146:
//# run-graphql --cursors {"c":4,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 19, line 148:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 20, line 150:
//# create-checkpoint
Checkpoint created: 8

task 21, lines 152-173:
//# run-graphql --cursors {"c":2,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 22, lines 175-196:
//# run-graphql --cursors {"c":3,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 23, lines 198-219:
//# run-graphql --cursors {"c":4,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 24, line 221:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 25, line 223:
//# create-checkpoint
Checkpoint created: 9

task 26, lines 225-246:
//# run-graphql --cursors {"c":2,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 27, lines 248-269:
//# run-graphql --cursors {"c":3,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 28, lines 271-292:
//# run-graphql --cursors {"c":4,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980382000"
                },
                {
                  "coinType": {
                    "repr": "0xbdf6cc52e18ba611bf235bf856f16c4c30f609167401546f52e08ba168429473::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 29, line 295:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 6
Objects snapshot updated to [0 to 6)

task 30, line 297:
//# create-checkpoint
Checkpoint created: 10

task 31, lines 299-320:
//# run-graphql --cursors {"c":2,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 32, lines 322-343:
//# run-graphql --cursors {"c":3,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 33, lines 345-366:
//# run-graphql --cursors {"c":4,"t":1,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
