processed 34 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 20-47:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 49-49:
Checkpoint created: 1

task 3 'programmable'. lines 51-53:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 4012800, non_refundable_storage_fee: 0

task 4 'create-checkpoint'. lines 55-55:
Checkpoint created: 2

task 5 'transfer-object'. lines 57-57:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 6 'create-checkpoint'. lines 59-59:
Checkpoint created: 3

task 7 'transfer-object'. lines 61-61:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 9 'create-checkpoint'. lines 65-65:
Checkpoint created: 4

task 11 'create-checkpoint'. lines 69-69:
Checkpoint created: 5

task 13 'create-checkpoint'. lines 73-73:
Checkpoint created: 6

task 15 'create-checkpoint'. lines 77-77:
Checkpoint created: 7

task 16 'run-graphql'. lines 79-100:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 102-123:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 18 'run-graphql'. lines 125-146:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 19 'force-object-snapshot-catchup'. lines 148-148:
Objects snapshot updated to [0 to 3)

task 20 'create-checkpoint'. lines 150-150:
Checkpoint created: 8

task 21 'run-graphql'. lines 152-173:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 22 'run-graphql'. lines 175-196:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 23 'run-graphql'. lines 198-219:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 24 'force-object-snapshot-catchup'. lines 221-221:
Objects snapshot updated to [0 to 4)

task 25 'create-checkpoint'. lines 223-223:
Checkpoint created: 9

task 26 'run-graphql'. lines 225-246:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 27 'run-graphql'. lines 248-269:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 28 'run-graphql'. lines 271-292:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "200"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980336400"
                },
                {
                  "coinType": {
                    "repr": "0x494bb9aa583dff5b55ca0aa5cf167519db588b705c7ac95e200834dcb988f607::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "200"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 29 'force-object-snapshot-catchup'. lines 295-295:
Objects snapshot updated to [0 to 6)

task 30 'create-checkpoint'. lines 297-297:
Checkpoint created: 10

task 31 'run-graphql'. lines 299-320:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 32 'run-graphql'. lines 322-343:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 33 'run-graphql'. lines 345-366:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
