processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-40:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 44-46:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 4012800, non_refundable_storage_fee: 0

task 4, line 48:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 50-91:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                "balance": {
                  "value": "100300"
                }
              }
            }
          }
        },
        {
          "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                  "balance": {
                    "value": "100300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 93-134:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 136:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 8, line 138:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 9, line 140:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 142-195:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "100300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                "balance": {
                  "value": "100300"
                }
              }
            }
          }
        },
        {
          "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                  "balance": {
                    "value": "100300"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 199:
//# create-checkpoint
Checkpoint created: 4

task 14, line 203:
//# create-checkpoint
Checkpoint created: 5

task 16, line 207:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 209-250:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IOqHiBIiGGWRVX98PwcA7D6OlUxbWRIbTaAd43LibLWxAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xea87881222186591557f7c3f0700ec3e8e954c5b59121b4da01de372e26cb5b1",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IADQ2v0ct4nNzTYO05l+0d4aK04vvctc++HRiQ6gNsTgAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x00d0dafd1cb789cdcd360ed3997ed1de1a2b4e2fbdcb5cfbe1d1890ea036c4e0",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IE0ijO1u41EiLYHpPEz/85YK+UizMz1rxfX0l2FtDZHGAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x4d228ced6ee351222d81e93c4cfff3960af948b3333d6bc5f5f497616d0d91c6",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 252:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 254:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 256-285:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
