processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-40:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 44-46:
//# programmable --sender A --inputs object(1,5) 100000 object(1,1)
//> 0: iota::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 4012800, non_refundable_storage_fee: 0

task 4, line 48:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 50-91:
//# run-graphql
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6, lines 93-134:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 136:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 8, line 138:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2310400, non_refundable_storage_fee: 0

task 9, line 140:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 142-195:
//# run-graphql
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "100200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                "balance": {
                  "value": "100200"
                }
              }
            }
          }
        },
        {
          "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                  "balance": {
                    "value": "100200"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12, line 199:
//# create-checkpoint
Checkpoint created: 4

task 14, line 203:
//# create-checkpoint
Checkpoint created: 5

task 16, line 207:
//# create-checkpoint
Checkpoint created: 6

task 17, lines 209-250:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IPR7BIW9qs+92bKG1LYmZjkSEj/t1eTj1+QukrriehGSAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xf47b0485bdaacfbdd9b286d4b626663912123fedd5e4e3d7e42e92bae27a1192",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IDUYDw/7OyB55OgZxQyc+tZm1TcLwL+tlPDfFWcNvK3CAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x35180f0ffb3b2079e4e819c50c9cfad666d5370bc0bfad94f0df15670dbcadc2",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IIjm0tiqZWJpGjY7fcwimlIauosR/ciL+OSW2ABxCNdKAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x88e6d2d8aa6562691a363b7dcc229a521aba8b11fdc88bf8e496d8007108d74a",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18, line 252:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 19, line 254:
//# create-checkpoint
Checkpoint created: 7

task 20, lines 256-285:
//# run-graphql --cursors @{obj_1_3,1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
