processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 16-29:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 31:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 33:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 35:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 37-65:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": []
      }
    },
    "if_the_other_does_not": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          }
        }
      ]
    }
  }
}

task 6, line 67:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 69:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 71:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 73-101:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": []
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          }
        }
      ]
    }
  }
}

task 10, lines 103-118:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                "value": "1"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                "value": "3"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 120-145:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                "value": "1"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                "value": "3"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 147-148:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 5259200, non_refundable_storage_fee: 0

task 13, line 150:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 152-214:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 4,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                "value": "1"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
                        },
                        "json": {
                          "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                          "value": "2"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 218:
//# create-checkpoint
Checkpoint created: 4

task 18, line 222:
//# create-checkpoint
Checkpoint created: 5

task 19, line 224:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 20, line 226:
//# create-checkpoint
Checkpoint created: 6

task 21, lines 228-243:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 245-261:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                "value": "1"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 23, lines 263-289:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x313999574a927527544dd47e70eeb379cbac96099cad54784f0cefaa915bf116",
                "value": "1"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0x421d260780b55a9eaa4cb8124c27f11f37fcb4c983f1d1fad91001769b8df07d",
                "value": "3"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xd138ca6f6ecef6233444a26b905caef192f8fcd626c63d144a5342f076bcec49",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xfccd421c62fb5bd39e4f63cb7ab84f49260c8434b660b9b3ccc9165ac66696c6::M1::Object"
              },
              "json": {
                "id": "0xdd38c7822863cbdd7cab6d4de874f518ec607a9fffa9039c43aa742fc400fb4f",
                "value": "2"
              }
            }
          }
        ]
      }
    }
  }
}
