processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5449200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, line 32:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::update --sender A --args 100 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 1307200, non_refundable_storage_fee: 0

task 5, line 36:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 38-66:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 68:
//# run Test::M1::update --sender A --args 200 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 8, line 70:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 72-101:
//# run-graphql --cursors @{obj_3_0,1}
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 103-178:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "200"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x1064f0e2c1402df49da99967e53770ca27892458ce8a9ea983db9d1f13d8ce61",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x1064f0e2c1402df49da99967e53770ca27892458ce8a9ea983db9d1f13d8ce61",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 11, line 180:
//# run Test::M1::update --sender A --args 300 object(3,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 2287600, non_refundable_storage_fee: 0

task 12, line 182:
//# create-checkpoint
Checkpoint created: 3

task 13, lines 184-247:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x1064f0e2c1402df49da99967e53770ca27892458ce8a9ea983db9d1f13d8ce61",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 14, lines 249-324:
//# run-graphql --cursors @{obj_3_0,3}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "200"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x1064f0e2c1402df49da99967e53770ca27892458ce8a9ea983db9d1f13d8ce61",
                "value": "300"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
              },
              "json": {
                "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x0ba09e699b7a2c69fcf9e5c3b84610345a7f92bc8aad27d06a82aa10a94f0cf5",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x8ba0645055ca9407f1fda27d9c5a12697215f596238dc5db7eaf434471bd1e0a::M1::Object"
                        },
                        "json": {
                          "id": "0x1064f0e2c1402df49da99967e53770ca27892458ce8a9ea983db9d1f13d8ce61",
                          "value": "300"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
