processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 16-29:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 31:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 33:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 35:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 37-65:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6, line 67:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 69:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 71:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 73-101:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10, lines 103-118:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                "value": "2"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 120-145:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                "value": "2"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 147-148:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 5259200, non_refundable_storage_fee: 0

task 13, line 150:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 152-214:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                "value": "0"
              }
            },
            "owner_at_latest_state_has_iota_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_iota_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x8cc2a7bc18cb7b94bcd1dbd6e3acc7db8b447cfedbff284c230bf5c3423dafb8",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
                        },
                        "json": {
                          "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 218:
//# create-checkpoint
Checkpoint created: 4

task 18, line 222:
//# create-checkpoint
Checkpoint created: 5

task 19, line 224:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 20, line 226:
//# create-checkpoint
Checkpoint created: 6

task 21, lines 228-243:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22, lines 245-261:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 23, lines 263-289:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x33e71ed21f18a4581f5b9c4472a2ca5cfea62b674846bcdb59c1ce265cce7c65",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0x5941fbfba611b8863ab492e93f2865a53b3cb64680978fe7e30046e0e443a14c",
                "value": "2"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xacaebcc5ec4007606fe12e5a5e2e5f08117b69a1230ec75d1c2dd04056d293fe",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xdba8b85775e730f7d15abfd3066668cf163cec980587f830f70a40d86b307fa0::M1::Object"
              },
              "json": {
                "id": "0xcbb00d35df539f6c42065d152c9482e80068279c542d32107a63e1b2c9847c74",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}
