processed 20 tasks

init:
A: object(0,0)

task 1, lines 20-57:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7014800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 59:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-76:
//# run-graphql
Response: {
  "data": {
    "object": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "0"
          }
        }
      }
    }
  }
}

task 5, line 78:
//# run Test::M1::update --sender A --args object(2,0) 1
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1314800, non_refundable_storage_fee: 0

task 6, line 80:
//# create-checkpoint
Checkpoint created: 2

task 7, lines 82-108:
//# run-graphql
Response: {
  "data": {
    "latest_version": {
      "status": "INDEXED",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "0"
          }
        }
      }
    }
  }
}

task 8, line 110:
//# run Test::M1::wrap --sender A --args object(2,0)
created: object(8,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 9, line 112:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 114-140:
//# run-graphql
Response: {
  "data": {
    "latest_wrapped": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "previous_version": {
      "status": "INDEXED",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "1"
          }
        }
      }
    }
  }
}

task 11, line 142:
//# run Test::M1::unwrap --sender A --args object(8,0)
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(8,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2553600, non_refundable_storage_fee: 0

task 12, line 144:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 146-184:
//# run-graphql
Response: {
  "data": {
    "latest_unwrapped": {
      "status": "INDEXED",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "first_version": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "0"
          }
        }
      }
    }
  }
}

task 14, line 186:
//# run Test::M1::delete --sender A --args object(2,0)
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 15, line 188:
//# create-checkpoint
Checkpoint created: 5

task 16, lines 190-216:
//# run-graphql
Response: {
  "data": {
    "latest_deleted": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    },
    "version_specified": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    }
  }
}

task 17, line 218:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 5
Objects snapshot updated to [0 to 5)

task 18, line 220:
//# create-checkpoint
Checkpoint created: 6

task 19, lines 222-261:
//# run-graphql
Response: {
  "data": {
    "object_within_available_range": {
      "status": "INDEXED",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "1"
          }
        }
      }
    },
    "object_outside_available_range": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "object_not_in_snapshot": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xf590274bb295a6aa90f3204376664a126cd7991dc55a51a097c0f131a51a1688",
            "value": "0"
          }
        }
      }
    }
  }
}
