processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5456800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 32:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::update --sender A --args 100 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1314800, non_refundable_storage_fee: 0

task 5, line 36:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 38-66:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 7, line 68:
//# run Test::M1::update --sender A --args 200 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 8, line 70:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 72-101:
//# run-graphql --cursors @{obj_3_0,1}
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 10, lines 103-178:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xce38c4975a2275a5731f5ecc04913f38976e4500595b6dcfae8badf010560a8c",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xce38c4975a2275a5731f5ecc04913f38976e4500595b6dcfae8badf010560a8c",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}

task 11, line 180:
//# run Test::M1::update --sender A --args 300 object(3,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 12, line 182:
//# create-checkpoint
Checkpoint created: 3

task 13, lines 184-247:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xce38c4975a2275a5731f5ecc04913f38976e4500595b6dcfae8badf010560a8c",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 14, lines 249-324:
//# run-graphql --cursors @{obj_3_0,3}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xce38c4975a2275a5731f5ecc04913f38976e4500595b6dcfae8badf010560a8c",
                "value": "300"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
              },
              "json": {
                "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xce38c4975a2275a5731f5ecc04913f38976e4500595b6dcfae8badf010560a8c",
                          "value": "300"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x8e56739ab3b3769e4c9713c7385f1ef135a3e9ef17eeeecbe11f21f8e4491a9b::M1::Object"
                        },
                        "json": {
                          "id": "0xf1c8cfb859967b0fa6ed561eef82391ae0543be85161f037def1518fbf63e3fa",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}
