processed 15 tasks

init:
C: object(0,0)

task 1 'run-graphql'. lines 7-19:
Response: {
  "data": {
    "address": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 2 'programmable'. lines 21-23:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 25-25:
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [224, 254, 135, 74, 173, 170, 72, 210, 205, 206, 11, 96, 21, 79, 25, 36, 170, 113, 10, 64, 232, 245, 75, 115, 20, 97, 24, 171, 22, 151, 46, 165, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 15108800,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 4 'create-checkpoint'. lines 27-27:
Checkpoint created: 1

task 5 'advance-epoch'. lines 29-29:
Epoch advanced: 0

task 6 'programmable'. lines 31-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 35-35:
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [224, 254, 135, 74, 173, 170, 72, 210, 205, 206, 11, 96, 21, 79, 25, 36, 170, 113, 10, 64, 232, 245, 75, 115, 20, 97, 24, 171, 22, 151, 46, 165, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(7,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0), object(3,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 15108800,  storage_rebate: 14656752, non_refundable_storage_fee: 148048

task 8 'create-checkpoint'. lines 37-37:
Checkpoint created: 3

task 9 'advance-epoch'. lines 39-39:
Epoch advanced: 1

task 10 'view-object'. lines 41-41:
Owner: Account Address ( C )
Version: 3
Contents: iota_system::staking_pool::StakedIota {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,1)}}, pool_id: iota::object::ID {bytes: _}, stake_activation_epoch: 1u64, principal: iota::balance::Balance<iota::iota::IOTA> {value: 10000000000u64}}

task 11 'view-object'. lines 43-43:
Owner: Account Address ( C )
Version: 5
Contents: iota_system::staking_pool::StakedIota {id: iota::object::UID {id: iota::object::ID {bytes: fake(7,0)}}, pool_id: iota::object::ID {bytes: _}, stake_activation_epoch: 2u64, principal: iota::balance::Balance<iota::iota::IOTA> {value: 10000000000u64}}

task 12 'run-graphql'. lines 45-57:
Response: {
  "data": {
    "address": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IESPO/G8XA44r6SzmAwmTxKFwz57ASpPj4qyJi5qiNezBAAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          },
          {
            "cursor": "IGNUSo0Wtii8qNLV2YiihYoo1wW0NXNyv5S+3AvklredBAAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 59-103:
Response: {
  "data": {
    "no_coins_after_obj_3_1_chkpt_1": {
      "stakedIotas": {
        "edges": []
      }
    },
    "no_coins_before_obj_3_1_chkpt_1": {
      "stakedIotas": {
        "edges": []
      }
    },
    "no_coins_after_obj_7_0_chkpt_1": {
      "stakedIotas": {
        "edges": []
      }
    },
    "no_coins_before_obj_7_0_chkpt_1": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 14 'run-graphql'. lines 105-148:
Response: {
  "data": {
    "coins_after_obj_3_1_chkpt_3": {
      "stakedIotas": {
        "edges": []
      }
    },
    "coins_before_obj_3_1_chkpt_3": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IESPO/G8XA44r6SzmAwmTxKFwz57ASpPj4qyJi5qiNezAwAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    },
    "coins_after_obj_7_0_chkpt_3": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IGNUSo0Wtii8qNLV2YiihYoo1wW0NXNyv5S+3AvklredAwAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    },
    "coins_before_obj_7_0_chkpt_3": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}
