processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 18-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 37-38:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 40:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 42-45:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5, line 47:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 49-53:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 7, line 55:
//# create-checkpoint
Checkpoint created: 3

task 9, line 59:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 61-135:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                "value": "6"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                "value": "200"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                "value": "3"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                "value": "2"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                "value": "5"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                "value": "4"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 137-181:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 183:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 185:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 187-261:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                "value": "6"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                "value": "200"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                "value": "3"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                "value": "2"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                "value": "5"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                "value": "4"
              },
              "type": {
                "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x609b6c99b98a8503a8df95b89e4e2e41dea90a4ffe19c0e732c9d82024541b21",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 263:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 265-300:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x18af24877e0e94def108a91eb5d43d1c85ab2f129adc6c29d48b1ba1af612cbd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8b713623c4253a0a31d930187ebf94e1214015a1af24d20a7778cbc939fa133e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa0e65a918d9f886135294ccc13deeb90ab2a3fca09dcde928448c6c173ceb995",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa7da47c1528a286b0d2814e4836a974e366defdf120b95f7f7509a1309ac7392",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a53c52370cf06bb95d75b816b5edc4e883f060518a91e9bebb7a65f6442536",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd541ee18fc789bdbae612e374d12d8d6ad7548d21a32f11139d4e46b1f741ad8",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x0c036868a9741e923b3822d0b93874f374117f0f8f085a2c35156e796930762e::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
