processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 18-35:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 37-38:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 40-40:
Checkpoint created: 1

task 4 'programmable'. lines 42-45:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 47-47:
Checkpoint created: 2

task 6 'programmable'. lines 49-53:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 55-55:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 59-59:
Checkpoint created: 4

task 10 'run-graphql'. lines 61-135:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                "value": "200"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                "value": "3"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                "value": "6"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                "value": "5"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                "value": "2"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                "value": "4"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0xad17977b4193a8c3be1b3ab08cca5a66a2ba171684ab7ba10835b8ff720d140a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 137-181:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0xad17977b4193a8c3be1b3ab08cca5a66a2ba171684ab7ba10835b8ff720d140a",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0xad17977b4193a8c3be1b3ab08cca5a66a2ba171684ab7ba10835b8ff720d140a",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0xad17977b4193a8c3be1b3ab08cca5a66a2ba171684ab7ba10835b8ff720d140a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 183-183:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 185-185:
Checkpoint created: 5

task 14 'run-graphql'. lines 187-261:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                "value": "200"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                "value": "3"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                "value": "6"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                "value": "5"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                "value": "2"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                "value": "4"
              },
              "type": {
                "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0xad17977b4193a8c3be1b3ab08cca5a66a2ba171684ab7ba10835b8ff720d140a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 263-263:
Checkpoint created: 6

task 16 'run-graphql'. lines 265-300:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x13404542042153f8a5de00fecf2c0e8e2a27b0a6ad331cab4470f8074839ae60",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x7c388cc9d4c175101e673778607cdda85c644bc37e0009c521c36a6421c0520d",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xa2ef3b9af9b6ce5d6eeaecd63eece88c52bbd712043c9ac3eafa6c03f2555147",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1a1905314dcf0eecf0422b1d717bdd281d846edc19a8e754151239d480c2ff0",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd84e6ec96c476e644937ab92f8abdb602430b42be678be4d15ab0392b56be467",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xfa32f6eb6058aebe08893cec51ddbf0edb1f5fb39316318daa4339d6969da561",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x51afa67acf635c948665bf4bcf305e05941d838a37fb566baed8ec4840671962::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
