processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 18-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 37-38:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 40:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 42-45:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5, line 47:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 49-53:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 7, line 55:
//# create-checkpoint
Checkpoint created: 3

task 9, line 59:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 61-135:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                "value": "4"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                "value": "5"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                "value": "3"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                "value": "200"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                "value": "6"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                "value": "2"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x1fd0f50cd017f97b048a4a779dbc67cb5387d17a79984b1819a429b7ffb4ef53",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 137-181:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x1fd0f50cd017f97b048a4a779dbc67cb5387d17a79984b1819a429b7ffb4ef53",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x1fd0f50cd017f97b048a4a779dbc67cb5387d17a79984b1819a429b7ffb4ef53",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x1fd0f50cd017f97b048a4a779dbc67cb5387d17a79984b1819a429b7ffb4ef53",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 183:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 13, line 185:
//# create-checkpoint
Checkpoint created: 5

task 14, lines 187-261:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                "value": "4"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                "value": "5"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                "value": "3"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                "value": "200"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                "value": "6"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                "value": "2"
              },
              "type": {
                "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                      },
                      "json": {
                        "id": "0x1fd0f50cd017f97b048a4a779dbc67cb5387d17a79984b1819a429b7ffb4ef53",
                        "balance": {
                          "value": "299999993067600"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15, line 263:
//# create-checkpoint
Checkpoint created: 6

task 16, lines 265-300:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x4f263537d7fe5e33e686f35580d88127cf67ca98fe3cce7dd910635eba391586",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5941bc00a228a02d0db39d77f0cf61e36dbe9a1013f273e9ed0ee02eb3259160",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x620fc261f44d1a27f42d6c8bd9d95c22c781966926056c56e4274140ba02d1b6",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaed872c4119b75506c212811899e9414db6106e3f687222db8833062003fa46e",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xba33c3291e8547a7ee8c971c786ffa720d3df52650e5ff493be10d52c86688d9",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc331b92ab20dd4a424b17a2c0bf507b935a92f84caee9b6f9717a61dc356607c",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfc270c987b7201d57da23ca7c3f431b2363860e19bb32efae81175586340241d::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
