processed 7 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-62:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 8458800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 64:
//# run test::m::mint --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 66:
//# run test::m::add --sender A --args object(2,0) 0
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5859600,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 4, line 68:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5, line 70:
//# run test::m::remove --sender A --args object(2,0) 0
mutated: object(0,0), object(2,0)
deleted: object(3,0), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 5859600, non_refundable_storage_fee: 0

task 6, line 72:
//# run test::m::freeze_object --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0
