processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-46:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6976800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 48:
//# run test::m::mint_and_share --sender A
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5859600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 50-54:
//# view-object 2,1
Owner: Shared( 2 )
Version: 2
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 4, line 56:
//# run test::m::mint --sender A
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5859600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 58:
//# run test::m::transfer --sender A --args object(4,2) @B
mutated: object(0,0), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 6, lines 60-64:
//# view-object 4,2
Owner: Account Address ( B )
Version: 4
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,2),
        },
    },
}

task 7, line 66:
//# run test::m::mint --sender A
created: object(7,0), object(7,1), object(7,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5859600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 68:
//# transfer-object 7,1 --sender A --recipient B
mutated: object(0,0), object(7,1)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 9, line 70:
//# view-object 7,1
Owner: Account Address ( B )
Version: 6
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(7,1),
        },
    },
}
