processed 4 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-37:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6072400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 39-39:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2439600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 41-41:
mutated: object(0,0)
unwrapped: object(3,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2439600, non_refundable_storage_fee: 0
