processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-18:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5183200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 20-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7668400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'publish'. lines 49-73:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8215600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'run'. lines 75-75:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5 'run'. lines 77-77:
created: object(5,0), object(5,1)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 5920400,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 6 'view-object'. lines 79-79:
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: t3::o3::Obj3 {id: iota::object::UID {id: iota::object::ID {bytes: fake(4,0)}}}

task 7 'view-object'. lines 81-83:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,1)}}}

task 8 'run'. lines 84-84:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(4,0), parent_id: object(5,0) }
