processed 9 tasks

init:
A: object(0,0)

task 1, lines 7-18:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5183200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 20-46:
//# publish --dependencies t3
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7668400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 49-73:
//# publish --dependencies t2 t3
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8215600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 75:
//# run t3::o3::create --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 77:
//# run t2::o2::create_shared --args object(4,0) --sender A
created: object(5,0), object(5,1)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 5920400,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 6, line 79:
//# view-object 4,0
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: t3::o3::Obj3 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,0),
        },
    },
}

task 7, lines 81-83:
//# view-object 5,1
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,1),
        },
    },
}

task 8, line 84:
//# run t1::o1::use_o2_o3 --args object(5,1) object(4,0) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(4,0), parent_id: object(5,0) }
