bytecode-interpreter-crypto:
  - "external-crates/move/crates/bytecode-interpreter-crypto/**"
bytecode-interpreter-testsuite:
  - "external-crates/move/crates/bytecode-interpreter-testsuite/**"
bytecode-verifier-libfuzzer:
  - "external-crates/move/crates/bytecode-verifier-libfuzzer/**"
bytecode-verifier-tests:
  - "external-crates/move/crates/bytecode-verifier-tests/**"
bytecode-verifier-transactional-tests:
  - "external-crates/move/crates/bytecode-verifier-transactional-tests/**"
enum-compat-util:
  - "external-crates/move/crates/enum-compat-util/**"
invalid-mutations:
  - "external-crates/move/crates/invalid-mutations/**"
language-benchmarks:
  - "external-crates/move/crates/language-benchmarks/**"
module-generation:
  - "external-crates/move/crates/module-generation/**"
move-abstract-stack:
  - "external-crates/move/crates/move-abstract-stack/**"
move-analyzer:
  - "external-crates/move/crates/move-analyzer/**"
move-binary-format:
  - "external-crates/move/crates/move-binary-format/**"
move-borrow-graph:
  - "external-crates/move/crates/move-borrow-graph/**"
move-bytecode-source-map:
  - "external-crates/move/crates/move-bytecode-source-map/**"
move-bytecode-utils:
  - "external-crates/move/crates/move-bytecode-utils/**"
move-bytecode-verifier:
  - "external-crates/move/crates/move-bytecode-verifier/**"
move-bytecode-viewer:
  - "external-crates/move/crates/move-bytecode-viewer/**"
move-cli:
  - "external-crates/move/crates/move-cli/**"
move-command-line-common:
  - "external-crates/move/crates/move-command-line-common/**"
move-compiler:
  - "external-crates/move/crates/move-compiler/**"
move-compiler-transactional-tests:
  - "external-crates/move/crates/move-compiler-transactional-tests/**"
move-core-types:
  - "external-crates/move/crates/move-core-types/**"
move-coverage:
  - "external-crates/move/crates/move-coverage/**"
move-disassembler:
  - "external-crates/move/crates/move-disassembler/**"
move-docgen:
  - "external-crates/move/crates/move-docgen/**"
move-errmapgen:
  - "external-crates/move/crates/move-errmapgen/**"
move-explain:
  - "external-crates/move/crates/move-explain/**"
move-ir-compiler:
  - "external-crates/move/crates/move-ir-compiler/**"
move-ir-compiler-transactional-tests:
  - "external-crates/move/crates/move-ir-compiler-transactional-tests/**"
move-ir-to-bytecode:
  - "external-crates/move/crates/move-ir-to-bytecode/**"
move-ir-to-bytecode-syntax:
  - "external-crates/move/crates/move-ir-to-bytecode-syntax/**"
move-ir-types:
  - "external-crates/move/crates/move-ir-types/**"
move-model:
  - "external-crates/move/crates/move-model/**"
move-package:
  - "external-crates/move/crates/move-package/**"
move-proc-macros:
  - "external-crates/move/crates/move-proc-macros/**"
move-prover-test-utils:
  - "external-crates/move/crates/move-prover-test-utils/**"
move-read-write-set-types:
  - "external-crates/move/crates/move-read-write-set-types/**"
move-stackless-bytecode:
  - "external-crates/move/crates/move-stackless-bytecode/**"
move-stackless-bytecode-interpreter:
  - "external-crates/move/crates/move-stackless-bytecode-interpreter/**"
move-stdlib:
  - "external-crates/move/crates/move-stdlib/**"
move-symbol-pool:
  - "external-crates/move/crates/move-symbol-pool/**"
move-transactional-test-runner:
  - "external-crates/move/crates/move-transactional-test-runner/**"
move-unit-test:
  - "external-crates/move/crates/move-unit-test/**"
move-vm-config:
  - "external-crates/move/crates/move-vm-config/**"
move-vm-integration-tests:
  - "external-crates/move/crates/move-vm-integration-tests/**"
move-vm-profiler:
  - "external-crates/move/crates/move-vm-profiler/**"
move-vm-runtime:
  - "external-crates/move/crates/move-vm-runtime/**"
move-vm-test-utils:
  - "external-crates/move/crates/move-vm-test-utils/**"
move-vm-transactional-tests:
  - "external-crates/move/crates/move-vm-transactional-tests/**"
move-vm-types:
  - "external-crates/move/crates/move-vm-types/**"
serializer-tests:
  - "external-crates/move/crates/serializer-tests/**"
test-generation:
  - "external-crates/move/crates/test-generation/**"
