processed 3 tasks

task 0 'publish'. lines 5-12:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Expected last parameter for _::m::init to be &mut iota::tx_context::TxContext or &iota::tx_context::TxContext, but found u64"), command: Some(0) } }

task 1 'publish'. lines 14-21:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Expected last parameter for _::tx_context::init to be &mut iota::tx_context::TxContext or &iota::tx_context::TxContext, but found _::tx_context::TxContext"), command: Some(0) } }

task 2 'publish'. lines 23-30:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Expected last parameter for _::m::init to be &mut iota::tx_context::TxContext or &iota::tx_context::TxContext, but found iota::tx_context::TxContext"), command: Some(0) } }
