packages:
  - "sdk/**"
  - "apps/**"
  - "dapps/**"
  - "docs/site"
  - "!**/dist/**"
  - "!**/.next/**"
  - "!sdk/create-dapp/templates"
  - "!sdk/typescript/bcs"
  - "!sdk/typescript/client"
  - "!sdk/typescript/cryptography"
  - "!sdk/typescript/faucet"
  - "!sdk/typescript/graphql"
  - "!sdk/typescript/graphql/schemas/2024-01"
  - "!sdk/typescript/keypairs/ed25519"
  - "!sdk/typescript/keypairs/secp256k1"
  - "!sdk/typescript/keypairs/secp256r1"
  - "!sdk/typescript/multisig"
  - "!sdk/typescript/scripts"
  - "!sdk/typescript/transactions"
  - "!sdk/typescript/utils"
  - "!sdk/typescript/verify"
  - "!sdk/typescript/zklogin"
  - "!sdk/move-bytecode-template/pkg"
  - "!sdk/move-bytecode-template/pkg"
  - "!sdk/docs"
