error[Iota E01001]: invalid object construction
   ┌─ tests/iota_mode/id_leak/through_pack.move:22:17
   │
22 │         let c = C { id };
   │                 ^^^^^^^^
   │                 │   │
   │                 │   The UID must come directly from iota::object::new. Or for tests, it can come from iota::test_scenario::new_object
   │                 Invalid object creation without a newly created UID.

