processed 4 tasks

task 1 'publish'. lines 7-20:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6642400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 22-22:
Owner: Account Address ( _ )
Version: 2
Contents: Test::M1::Object {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,1)}}, value: 42u64}

task 3 'view-object'. lines 24-24:
1,0::M1
