processed 14 tasks

init:
A: object(0,0)

task 1, lines 9-220:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 20869600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 222-224:
//# programmable --sender A --inputs @A
//> 0: test::m::new();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,8), object(2,9)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 17654800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 226:
//# view-object 2,9
Owner: Account Address ( A )
Version: 2
Contents: test::m::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,9),
        },
    },
}

task 4, lines 228-229:
//# programmable --sender A --inputs object(2,9) 112
//> test::m::set(Input(0), Input(1))
mutated: object(0,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,8), object(2,9)
gas summary: computation_cost: 1000000, storage_cost: 13968800,  storage_rebate: 13968800, non_refundable_storage_fee: 0

task 5, line 231:
//# view-object 2,9
Owner: Account Address ( A )
Version: 3
Contents: test::m::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,9),
        },
    },
}

task 6, lines 233-234:
//# programmable --sender A --inputs object(2,9) 112
//> test::m::remove(Input(0))
mutated: object(0,0), object(2,9)
deleted: object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,8)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 13968800, non_refundable_storage_fee: 0

task 7, lines 236-239:
//# view-object 2,9
Owner: Account Address ( A )
Version: 4
Contents: test::m::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,9),
        },
    },
}

task 8, lines 241-242:
//# programmable --sender A --inputs object(2,9)@2 vector[0] --dev-inspect
//> test::m::check(Input(0), Input(1))
mutated: object(_), object(2,9)
gas summary: computation_cost: 500000, storage_cost: 2234400,  storage_rebate: 1246400, non_refundable_storage_fee: 0

task 9, lines 244-245:
//# programmable --sender A --inputs object(2,9)@3 vector[112] --dev-inspect
//> test::m::check(Input(0), Input(1))
mutated: object(_), object(2,9)
gas summary: computation_cost: 500000, storage_cost: 2234400,  storage_rebate: 1246400, non_refundable_storage_fee: 0

task 10, lines 247-252:
//# programmable --sender A --inputs object(2,9)@4 vector[] --dev-inspect
//> test::m::check(Input(0), Input(1))
// dev-inspect with 'check' and _incorrect_ values
// Should fail since the field exists but with a different field.
mutated: object(_), object(2,9)
gas summary: computation_cost: 500000, storage_cost: 2234400,  storage_rebate: 1246400, non_refundable_storage_fee: 0

task 11, lines 253-256:
//# programmable --sender A --inputs object(2,9)@3 vector[0] --dev-inspect
//> test::m::check(Input(0), Input(1))
// Should fail since the field has been deleted.
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 15, instruction: 12, function_name: Some("check_") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 15, instruction: 12, function_name: Some("check_") }, 0) in command 0

task 12, lines 257-260:
//# programmable --sender A --inputs object(2,9)@4 vector[112] --dev-inspect
//> test::m::check(Input(0), Input(1))
// Should fail since at the version of the object we're passing in the field exists still
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0

task 13, lines 261-262:
//# programmable --sender A --inputs object(2,9)@2 vector[] --dev-inspect
//> test::m::check(Input(0), Input(1))
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 15, instruction: 20, function_name: Some("check_") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 15, instruction: 20, function_name: Some("check_") }, 0) in command 0
