processed 24 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-59:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10533600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 61-61:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7273200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 63-63:
Owner: Object ID: ( fake(2,3) )
Version: 2
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,1)}}

task 4 'view-object'. lines 65-65:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'view-object'. lines 67-67:
Owner: Account Address ( fake(2,2) )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}, value: 0u64}

task 6 'view-object'. lines 69-69:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 7 'run'. lines 71-71:
created: object(7,0)
mutated: object(0,0), object(2,2), object(2,3)
gas summary: computation_cost: 1000000, storage_cost: 5996400,  storage_rebate: 3541600, non_refundable_storage_fee: 0

task 8 'view-object'. lines 73-75:
Owner: Object ID: ( fake(2,3) )
Version: 2
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,1)}}

task 9 'view-object'. lines 76-76:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 10 'view-object'. lines 78-78:
Owner: Object ID: ( fake(7,0) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}, value: 0u64}

task 11 'view-object'. lines 80-80:
Owner: Account Address ( A )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 12 'programmable'. lines 82-83:
mutated: object(0,0), object(2,1), object(2,2), object(2,3)
gas summary: computation_cost: 1000000, storage_cost: 4818400,  storage_rebate: 4818400, non_refundable_storage_fee: 0

task 13 'view-object'. lines 85-87:
Owner: Object ID: ( fake(2,3) )
Version: 2
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,1)}}

task 14 'view-object'. lines 88-88:
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 3u64}

task 15 'view-object'. lines 90-90:
Owner: Object ID: ( fake(7,0) )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}, value: 2u64}

task 16 'view-object'. lines 92-92:
Owner: Account Address ( A )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 1u64}

task 17 'programmable'. lines 94-97:
mutated: object(0,0), object(2,2)
deleted: object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2264800,  storage_rebate: 5996400, non_refundable_storage_fee: 0

task 18 'programmable'. lines 99-100:
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2264800,  storage_rebate: 1276800, non_refundable_storage_fee: 0

task 19 'programmable'. lines 102-103:
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2264800,  storage_rebate: 1276800, non_refundable_storage_fee: 0

task 20 'programmable'. lines 105-108:
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2264800,  storage_rebate: 1276800, non_refundable_storage_fee: 0

task 21 'programmable'. lines 110-111:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: tto, name: Identifier("M1") }, function: 4, instruction: 10, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: tto, name: Identifier("M1") }, function: 4, instruction: 10, function_name: Some("check") }, 0) in command 0

task 22 'programmable'. lines 113-114:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0

task 23 'programmable'. lines 116-117:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: tto, name: Identifier("M1") }, function: 4, instruction: 10, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: tto, name: Identifier("M1") }, function: 4, instruction: 10, function_name: Some("check") }, 0) in command 0
