{
 "title": "IOTA Rebased Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(total_transaction_certificates[30s]) > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(current_epoch)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Checkpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(highest_synced_checkpoint)", "legendFormat": "__auto" }
   ]
  },
  { "type": "timeseries", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Validators List",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(irate(consensus_committed_messages[30s])) by (authority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"iota\"} |= \"WARN\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"indexer-reader\"} |= \"WARN\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"indexer-writer\"} |= \"WARN\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"faucet\"} |= \"WARN\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"graphql\"} |= \"WARN\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"iota\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"indexer-reader\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"indexer-writer\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"faucet\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    },
    {
     "expr": "sum without(filename, detected_level) (count_over_time({container_name=\"graphql\"} |= \"ERROR\" [1m]))",
     "legendFormat": "{{ host }} - {{ container_name }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "clamp_min(highest_synced_checkpoint - highest_known_checkpoint, 0)"
    },
    { "expr": "highest_known_checkpoint" },
    { "expr": "highest_synced_checkpoint" },
    { "expr": "current_epoch", "legendFormat": "__auto" },
    { "expr": "iota_network_peers", "legendFormat": "__auto" }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Certificates Created Rate (Avg. 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(rate(certificates_created[30s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Committed Messages (Avg. 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "sum(irate(consensus_committed_messages[30s])) by (authority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Narwhal Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "highest_processed_round{source=\"other\"} - ignoring(source) highest_processed_round{source=\"own\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "IOTA Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "irate(total_transaction_certificates[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Highest Synced Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    { "expr": "highest_synced_checkpoint", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    { "expr": "current_epoch", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Peering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    { "expr": "iota_network_peers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Checkpoint Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "clamp_min(highest_synced_checkpoint - highest_known_checkpoint, 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOTA Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(req_latency_by_route_sum[30s])",
     "legendFormat": "{{instance}} - {{ route }}"
    }
   ]
  },
  { "title": "Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Indexer Checkpoint Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "indexer_latest_fullnode_checkpoint_sequence_number - indexer_latest_indexer_checkpoint_sequence_number",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Indexer DB Commit Latency (Avg. 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(indexer_checkpoint_db_commit_latency_sum[30s])",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Indexer Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(indexer_req_latency_by_route_sum[30s])",
     "legendFormat": "{{instance}} - {{job}} - {{route}}"
    }
   ]
  },
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Requests Per Seconds (Avg 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(traefik_service_requests_total{instance=~\"lb.*\"}[30s])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Duration (Avg. 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(traefik_service_request_duration_seconds_sum{instance=~\"lb.*\"}[30s])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    { "expr": "traefik_service_server_up", "legendFormat": "{{service}}" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((sum(irate(node_cpu_seconds_total {mode!=\"idle\"} [1m])) without (cpu)) / count(node_cpu_seconds_total) without (cpu)) without (mode) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOTA CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"iota\"}[5m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Indexer CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"indexer.*\"}[5m]) * 100",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOTA Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=\"iota\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Indexer Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=~\"indexer.*\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Server Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scraping Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job!=\"cadvisor\"}",
     "legendFormat": "{{instance}}: {{job}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Commit Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=~\"iota_indexer\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Row Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Inserted: {{instance}}"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Updated: {{instance}}"
    },
    {
     "expr": "irate(pg_stat_database_tup_fetched{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Fetched: {{instance}}"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Returned: {{instance}}"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Deleted: {{instance}}"
    }
   ]
  },
  {
   "title": "Conflicts / Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_deadlocks{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Deadlock: {{instance}}"
    },
    {
     "expr": "irate(pg_stat_database_conflicts{datname=\"iota_indexer\"}[30s])",
     "legendFormat": "Conflicts: {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound / Outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "rate(iota_inbound_requests[1m])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Inbound Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(iota_inbound_request_latency_sum[30s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    },
    {
     "title": "Outbound Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "rate(iota_outbound_requests[1m])",
       "legendFormat": "{{instance}}({{route}})"
      }
     ]
    },
    {
     "title": "Outbound Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(iota_outbound_request_latency_sum[30s])",
       "legendFormat": "{{instance}} {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Replication",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 },
     "targets": [
      { "expr": "pg_replication_slots_active", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Replication WAL Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pg_stat_replication_pg_wal_lsn_diff",
       "legendFormat": "{{instance}} -> {{client_addr}} ({{state}})"
      }
     ]
    },
    {
     "title": "Replication Acknowledgment Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - pg_stat_replication_reply_time",
       "legendFormat": "{{instance}} -> {{client_addr}} ({{state}})"
      }
     ]
    }
   ]
  }
 ]
}