[package]
name = "move-vm-integration-tests"
version = "0.1.0"
authors = ["IOTA Foundation <contact@iota.org>"]
edition = "2021"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/diem/diem"
description = "Move VM Integration Tests"

[dependencies]
anyhow.workspace = true
fail = { workspace = true, features = ["failpoints"] }
memory-stats = "1.2"
tempfile.workspace = true

move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-stdlib.workspace = true
move-vm-config.workspace = true
move-vm-profiler.workspace = true
move-vm-runtime.workspace = true
move-vm-test-utils.workspace = true
move-vm-types.workspace = true

[features]
default = []
gas-profiler = [
  "move-vm-config/gas-profiler",
  "move-vm-runtime/gas-profiler",
  "move-vm-profiler/gas-profiler",
  "move-vm-types/gas-profiler",
  "move-vm-test-utils/gas-profiler",
]

[[bin]]
name = "instantiation"
path = "src/tests/instantiation_tests.rs"
