processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-33:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6627200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 35-35:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 37-37:
Owner: Shared
Version: 2
Contents: a::m::Obj {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'run'. lines 39-39:
created: object(4,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 3678400,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 5 'run'. lines 41-41:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'view-object'. lines 43-43:
Owner: Shared
Version: 4
Contents: a::m::Obj {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,0)}}}

task 7 'run'. lines 45-45:
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 2211600, non_refundable_storage_fee: 0
