processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-40:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7531600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 42-42:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 44-44:
Owner: Shared
Version: 2
Contents: a::m::Inner {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'run'. lines 46-46:
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 5 'run'. lines 48-48:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'view-object'. lines 50-50:
Owner: Shared
Version: 4
Contents: a::m::Inner {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,0)}}}

task 7 'run'. lines 52-52:
created: object(7,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3465600,  storage_rebate: 2226800, non_refundable_storage_fee: 0
