processed 8 tasks

init:
A: object(0,0)

task 1, lines 10-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 7683600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# run a::m::create_shared --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2211600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 44:
//# view-object 2,0
Owner: Shared( 2 )
Version: 2
Contents: a::m::Inner {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 46:
//# run a::m::add_dynamic_object_field --sender A --args object(2,0)
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 5, line 48:
//# run a::m::create_shared --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2211600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 50:
//# view-object 5,0
Owner: Shared( 4 )
Version: 4
Contents: a::m::Inner {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,0),
        },
    },
}

task 7, line 52:
//# run a::m::add_and_remove_dynamic_object_field --sender A --args object(5,0)
created: object(7,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3442800,  storage_rebate: 2211600, non_refundable_storage_fee: 0
