processed 11 tasks

task 1 'publish'. lines 7-36:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6399200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 38-38:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'run'. lines 40-40:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'view-object'. lines 42-42:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 5 'view-object'. lines 44-46:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}}

task 6 'programmable'. lines 47-49:
mutated: object(0,0), object(2,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 3465600, non_refundable_storage_fee: 0

task 7 'run'. lines 51-51:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8 'view-object'. lines 53-55:
Owner: Shared
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(7,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 0u64}}

task 9 'programmable'. lines 56-62:
created: object(9,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 10 'programmable'. lines 63-67:
created: object(10,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0
