processed 21 tasks

init:
A: object(0,0)

task 1, lines 14-61:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9279600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 63:
//# run t2::o2::mint_shared_coin
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 65:
//# run t2::o2::mint_owned_coin
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 67:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 5, lines 69-72:
//# view-object 3,0
Owner: Account Address ( A )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 6, lines 73-77:
//# programmable --sender A --inputs object(2,0) object(3,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::transferer(Input(1));
// **Merge owned into shared**
mutated: object(0,0), object(3,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 7, line 79:
//# run t2::o2::mint_owned_coin
created: object(7,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 81:
//# run t2::o2::mint_shared_coin
created: object(8,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9, line 83:
//# run t2::o2::mint_shared_obj
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 85:
//# view-object 7,0
Owner: Account Address ( A )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(7,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 11, line 87:
//# view-object 8,0
Owner: Shared( 6 )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(8,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 12, lines 89-91:
//# view-object 9,0
Owner: Shared( 7 )
Version: 7
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(9,0),
        },
    },
}

task 13, lines 92-96:
//# programmable --sender A --inputs object(7,0) object(8,0) object(9,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::deleter(Input(1));
// **Merge shared into shared**
mutated: object(0,0), object(9,0)
deleted: object(7,0), object(8,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 4202800, non_refundable_storage_fee: 0

task 14, line 98:
//# run t2::o2::mint_shared_coin
created: object(14,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 15, line 100:
//# run t2::o2::mint_shared_coin
created: object(15,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16, line 102:
//# run t2::o2::mint_shared_obj
created: object(16,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 17, line 104:
//# view-object 14,0
Owner: Shared( 8 )
Version: 8
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(14,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 18, line 106:
//# view-object 15,0
Owner: Shared( 9 )
Version: 9
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(15,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 19, lines 108-110:
//# view-object 16,0
Owner: Shared( 10 )
Version: 10
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(16,0),
        },
    },
}

task 20, lines 111-113:
//# programmable --sender A --inputs object(14,0) object(15,0) object(16,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::deleter(Input(1));
mutated: object(0,0), object(16,0)
deleted: object(14,0), object(15,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 4202800, non_refundable_storage_fee: 0
