processed 22 tasks

task 1, lines 7-98:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10959200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 100:
//# run t2::o2::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 102:
//# run t2::o2::create
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 104:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5, lines 106-108:
//# view-object 3,0
Owner: Shared( 4 )
Version: 4
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
}

task 6, lines 109-113:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::freezee(Result(0));
// Make MoveVec and then try to add as dof
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 7, lines 114-118:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::dof_(Input(0), Result(0));
// Make MoveVec and then try to add as df
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 8, lines 119-123:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::df_(Input(0), Result(0));
// Make MoveVec and then try to transfer it
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 9, lines 124-128:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::transfer_(Result(0));
// Make MoveVec pop and return it, then try to freeze
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 10, lines 129-134:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::pop_it(Result(0));
//> 2: t2::o2::freezer(Result(1));
// Make MoveVec pop and return it, then try to add as dof
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 11, lines 135-140:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::pop_it(Result(0));
//> 2: t2::o2::dofer(Input(0), Result(1));
// Make MoveVec pop and return it, then try to add as df
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 12, lines 141-146:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::pop_it(Result(0));
//> 2: t2::o2::dfer(Input(0), Result(1));
// Make MoveVec pop and return it, then try to transfer it
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 13, lines 147-152:
//# programmable --inputs object(2,0) object(3,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(1)]);
//> 1: t2::o2::pop_it(Result(0));
//> 2: t2::o2::transferer(Result(1));
// Make MoveVec pop and return it, then try to transfer it with PT transfer
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 14, lines 153-156:
//# programmable --inputs object(3,0) @0x0
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(0)]);
//> 1: t2::o2::pop_it(Result(0));
//> 2: TransferObjects([Result(1)], Input(1));
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 15, line 158:
//# run t2::o2::mint_shared_coin
created: object(15,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16, lines 160-163:
//# view-object 15,0
Owner: Shared( 14 )
Version: 14
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(15,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 17, lines 164-170:
//# programmable --inputs 0 object(15,0) @0x0
//> 0: MakeMoveVec([Input(1)]);
//> 1: t2::o2::pop_coin(Result(0));
//> 2: SplitCoins(Result(1), [Input(0)]);
//> 3: TransferObjects([Result(2)], Input(2));
// Try to call public_share_object directly -- this should fail
Error: Transaction Effects Status: Unused result without the drop ability. Command result 1, return value 0
Debug of error: UnusedValueWithoutDrop { result_idx: 1, secondary_idx: 0 } at command None

task 18, lines 171-179:
//# programmable --inputs 0 object(15,0) @0x0
//> 0: MakeMoveVec([Input(1)]);
//> 1: t2::o2::pop_coin(Result(0));
//> 2: SplitCoins(Result(1), [Input(0)]);
//> 3: TransferObjects([Result(2)], Input(2));
//> 4: iota::transfer::public_share_object(Input(1));
// Try to reshare the shared object -- this should fail since the input was
// used for the `MakeMoveVec` call
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Debug of error: VMVerificationOrDeserializationError at command Some(4)

task 19, lines 180-188:
//# programmable --inputs 0 object(15,0) @0x0
//> 0: MakeMoveVec([Input(1)]);
//> 1: t2::o2::pop_coin(Result(0));
//> 2: SplitCoins(Result(1), [Input(0)]);
//> 3: TransferObjects([Result(2)], Input(2));
//> 4: t2::o2::share_coin(Input(1));
// Try to transfer the shared object -- this should fail since the input was
// used for the `MakeMoveVec` call
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage } at command Some(4)

task 20, lines 189-196:
//# programmable --inputs 0 object(15,0) @0x0
//> 0: MakeMoveVec([Input(1)]);
//> 1: t2::o2::pop_coin(Result(0));
//> 2: SplitCoins(Result(1), [Input(0)]);
//> 3: TransferObjects([Result(2)], Input(2));
//> 4: TransferObjects([Input(1)], Input(2));
// Try to transfer the shared object
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage } at command Some(4)

task 21, lines 197-202:
//# programmable --inputs 0 object(15,0) @0x0
//> 0: MakeMoveVec([Input(1)]);
//> 1: t2::o2::pop_coin(Result(0));
//> 2: SplitCoins(Result(1), [Input(0)]);
//> 3: TransferObjects([Result(2)], Input(2));
//> 4: TransferObjects([Result(1)], Input(2));
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
