processed 7 tasks

task 1, lines 9-25:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5342800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 27-35:
//# publish --dependencies t2
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4453600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 38:
//# run t2::o2::create
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 40:
//# view-object 3,0
Owner: Shared( 4 )
Version: 4
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
}

task 5, line 42:
//# run t1::o1::consume_o2 --args object(3,0)
Error: Transaction Effects Status: Invalid command argument at 0. Immutable objects cannot be passed by-value.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue } at command Some(0)

task 6, line 44:
//# run t2::o2::consume_o2 --args object(3,0)
Error: Transaction Effects Status: Invalid command argument at 0. Immutable objects cannot be passed by-value.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue } at command Some(0)
