processed 9 tasks

task 1 'publish'. lines 10-27:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5342800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 29-37:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4453600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'run'. lines 39-39:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'view-object'. lines 41-43:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}}

task 5 'run'. lines 44-44:
mutated: object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 6 'run'. lines 46-46:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 48-50:
Owner: Shared
Version: 6
Contents: t2::o2::Obj2 {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}}

task 8 'run'. lines 51-51:
mutated: object(0,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2226800, non_refundable_storage_fee: 0
