processed 11 tasks

task 1, lines 7-36:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6399200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 38:
//# run t2::o2::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 40:
//# run t2::o2::create
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 42:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5, lines 44-46:
//# view-object 3,0
Owner: Shared( 4 )
Version: 4
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
}

task 6, lines 47-49:
//# programmable --inputs object(2,0) object(3,0)
//> 0: t2::o2::id<t2::o2::Obj2>(Input(1));
//> 1: t2::o2::deleter(Result(0));
mutated: object(0,0), object(2,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 3465600, non_refundable_storage_fee: 0

task 7, line 51:
//# run t2::o2::mint_shared_coin
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, lines 53-55:
//# view-object 7,0
Owner: Shared( 6 )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(7,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 9, lines 56-62:
//# programmable --inputs 0 object(7,0) @0x0
//> 0: t2::o2::id<iota::coin::Coin<iota::iota::IOTA>>(Input(1));
//> 1: SplitCoins(Result(0), [Input(0)]);
//> 2: TransferObjects([Result(1)], Input(2));
//> 3: t2::o2::share_coin(Result(0));
// Try to call public_share_object directly -- this should work because the coin has `store`.
created: object(9,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 10, lines 63-67:
//# programmable --inputs 0 object(7,0) @0x0
//> 0: t2::o2::id<iota::coin::Coin<iota::iota::IOTA>>(Input(1));
//> 1: SplitCoins(Result(0), [Input(0)]);
//> 2: TransferObjects([Result(1)], Input(2));
//> 3: iota::transfer::public_share_object<iota::coin::Coin<iota::iota::IOTA>>(Result(0));
created: object(10,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0
