processed 24 tasks

init:
A: object(0,0)

task 1, lines 14-63:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9279600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 65:
//# run t2::o2::mint_owned_coin
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 67:
//# run t2::o2::mint_shared_coin
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 69:
//# run t2::o2::mint_shared_obj
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 71:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 6, line 73:
//# view-object 3,0
Owner: Shared( 4 )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 7, lines 75-77:
//# view-object 4,0
Owner: Shared( 5 )
Version: 5
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,0),
        },
    },
}

task 8, lines 78-82:
//# programmable --sender A --inputs object(2,0) object(3,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::freezer(Input(1));
// Merge and then try to add as dof
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 9, lines 83-87:
//# programmable --sender A --inputs object(2,0) object(3,0) object(4,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::dofer(Input(2), Input(1));
// Merge and then try to add as df
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 10, lines 88-92:
//# programmable --sender A --inputs object(2,0) object(3,0) object(4,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::dfer(Input(2), Input(1));
// Merge and then try to transfer it
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 11, lines 93-97:
//# programmable --sender A --inputs object(2,0) object(3,0) object(4,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::transferer(Input(1));
// Merge and then try to transfer it with PTB transfer
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 12, lines 98-102:
//# programmable --sender A --inputs object(2,0) object(3,0) object(4,0) @A
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: TransferObjects([Input(1)], Input(3));
// **Merge shared into shared**
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 13, line 104:
//# run t2::o2::mint_shared_coin
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 14, line 106:
//# run t2::o2::mint_shared_coin
created: object(14,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 15, line 108:
//# run t2::o2::mint_shared_obj
created: object(15,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16, line 110:
//# view-object 13,0
Owner: Shared( 6 )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(13,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 17, line 112:
//# view-object 14,0
Owner: Shared( 7 )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(14,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 18, lines 114-116:
//# view-object 15,0
Owner: Shared( 8 )
Version: 8
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(15,0),
        },
    },
}

task 19, lines 117-121:
//# programmable --sender A --inputs object(13,0) object(14,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::freezer(Input(1));
// Merge and then try to add as dof
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 20, lines 122-126:
//# programmable --sender A --inputs object(13,0) object(14,0) object(15,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::dofer(Input(2), Input(1));
// Merge and then try to add as df
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 21, lines 127-131:
//# programmable --sender A --inputs object(13,0) object(14,0) object(15,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::dfer(Input(2), Input(1));
// Merge and then try to transfer it
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 22, lines 132-136:
//# programmable --sender A --inputs object(13,0) object(14,0) object(15,0)
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: t2::o2::transferer(Input(1));
// Merge and then try to transfer it with PTB transfer
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None

task 23, lines 137-139:
//# programmable --sender A --inputs object(13,0) object(14,0) object(15,0) @A
//> 0: MergeCoins(Input(1), [Input(0)]);
//> 1: TransferObjects([Input(1)], Input(3));
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
