processed 12 tasks

task 1, lines 9-30:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5882400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# run t2::o2::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 34:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 36:
//# run t2::o2::mut_o2 --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 5, line 38:
//# view-object 2,0
Owner: Shared( 3 )
Version: 4
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 6, line 40:
//# run t2::o2::re_share_o2 --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 7, line 42:
//# view-object 2,0
Owner: Shared( 3 )
Version: 5
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 8, line 44:
//# run t2::o2::re_share_non_public_o2 --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 9, line 46:
//# view-object 2,0
Owner: Shared( 3 )
Version: 6
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 10, line 48:
//# run t2::o2::mut_o2 --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2226800, non_refundable_storage_fee: 0

task 11, line 50:
//# view-object 2,0
Owner: Shared( 3 )
Version: 7
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}
