processed 5 tasks

task 1, lines 10-25:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5654400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 27:
//# run t2::o2::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 29:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 31:
//# run t2::o2::transfer_to_single_owner --args object(2,0)
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
