processed 1 task

task 0 'publish'. lines 4-11:
Error: Transaction Effects Status: IOTA Move Bytecode Verification Error. Please run the IOTA Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IOTAMoveVerificationError, source: Some("First field of struct S must be of type iota::object::UID, _::object::UID type found"), command: Some(0) } }
