processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::create --args 0 @A --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 31:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::create --args 0 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 35:
//# run Test::M1::create --args 0 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 37:
//# create-checkpoint
Checkpoint created: 1

task 7, line 39:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 41:
//# run Test::M1::create --args 0 @A --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9, line 43:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 45:
//# create-checkpoint
Checkpoint created: 2

task 11, line 47:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12, line 49:
//# run Test::M1::create --args 0 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 13, line 51:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 53-77:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "ARW7Huh9GW72bMvDoEUY2BQkU2TbgkJeuCtk538E65ud",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "Ay1h3NAkKnrkUif97h8ra2cf8ZyXzQvxUrJp7eaN89cV",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "CaWJtdWxxV8QcJyNnX8hnKRxeZsDTwNbRd3MHdRAnswP",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "8ThoJwqQb8Qfk6FCa4rm3ZaGZXPQNRJV5Q9juj1MKRPV",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "CvhQVJ7numDYf6yZL4nWtw6Xh5iGYGEyVo23eYzQrBg1",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "DQHEeQgLHCrvGvvMCwSf6nkPJSHPau76ubpxmh1dQpE9",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "FyorXheep61dt4Uwv6tAGULrjYVKwZMdzQr13C8y1Nwk",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "BHybRgj8Z9zf6yK7QHay4Y91ntSY7Tv4tbPFKNrdfUpd",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
                "node": {
                  "digest": "5XuV7BK4xMoHsgPyXjWiA4XTcAozfauKW1sdAZ7V9yfT",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOgjTJtf/6FlTpu0BCSEiQre3ONPUDwTdz0xbRu+TVWuAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15, lines 79-96:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
