processed 18 tasks

task 1 'create-checkpoint'. lines 32-32:
Checkpoint created: 12

task 2 'run-graphql'. lines 34-46:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        }
      ]
    }
  }
}

task 3 'run-graphql'. lines 48-60:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        }
      ]
    }
  }
}

task 4 'run-graphql'. lines 62-74:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 5 'run-graphql'. lines 76-88:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 6 'run-graphql'. lines 90-102:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        }
      ]
    }
  }
}

task 7 'run-graphql'. lines 104-116:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 118-130:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 9 'run-graphql'. lines 132-144:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 146-158:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 160-172:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 174-186:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 188-200:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 202-214:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 216-228:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 230-242:
Response: {
  "data": null,
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "checkpoints"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 17 'run-graphql'. lines 244-257:
Response: {
  "data": null,
  "errors": [
    {
      "message": "The provided cursors are taken from different checkpoints and cannot be used together in the same query.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "checkpoints"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
