processed 18 tasks

task 1, line 32:
//# create-checkpoint 12
Checkpoint created: 12

task 2, lines 34-46:
//# run-graphql --cursors {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        }
      ]
    }
  }
}

task 3, lines 48-60:
//# run-graphql --cursors {"c":12,"s":6} {"c":12,"s":8}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        }
      ]
    }
  }
}

task 4, lines 62-74:
//# run-graphql --cursors {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 5, lines 76-88:
//# run-graphql --cursors {"c":12,"s":3} {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 6, lines 90-102:
//# run-graphql --cursors {"c":12,"s":3}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        }
      ]
    }
  }
}

task 7, lines 104-116:
//# run-graphql --cursors {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 8, lines 118-130:
//# run-graphql --cursors {"c":12,"s":4}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 9, lines 132-144:
//# run-graphql --cursors {"c":12,"s":4}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 10, lines 146-158:
//# run-graphql --cursors {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 11, lines 160-172:
//# run-graphql --cursors {"c":12,"s":3} {"c":12,"s":6}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 12, lines 174-186:
//# run-graphql --cursors {"c":12,"s":9}
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 13, lines 188-200:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 14, lines 202-214:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 15, lines 216-228:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjIjoxMiwicyI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjIjoxMiwicyI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 16, lines 230-242:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "checkpoints"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 17, lines 244-257:
//# run-graphql --cursors {"c":10,"s":3} {"c":12,"s":6}
Response: {
  "data": null,
  "errors": [
    {
      "message": "The provided cursors are taken from different checkpoints and cannot be used together in the same query.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "checkpoints"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
