processed 11 tasks

task 1, lines 23-42:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5563200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 44-62:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 3, line 64:
//# run Test::M1::create --args 0 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, line 66:
//# view-object 3,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 5, line 68:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 70-88:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "owner": {
                "__typename": "AddressOwner",
                "owner": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7, lines 90-108:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "owner": {
                "__typename": "AddressOwner",
                "owner": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 8, lines 110-128:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 9, lines 130-148:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "objects": {
        "edges": [
          {
            "node": {
              "owner": {
                "__typename": "AddressOwner",
                "owner": {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 150-168:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}
