processed 26 tasks

init:
validator_0: object(0,0)

task 1, lines 7-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 32:
//# view-object 0,0
Owner: Account Address ( validator_0 )
Version: 1
Contents: iota_system::validator_cap::UnverifiedValidatorOperationCap {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(0,0),
        },
    },
    authorizer_validator_address: validator_0,
}

task 5, line 34:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 36:
//# view-object 3,0
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 38:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 40:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1976000, non_refundable_storage_fee: 0 }}

task 9, line 42:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 44:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: 9X2eEhaTREKQbXGbHrnnmvTm4TZfhhY5H6rUcecft8bX,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 46-51:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 53:
//# create-checkpoint
Checkpoint created: 11

task 13, line 55:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 57-62:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 64-69:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-iota-rpc-version": "2024.7.0-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 2024.7.0-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 71:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 73-76:
//# advance-epoch
Epoch advanced: 6

task 18, lines 78-93:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x6273faa79d73a191d238a3bdcc2b3c11eb976980b296d22d410f95c0f61d2fde",
              "digest": "121p5YAKxtozkekSFdYPAoFpViqUnAztxspya851dx9M",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 95-150:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x6273faa79d73a191d238a3bdcc2b3c11eb976980b296d22d410f95c0f61d2fde",
              "digest": "121p5YAKxtozkekSFdYPAoFpViqUnAztxspya851dx9M",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x0aa69d72003801ab057e567938016c0f832f1516937fc84a8b5c11ba06c06815",
              "digest": "8NvJsVTkKKDJgavep2F65Aff6gJmdWpxJJ7Hpe1dTZ7e",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x26bf0f03edd09bb3f862e13cec014d17c26dd739d2563d9c704aa8d206301df2",
              "digest": "qm9zxqHuMpn3adTZR7Hw4kx2E5cAApBrNZcCYMTj4q4",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x31e3256cfe19704fd29c7e8a8d0030b2d6101b8c04668ead7bf7d38257d9e002",
              "digest": "FXQKdY2oYvWnDGs3L2EuPYSYupHC8yhcsWBTtGP12DBr",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x3442446f02377d1025b211e51564e4f1c9a46845ccad733beeb06180d3f66c31",
              "digest": "GuVwJJNsKJwzmufHJCmPMW27fYZf2JNS2SNT3gi1XSgj",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x3c88cad5799a8da0467b8456a7429a97e7c141cfcf25f02faf51aa8cb4840461",
              "digest": "abMq2H3FqVggiupt3CknW1YNEKFZdYGTZNu7XpU7YsX",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x847c914d647e7387d7cea4db5ad8fefeffe66773635804a991dfd4385fab6a97",
              "digest": "HpzDcE6Fz6Nbk1KNhY1c1qU5QxCAaHXzFA1hfYfhFMHz",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x892836945e37c3a48c0dde074d3a079a50dfc47c1fbde03d7409064340b1f743",
              "digest": "6saYWQXDNUMksgPTxBkir1ZHoh6L6A1sXJ14CTTTPLkx",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xa79cc544021a721176cdc4497728ec35a5311b8ff0aa293a5d29c0d32cb56056",
              "digest": "844BRJc3iC63fki2xFCUuVwTJead6GqviJHFvgGmxyj5",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xab2415a43bf8f72193ec765f63af9cf7705bb3a312b0a14f1332be3f74d81c58",
              "digest": "6p1wpzeYh47gcC9FC22Po8N1wCHMEyaZJwB4QzLRdcFo",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xac9c2e11aebecd35b4cb15802ca6ad5e64d320204149187ba646a16d07a4934d",
              "digest": "35hWuW17ahJAyBFSWHZH2f8LNNDTF4mVT362X7FSyhJ6",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xb21c0b03871456040643740e238d03bde38de240d7b17055f4670777a19f07b8",
              "digest": "HRC6wHwgsx4WmFhWVAJSDAMMAFoVZtGKSWrv78QDrzxn",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xfb29acaee47f4cf6dfd7d21773f74fb65f842e9483b194b06bf83f91c0460bf3",
              "digest": "CsCUE4uQeGjvUMAAFkh1sh2rfLfLdBXJHy7aBv1TfuPo",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 152-168:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
    }
  }
}

task 21, lines 170-176:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 178:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 23, line 180:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 24, line 182:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 25, lines 184-189:
//# run-graphql
Response: {
  "data": {
    "serviceConfig": {
      "availableVersions": [
        "2024.7"
      ]
    }
  }
}
