processed 26 tasks

init:
validator_0: object(0,0)

task 1, lines 7-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 32:
//# view-object 0,0
Owner: Account Address ( validator_0 )
Version: 1
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(0,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 30000000000000000u64,
    },
}

task 5, line 34:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 36:
//# view-object 3,0
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 38:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 40:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1976000, non_refundable_storage_fee: 0 }}

task 9, line 42:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 44:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: 5FUncVVyBTNY74CQf1Y2v7SxjjMjr437Xoo2aZJkS88u,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 46-51:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 53:
//# create-checkpoint
Checkpoint created: 11

task 13, line 55:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 57-62:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 64-69:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-iota-rpc-version": "2024.7.0-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 2024.7.0-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 71:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 73-76:
//# advance-epoch
Epoch advanced: 6

task 18, lines 78-93:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x28b61d9a309c5a88a18455d588c6ba42bdcd05d7bfca44fadb2fdff0190b14b3",
              "digest": "2uxZrz8XrLdjDaN5ToNn26umCL4yb5YN9AeRFAnzfvyE",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 95-150:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x28b61d9a309c5a88a18455d588c6ba42bdcd05d7bfca44fadb2fdff0190b14b3",
              "digest": "2uxZrz8XrLdjDaN5ToNn26umCL4yb5YN9AeRFAnzfvyE",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x26bf0f03edd09bb3f862e13cec014d17c26dd739d2563d9c704aa8d206301df2",
              "digest": "2sYWKex6yu3k1CXMYwnLkqYKhnGmnP3yP1dJLhR5Xkko",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x3442446f02377d1025b211e51564e4f1c9a46845ccad733beeb06180d3f66c31",
              "digest": "9UKK4yuneF6FvxgtNXLcb3fmaVKnwwEibPXRYaQRHRzj",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x3c88cad5799a8da0467b8456a7429a97e7c141cfcf25f02faf51aa8cb4840461",
              "digest": "Be8LdYznQGaiKJ1Zcp9nH4pKtUYRaXQVtq8kj9NZrHjJ",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x48c6a3b6b09076c9d9da63411aadfb10327fc8d2e7223dbf12fe843588b202df",
              "digest": "9DTNHygGtUHtpx2FLoF5gD2i1pMqqMyB63ima322HnYc",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x57cb8e1780b3c414a13397213f69198e6eb6f269333431ba7f16d7baeb79c25d",
              "digest": "2CDCVccBAm9xntXxNZY8PYsuLrNCRwzBv5srUwsGziFZ",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x823dd2709d95ec2034c4892191d8b3418487a75abdddd054679b994746561959",
              "digest": "5EGBgWa2meW9wqH6wxprz9awzt4kGra4EhR6FW2vvsq6",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x847c914d647e7387d7cea4db5ad8fefeffe66773635804a991dfd4385fab6a97",
              "digest": "3QSgX14R65FBTub7d1dwnExPhFNSSNrMS1FEfSQpRJR7",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x88cf6147a9c57ab642cd71d22c2e91577db6bf93d26e30dc55046e61da855253",
              "digest": "EXBNoySgRY88bqZz5X6dy41gsrHtHKobdFDaX2s7SZ5x",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x8cf840979473dc5fa9305e37aa467afaca8cac1fc403715eaa1a281a11a3807d",
              "digest": "13Egdk3JXG33jF26eKG1Es2dsEhX2g6yG7ZNdK3effAU",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xa79cc544021a721176cdc4497728ec35a5311b8ff0aa293a5d29c0d32cb56056",
              "digest": "nPWD3aqbQmz7e5voUkHzMQ7pi3NhHh7erKzTKPLffhh",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xac9c2e11aebecd35b4cb15802ca6ad5e64d320204149187ba646a16d07a4934d",
              "digest": "3zHhWmCGNWM9hYZ41PL7fUksLudgoFDexFeaC53uut3q",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xb21c0b03871456040643740e238d03bde38de240d7b17055f4670777a19f07b8",
              "digest": "8DWBQ73PBVbKXvWpD6BCG1vgHMbc4XS2Ra3hgzJAz5N9",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 152-168:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
    }
  }
}

task 21, lines 170-176:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 178:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 23, line 180:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 24, line 182:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 25, lines 184-189:
//# run-graphql
Response: {
  "data": {
    "serviceConfig": {
      "availableVersions": [
        "2024.7"
      ]
    }
  }
}
