processed 11 tasks

init:
C: object(0,0)

task 1 'create-checkpoint'. lines 9-9:
Checkpoint created: 1

task 2 'advance-epoch'. lines 11-11:
Epoch advanced: 0

task 3 'programmable'. lines 13-15:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 17-19:
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [95, 135, 174, 233, 197, 147, 52, 55, 236, 249, 148, 154, 21, 252, 46, 105, 210, 250, 18, 116, 95, 45, 151, 207, 146, 210, 63, 157, 136, 99, 111, 87, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 14789600,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 5 'create-checkpoint'. lines 20-20:
Checkpoint created: 3

task 6 'advance-epoch'. lines 22-24:
Epoch advanced: 1

task 7 'programmable'. lines 25-29:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 30-30:
Checkpoint created: 5

task 9 'advance-epoch'. lines 32-33:
Epoch advanced: 2

task 10 'run-graphql'. lines 34-62:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "totalStake": "3034010000000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        },
        "validatorCandidatesSize": 0,
        "inactivePoolsId": "0x7a410699534b7228fce55c67cbe982de1751beb87a10d8951518ec3e4305a36d"
      },
      "totalGasFees": "1000000",
      "totalStakeRewards": "767000000000000",
      "fundSize": "14789600",
      "fundInflow": "1976000",
      "fundOutflow": "988000",
      "netInflow": "988000",
      "transactionBlocks": {
        "nodes": [
          {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            },
            "digest": "832vtFgFDPCdQQHieuKsNHKha4tMdgkpBQrwapxDMPWX"
          },
          {
            "kind": {
              "__typename": "EndOfEpochTransaction"
            },
            "digest": "HA6PvtnNKdSJrXojWzBBL9x7W15YwSh3wWpvwNSsYAeQ"
          }
        ]
      }
    }
  }
}
