processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-32:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 34:
//# create-checkpoint
Checkpoint created: 1

task 3, line 36:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 38:
//# run Test::M1::create --args 1 @B --sender B
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 40:
//# run Test::M1::create --args 2 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 42:
//# run Test::M1::create --args 3 @B --sender B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 44:
//# run Test::M1::create --args 4 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 46:
//# create-checkpoint
Checkpoint created: 2

task 9, line 48:
//# run Test::M1::create --args 100 @B --sender B
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 50:
//# run Test::M1::create --args 101 @A --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11, line 52:
//# run Test::M1::create --args 102 @B --sender B
created: object(11,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12, line 54:
//# run Test::M1::create --args 103 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 13, line 56:
//# run Test::M1::create --args 104 @B --sender B
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 14, line 58:
//# create-checkpoint
Checkpoint created: 3

task 15, lines 60-82:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EqqWSPU9Xpov2yDutF8bhtMpkbqB66Ct3AN8sMJWBUCu",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "8yc9oAm3R4131ZyaFPmyUpzQR5gz42Bin7ADTqjvRnCx",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "digest": "5wW9eGhGKPoDfUxsiWHTgcxDBz34QD7Fc6cMiMEqwMW",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "digest": "D6AUvEYJVe6aZsxRn1CqcPLFbcuLKskfrSY1jMYNR2Ha",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
          "node": {
            "digest": "DvLhb1b8EgZnnqHeJewPu5wcySe1Emthar62n68G2JeA",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
          "node": {
            "digest": "96n3Rq5QnAGcXPHsom5kMHiWorsd28yAcjTpjKU2mDht",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
          "node": {
            "digest": "4JVs5UtEghNfT8MhBCxi5Dqc64sb2qM3gKynVrrDSnvM",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
          "node": {
            "digest": "85YmFDGF6qzNkXjeXwqfguzjopXQk4Yo6S7rizt5BXSH",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "FjEwv7uuizMyfXs2xHPRkTUHKhyAL7W9yGHGTBV7uwMW",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "4DpnvwQZvwxPUBVmBDntFc5ie5L2kA6W2GWU6NtG5dzm",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 16, lines 85-107:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0IjozLCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EqqWSPU9Xpov2yDutF8bhtMpkbqB66Ct3AN8sMJWBUCu",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 17, lines 109-131:
//# run-graphql --cursors {"c":4,"t":3,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0Ijo0LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0Ijo1LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "digest": "5wW9eGhGKPoDfUxsiWHTgcxDBz34QD7Fc6cMiMEqwMW",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 18, lines 133-159:
//# run-graphql --cursors {"c":4,"t":5,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0Ijo2LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0Ijo4LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0Ijo2LCJpIjpmYWxzZX0",
          "node": {
            "digest": "DvLhb1b8EgZnnqHeJewPu5wcySe1Emthar62n68G2JeA",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo4LCJpIjpmYWxzZX0",
          "node": {
            "digest": "4JVs5UtEghNfT8MhBCxi5Dqc64sb2qM3gKynVrrDSnvM",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 19, lines 161-183:
//# run-graphql --cursors {"c":4,"t":8,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjo0LCJ0Ijo5LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxMCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "FjEwv7uuizMyfXs2xHPRkTUHKhyAL7W9yGHGTBV7uwMW",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 20, lines 185-208:
//# run-graphql --cursors {"c":4,"t":10,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjo0LCJ0IjoxMSwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo0LCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": []
    }
  }
}

task 21, lines 210-233:
//# run-graphql --cursors {"c":4,"t":11,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": null,
        "endCursor": null
      },
      "edges": []
    }
  }
}
