warning[Lint W03001]: sub-optimal 'iota::coin::Coin' field type
   ┌─ tests/iota_mode/linter/coin_field.move:12:12
   │
12 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'iota::coin::Coin'
13 │         id: UID,
14 │         c: Coin<S1>,
   │         - Storing 'iota::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[allow(lint(coin_field))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W03001]: sub-optimal 'iota::coin::Coin' field type
   ┌─ tests/iota_mode/linter/coin_field.move:26:12
   │
26 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'iota::coin::Coin'
27 │         id: UID,
28 │         c: Balance<S1>,
   │         - Storing 'iota::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[allow(lint(coin_field))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

