warning[Lint W99008]: freezing potential capability
   ┌─ tests/iota_mode/linter/freezing_capability_false_positives.move:26:9
   │
26 │         transfer::public_freeze_object(w);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The type 'a::test_false_positives::NoCap' is potentially a capability based on its name
   │
   = Freezing a capability might lock out critical operations or otherwise open access to operations that otherwise should be restricted
   = This warning can be suppressed with '#[allow(lint(freezing_capability))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W99008]: freezing potential capability
   ┌─ tests/iota_mode/linter/freezing_capability_false_positives.move:30:9
   │
30 │         transfer::public_freeze_object(w);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The type 'a::test_false_positives::CapAndHat' is potentially a capability based on its name
   │
   = Freezing a capability might lock out critical operations or otherwise open access to operations that otherwise should be restricted
   = This warning can be suppressed with '#[allow(lint(freezing_capability))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

