processed 2 tasks

task 0, lines 5-27:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("PartialVMError with status UNKNOWN_VERIFICATION_ERROR with sub status 1 and message Invalid object creation in _::m::foo. Object created without a newly created UID. The UID must come directly from iota::object::new. Or for tests, it can come from iota::test_scenario::new_object"), command: Some(0) } }

task 1, lines 29-51:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4590400,  storage_rebate: 988000, non_refundable_storage_fee: 0
