processed 2 tasks

task 0, lines 7-29:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4970400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1, lines 31-60:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5168000,  storage_rebate: 988000, non_refundable_storage_fee: 0
