processed 1 task

task 0 'publish'. lines 5-35:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("PartialVMError with status UNKNOWN_VERIFICATION_ERROR with sub status 1 and message Invalid object creation in _::m::new. Object created without a newly created UID. The UID must come directly from iota::object::new. Or for tests, it can come from iota::test_scenario::new_object"), command: Some(0) } }
