processed 34 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 7-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5791200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# create-checkpoint
Checkpoint created: 1

task 3, line 32:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::create --args 1 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 36:
//# run Test::M1::create --args 2 @B --sender B
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6, line 38:
//# run Test::M1::create --args 3 @B --sender B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 40:
//# run Test::M1::create --args 4 @B --sender B
created: object(7,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 42:
//# create-checkpoint
Checkpoint created: 2

task 9, line 44:
//# run Test::M1::create --args 100 @B --sender B
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 46:
//# run Test::M1::create --args 101 @B --sender B
created: object(10,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 11, line 48:
//# run Test::M1::create --args 102 @B --sender B
created: object(11,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 50:
//# run Test::M1::create --args 103 @B --sender B
created: object(12,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 52:
//# run Test::M1::create --args 104 @B --sender B
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 14, line 54:
//# create-checkpoint
Checkpoint created: 3

task 15, line 56:
//# run Test::M1::create --args 100 @B --sender B
created: object(15,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 16, line 58:
//# run Test::M1::create --args 101 @B --sender B
created: object(16,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 17, line 60:
//# run Test::M1::create --args 102 @B --sender B
created: object(17,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 18, line 62:
//# run Test::M1::create --args 103 @B --sender B
created: object(18,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 19, line 64:
//# run Test::M1::create --args 104 @B --sender B
created: object(19,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 20, line 66:
//# create-checkpoint
Checkpoint created: 4

task 21, line 68:
//# run Test::M1::create --args 200 @A --sender A
created: object(21,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 22, line 70:
//# run Test::M1::create --args 201 @B --sender A
created: object(22,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 23, line 72:
//# run Test::M1::create --args 202 @B --sender B
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 24, line 74:
//# run Test::M1::create --args 203 @B --sender B
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 25, line 76:
//# run Test::M1::create --args 204 @A --sender A
created: object(25,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 26, line 78:
//# create-checkpoint
Checkpoint created: 5

task 27, lines 80-101:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EnWpFFgRUBm3LbuTfjJ6oF3RXVcnzpth6L9nn4Q18RNk",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "3fmkhmMgShCMM9HWgLR13ovdiBTy2Zoe6MgVfy8Wi8nt",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjoxNywiaSI6ZmFsc2V9",
          "node": {
            "digest": "8NagxHteFzUuAvwvzjFAorD1dNfqfKnqwwviDaAt8j1z",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjoxOCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "Ep8Q9KBacxFkYEvaxsm7CJAUqQ85WUi5z6oZudBEyFSP",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "636Q9XJw6aZQ4RGEnej49Z99Nn21GgPBQDmCGGhNQ2Rm",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 28, lines 104-130:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjo1LCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EnWpFFgRUBm3LbuTfjJ6oF3RXVcnzpth6L9nn4Q18RNk",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 29, lines 132-156:
//# run-graphql --cursors {"c":7,"t":2,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjozLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo3LCJ0Ijo3LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "3fmkhmMgShCMM9HWgLR13ovdiBTy2Zoe6MgVfy8Wi8nt",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 30, lines 158-181:
//# run-graphql --cursors {"c":7,"t":7,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0Ijo4LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo3LCJ0IjoxMiwiaSI6dHJ1ZX0"
      },
      "edges": []
    }
  }
}

task 31, lines 183-206:
//# run-graphql --cursors {"c":7,"t":12,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjoxMywiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo3LCJ0IjoxNywiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjoxNywiaSI6ZmFsc2V9",
          "node": {
            "digest": "8NagxHteFzUuAvwvzjFAorD1dNfqfKnqwwviDaAt8j1z",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 32, lines 208-233:
//# run-graphql --cursors {"c":7,"t":17,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjoxOCwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo3LCJ0IjoxOCwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjoxOCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "Ep8Q9KBacxFkYEvaxsm7CJAUqQ85WUi5z6oZudBEyFSP",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 33, lines 235-259:
//# run-graphql --cursors {"c":7,"t":18,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjo3LCJ0IjoxOSwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo3LCJ0IjoyMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjoyMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "636Q9XJw6aZQ4RGEnej49Z99Nn21GgPBQDmCGGhNQ2Rm",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}
