processed 34 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 7-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# create-checkpoint
Checkpoint created: 1

task 3, line 32:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 34:
//# run Test::M1::create --args 1 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 36:
//# run Test::M1::create --args 2 @B --sender B
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6, line 38:
//# run Test::M1::create --args 3 @B --sender B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 40:
//# run Test::M1::create --args 4 @B --sender B
created: object(7,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 42:
//# create-checkpoint
Checkpoint created: 2

task 9, line 44:
//# run Test::M1::create --args 100 @B --sender B
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 46:
//# run Test::M1::create --args 101 @B --sender B
created: object(10,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11, line 48:
//# run Test::M1::create --args 102 @B --sender B
created: object(11,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12, line 50:
//# run Test::M1::create --args 103 @B --sender B
created: object(12,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 13, line 52:
//# run Test::M1::create --args 104 @B --sender B
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 14, line 54:
//# create-checkpoint
Checkpoint created: 3

task 15, line 56:
//# run Test::M1::create --args 100 @B --sender B
created: object(15,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16, line 58:
//# run Test::M1::create --args 101 @B --sender B
created: object(16,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 17, line 60:
//# run Test::M1::create --args 102 @B --sender B
created: object(17,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 18, line 62:
//# run Test::M1::create --args 103 @B --sender B
created: object(18,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 19, line 64:
//# run Test::M1::create --args 104 @B --sender B
created: object(19,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 20, line 66:
//# create-checkpoint
Checkpoint created: 4

task 21, line 68:
//# run Test::M1::create --args 200 @A --sender A
created: object(21,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 22, line 70:
//# run Test::M1::create --args 201 @B --sender B
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 23, line 72:
//# run Test::M1::create --args 202 @B --sender B
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 24, line 74:
//# run Test::M1::create --args 203 @B --sender B
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 25, line 76:
//# run Test::M1::create --args 204 @A --sender A
created: object(25,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 26, line 78:
//# create-checkpoint
Checkpoint created: 5

task 27, lines 80-101:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjo1LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "mwCyozmxsNvmGdRkPQFGnz1FWbSsbi1Y5nAwwoCEvYj",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "HXhwQy2Cd8biC8fe111TFSYLKYYZoi5cWAFb7n4Epfdr",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjoxNywiaSI6ZmFsc2V9",
          "node": {
            "digest": "4w9544BVTSDYvvDibJmDsTJanU8zK8SpVMDzEzCMyv5W",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "9zEYeCv3r6s91Kg4YuD9PdNNNagSbQcCWHVFVa7xddMx",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 28, lines 104-126:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9",
        "endCursor": "eyJjIjo1LCJ0IjoyMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo1LCJ0IjoyMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "9zEYeCv3r6s91Kg4YuD9PdNNNagSbQcCWHVFVa7xddMx",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 29, lines 128-153:
//# run-graphql --cursors {"c":7,"t":21,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjoxNiwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo3LCJ0IjoyMCwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjoxNywiaSI6ZmFsc2V9",
          "node": {
            "digest": "4w9544BVTSDYvvDibJmDsTJanU8zK8SpVMDzEzCMyv5W",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 5
              }
            }
          }
        }
      ]
    }
  }
}

task 30, lines 155-178:
//# run-graphql --cursors {"c":7,"t":16,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjoxMSwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjo3LCJ0IjoxNSwiaSI6dHJ1ZX0"
      },
      "edges": []
    }
  }
}

task 31, lines 180-202:
//# run-graphql --cursors {"c":7,"t":11,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0Ijo2LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo3LCJ0IjoxMCwiaSI6dHJ1ZX0"
      },
      "edges": []
    }
  }
}

task 32, lines 204-228:
//# run-graphql --cursors {"c":7,"t":6,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjozLCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjo3LCJ0Ijo1LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "HXhwQy2Cd8biC8fe111TFSYLKYYZoi5cWAFb7n4Epfdr",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 33, lines 230-252:
//# run-graphql --cursors {"c":7,"t":3,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjo3LCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo3LCJ0IjoyLCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo3LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "mwCyozmxsNvmGdRkPQFGnz1FWbSsbi1Y5nAwwoCEvYj",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}
