processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 15-82:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 11263200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 84:
//# run Test::M1::create --sender A --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 86:
//# run Test::M1::emit_a --sender A --args object(2,0) 0
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 4, line 88:
//# run Test::M1::emit_b --sender A --args object(2,0) 1
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("Object"), type_params: [] })] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5, line 90:
//# run Test::M2::create --sender A --args 2 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 92:
//# run Test::M2::emit_a --sender A --args object(5,0) 2
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 7, line 94:
//# run Test::M2::emit_b --sender A --args object(5,0) 3
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M2"), name: Identifier("Object"), type_params: [] })] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 8, line 96:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 98-118:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 10, lines 120-140:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M2::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 11, lines 142-162:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 12, lines 164-184:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 13, lines 186-206:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::EventB<0x09aacb263274f968c844964d04220221707a91acd5f340c2504f6ee5873c1154::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 14, lines 208-228:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 15, lines 230-250:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 16, lines 252-272:
//# run-graphql
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}
