processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 15-82:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 11263200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 84-84:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 86-86:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 4 'run'. lines 88-88:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("Object"), type_params: [] })] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5 'run'. lines 90-90:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'run'. lines 92-92:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 7 'run'. lines 94-94:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M2"), name: Identifier("Object"), type_params: [] })] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 96-96:
Checkpoint created: 1

task 9 'run-graphql'. lines 98-118:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 120-140:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M2::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 142-162:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 164-184:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 186-206:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::EventB<0x1948409dca01736e469ca3b66180b9c5f0e9cb0c57d8b2803a8ebab660332be1::M1::Object>"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 208-228:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 15 'run-graphql'. lines 230-250:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 16 'run-graphql'. lines 252-272:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}
