processed 9 tasks

init:
A: object(0,0)

task 1, lines 7-23:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4818400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 25:
//# run Test::M1::emit_1 --sender A --args 0
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 27:
//# run Test::M1::emit_2 --sender A --args 1
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 29:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 31-55:
//# run-graphql
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 6, lines 57-81:
//# run-graphql --cursors {"tx":2,"e":0,"c":1}
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 7, lines 83-107:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 8, lines 109-133:
//# run-graphql
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x1f57915ce0ae42aa219f3cc99dc4c285414b0df9ffdac98c0eb944c64c1cd4ad::M1::EventA"
            },
            "sender": {
              "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}
