processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 4795600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::no_emit --sender A --args 0
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 31:
//# run Test::M1::emit_2 --sender A --args 2
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::emit_2 --sender B --args 4
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [4, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [5, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-44:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "BK3Kekkcdo6pkxFkib2gWaw7ozbTd1P9GFJf1Gdkk4Tw"
        },
        {
          "digest": "GS1LUR1UjD8peuQQh48Nwz8typs5zgKKc98nKMruXyWM"
        },
        {
          "digest": "69jE7Qho2T86X2SV89rF1esL9kM62eiTnuKADDmtThHT"
        },
        {
          "digest": "5pbswh7EYi78wk6TQSWZ1v2vPrxnmHLbzGEK7UZ2wKJs"
        },
        {
          "digest": "sywyCLK4TcmA9BVQtTjoqUdBAErTELaMhDL5bt7ALcb"
        }
      ]
    }
  }
}

task 7, lines 46-58:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 8, lines 60-73:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 9, lines 75-90:
//# run-graphql --cursors {"tx":1,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 10, lines 93-105:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 11, lines 107-119:
//# run-graphql --cursors {"tx":4,"e":0,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 12, lines 122-134:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 13, lines 136-149:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 14, lines 151-166:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 15, lines 169-181:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 16, lines 183-195:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 17, lines 197-210:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 18, lines 212-225:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 19, lines 227-240:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 20, lines 242-255:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}
