processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 4795600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::no_emit --sender A --args 0
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 31:
//# run Test::M1::emit_2 --sender A --args 2
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::emit_2 --sender B --args 4
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [4, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [5, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-44:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "J2ipHUWhTfsoqMAG5AfXSsKG73c3oSqsxwQns9WP7WKv"
        },
        {
          "digest": "F8z11KNSYyUsBD9ggqQkqm4AgDGgVvfzDntJMW8Z5a3j"
        },
        {
          "digest": "8h2qDXpVYkN95m5SupmMWFJfHw2x9GTESNsw5nnL9j4N"
        },
        {
          "digest": "3UpQ5k6ubWDEsCGeh39ZD7wRk8mx7LEHM7bxVC1kL1pc"
        },
        {
          "digest": "BLYdLfV5uMQrev9TDtkKbcDoz74NJ76yjCyEBnhgWueE"
        }
      ]
    }
  }
}

task 7, lines 46-58:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "3"
            }
          }
        }
      ]
    }
  }
}

task 8, lines 60-73:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 9, lines 75-90:
//# run-graphql --cursors {"tx":1,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 10, lines 93-105:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 11, lines 107-119:
//# run-graphql --cursors {"tx":4,"e":0,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 12, lines 122-134:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "3"
            }
          }
        }
      ]
    }
  }
}

task 13, lines 136-149:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        }
      ]
    }
  }
}

task 14, lines 151-166:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 15, lines 169-181:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 183-195:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        }
      ]
    }
  }
}

task 17, lines 197-210:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "3"
            }
          }
        }
      ]
    }
  }
}

task 18, lines 212-225:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 19, lines 227-240:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 20, lines 242-255:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}
