processed 6 tasks

task 1, lines 7-34:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 7174400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3397200,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 38-41:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::send_back(Input(0), Input(1))
// Include the receiving argument, but don't use it at the PTB level
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3397200,  storage_rebate: 3397200, non_refundable_storage_fee: 0

task 4, lines 42-46:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::nop(Input(0))
// Include the receiving argument, but don't use it at the Move level. The
// receiving object should not be mutated by this.
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2188800,  storage_rebate: 2188800, non_refundable_storage_fee: 0

task 5, lines 47-48:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::nop_with_receiver(Input(0), Input(1))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 2188800,  storage_rebate: 2188800, non_refundable_storage_fee: 0
