processed 9 tasks

task 1, lines 7-32:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6916000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 34:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 36:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 38:
//# view-object 2,1
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5, line 40:
//# run tto::M1::receiver --args object(2,0) receiving(2,1)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 3420000, non_refundable_storage_fee: 0

task 6, line 42:
//# view-object 2,0
Owner: Shared( 3 )
Version: 4
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 7, line 44:
//# view-object 2,1
Owner: Account Address ( _ )
Version: 4
Contents: tto::M1::B {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 8, line 46:
//# run tto::M1::receiver --args object(2,0) receiving(2,1)@3
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3) at command Some(0)
