processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-31:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5274400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 33-35:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 37-37:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 4 'programmable'. lines 39-40:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 5 'view-object'. lines 42-45:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 112u64}

task 6 'programmable'. lines 47-48:
mutated: object(_), object(2,0)
gas summary: computation_cost: 500000, storage_cost: 2257200,  storage_rebate: 1269200, non_refundable_storage_fee: 0

task 7 'programmable'. lines 50-54:
mutated: object(_), object(2,0)
gas summary: computation_cost: 500000, storage_cost: 2257200,  storage_rebate: 1269200, non_refundable_storage_fee: 0

task 8 'programmable'. lines 56-57:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 2, instruction: 8, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 2, instruction: 8, function_name: Some("check") }, 0) in command 0

task 9 'programmable'. lines 59-60:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 2, instruction: 8, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 2, instruction: 8, function_name: Some("check") }, 0) in command 0
