processed 6 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-27:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5821600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 29-29:
created: 200
mutated: 1
gas summary: computation_cost: 1000000, storage_cost: 270028000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 31-31:
created: 2000
mutated: 1
gas summary: computation_cost: 7000000, storage_cost: 2691388000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'run'. lines 33-33:
Error: Transaction Effects Status: Move Primitive Runtime Error. Location: iota::dynamic_field::has_child_object (function index 14) at offset 0. Arithmetic error, stack overflow, max value depth, etc.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 14, instruction: 0, function_name: Some("has_child_object") }))), source: Some(VMError { major_status: MEMORY_LIMIT_EXCEEDED, sub_status: Some(5), message: Some("Object runtime cached objects limit (1000 entries) reached"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("dynamic_field") }), indices: [], offsets: [(FunctionDefinitionIndex(14), 0)] }), command: Some(0) } }

task 5 'run'. lines 35-35:
Error: Transaction Effects Status: Move Primitive Runtime Error. Location: iota::dynamic_field::has_child_object (function index 14) at offset 0. Arithmetic error, stack overflow, max value depth, etc.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: iota, name: Identifier("dynamic_field") }, function: 14, instruction: 0, function_name: Some("has_child_object") }))), source: Some(VMError { major_status: MEMORY_LIMIT_EXCEEDED, sub_status: Some(5), message: Some("Object runtime cached objects limit (1000 entries) reached"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("dynamic_field") }), indices: [], offsets: [(FunctionDefinitionIndex(14), 0)] }), command: Some(0) } }
