processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-13:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3906400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 15-17:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call functions in iota::event"), command: Some(1) } }

task 3 'programmable'. lines 19-22:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call functions in iota::event"), command: Some(1) } }

task 4 'programmable'. lines 24-27:
Error: Transaction Effects Status: Function Not Found.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: FunctionNotFound, source: Some("Could not resolve function 'does_not_exist' in module iota::event"), command: Some(1) } }
