processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-21:
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10617200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 23-25:
created: object(2,0)
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 2690400, non_refundable_storage_fee: 0

task 3 'programmable'. lines 27-28:
Error: Transaction Effects Status: Insufficient coin balance for operation.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InsufficientCoinBalance, source: Some("balance: 1 required: 2"), command: Some(0) } }

task 4 'programmable'. lines 30-31:
Error: Transaction Effects Status: Insufficient coin balance for operation.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InsufficientCoinBalance, source: Some("balance: 299989985060400 required: 18446744073709551615"), command: Some(0) } }
