processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-29:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5760800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 31-32:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'programmable'. lines 34-35:
Error: Transaction Effects Status: Invalid command argument at 1. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidValueUsage } at command Some(0)

task 4 'programmable'. lines 37-38:
Error: Transaction Effects Status: Invalid command argument at 1. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidValueUsage } at command Some(0)

task 5 'programmable'. lines 40-41:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'programmable'. lines 43-44:
Error: Transaction Effects Status: Invalid command argument at 1. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidValueUsage } at command Some(0)

task 7 'programmable'. lines 46-47:
Error: Transaction Effects Status: Invalid command argument at 1. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Debug of error: CommandArgumentError { arg_idx: 1, kind: InvalidValueUsage } at command Some(0)
