processed 3 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'programmable'. lines 9-10:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 12-12:
Owner: Account Address ( B )
Version: 2
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(0,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 299999998012000u64}}
