processed 9 tasks

init:
A: object(0,0)

task 1, lines 9-25:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4058400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 26-27:
//# programmable --sender A
//> test::m1::t1<iota::coin::Coin<iota::iota::IOTA>>(Gas)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 29-30:
//# programmable --sender A
//> test::m1::t2<iota::coin::Coin<iota::iota::IOTA>>(Gas)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, lines 32-33:
//# programmable --sender A
//> test::m1::t2<iota::coin::Coin<iota::iota::IOTA>>(Gas)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 35-36:
//# programmable --sender A
//> test::m1::t4<iota::coin::Coin<iota::iota::IOTA>>(Gas)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, lines 38-39:
//# programmable --sender A
//> test::m1::t5<iota::coin::Coin<iota::iota::IOTA>>(Gas)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, lines 41-44:
//# programmable --sender A
//> test::m1::t6<iota::coin::Coin<iota::iota::IOTA>>(Gas)
// can pass to merge and split
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, lines 45-47:
//# programmable --sender A --inputs 10  --gas-budget 10000000000
//> 0: SplitCoins(Gas, [Input(0)]);
//> MergeCoins(Gas, [Result(0)])
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0
