processed 8 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-45:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 7159200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 46-53:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 54-61:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'programmable'. lines 62-66:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'programmable'. lines 67-69:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'view-object'. lines 71-71:
Owner: Account Address ( A )
Version: 5
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,0)}}, value: 112u64}

task 7 'programmable'. lines 73-79:
mutated: object(0,0)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2280000, non_refundable_storage_fee: 0
