processed 3 tasks

init:
A: object(0,0)

task 1, lines 9-20:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 4658800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-27:
//# programmable
//> 0: test::m1::potato();
//> 1: test::m1::pass(Result(0));
//> test::m1::imm(Result(1));
//> test::m1::mut_(Result(1));
//> test::m1::otatop(Result(1));
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0
