processed 18 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-16:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4666400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 18-19:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 3 'programmable'. lines 20-21:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 4 'programmable'. lines 23-24:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 5 'programmable'. lines 25-26:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 2
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 2 } }, source: None, command: Some(0) } }

task 6 'programmable'. lines 28-29:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 7 'programmable'. lines 30-31:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 8 'programmable'. lines 33-34:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 9 'programmable'. lines 35-36:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 10 'programmable'. lines 38-39:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 11 'programmable'. lines 40-41:
Error: Transaction Effects Status: Invalid command argument at 1. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 12 'programmable'. lines 43-44:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 13 'programmable'. lines 45-46:
Error: Transaction Effects Status: Invalid command argument at 1. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 14 'programmable'. lines 48-49:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 15 'programmable'. lines 50-51:
Error: Transaction Effects Status: Invalid command argument at 1. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }

task 16 'programmable'. lines 53-54:
Error: Transaction Effects Status: Invalid command argument at 0. Out of bounds access to input or result vector 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: IndexOutOfBounds { idx: 0 } }, source: None, command: Some(0) } }

task 17 'programmable'. lines 55-56:
Error: Transaction Effects Status: Invalid command argument at 1. Out of bounds access to input or result vector 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: IndexOutOfBounds { idx: 1 } }, source: None, command: Some(0) } }
