processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-13:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4628400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 15-17:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2219200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 19-19:
Owner: Account Address ( A )
Version: 2
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'programmable'. lines 21-23:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2219200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'view-object'. lines 25-25:
Owner: Shared
Version: 3
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(4,0)}}}

task 6 'programmable'. lines 27-29:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2219200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 31-31:
Owner: Immutable
Version: 4
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}}
