processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-27:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 29-33:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4636000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 35-39:
mutated: object(0,0)
deleted: object(2,0), object(2,1), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 4636000, non_refundable_storage_fee: 0

task 4 'programmable'. lines 41-44:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0
