processed 11 tasks

init:
A: object(0,0)

task 1, lines 9-18:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5228800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 20-22:
//# programmable --sender A --inputs @A
//> 0: test::m1::pub();
//> iota::transfer::transfer<test::m1::Pub>(Result(0), Input(0));
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::transfer. Use the public variant instead, iota::transfer::public_transfer"), command: Some(1) } }

task 3, lines 24-26:
//# programmable
//> 0: test::m1::pub();
//> iota::transfer::share_object<test::m1::Pub>(Result(0));
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::share_object. Use the public variant instead, iota::transfer::public_share_object"), command: Some(1) } }

task 4, lines 28-33:
//# programmable
//> 0: test::m1::pub();
//> iota::transfer::freeze_object<test::m1::Pub>(Result(0));
// Does not have store, cannot be used with internal variants
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::freeze_object. Use the public variant instead, iota::transfer::public_freeze_object"), command: Some(1) } }

task 5, lines 35-37:
//# programmable --sender A --inputs @A
//> 0: test::m1::priv();
//> iota::transfer::transfer<test::m1::Priv>(Result(0), Input(0));
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::transfer. Use the public variant instead, iota::transfer::public_transfer"), command: Some(1) } }

task 6, lines 39-41:
//# programmable
//> 0: test::m1::priv();
//> iota::transfer::share_object<test::m1::Priv>(Result(0));
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::share_object. Use the public variant instead, iota::transfer::public_share_object"), command: Some(1) } }

task 7, lines 43-48:
//# programmable
//> 0: test::m1::priv();
//> iota::transfer::freeze_object<test::m1::Priv>(Result(0));
// Does not have store, cannot be used with public variants
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::freeze_object. Use the public variant instead, iota::transfer::public_freeze_object"), command: Some(1) } }

task 8, lines 50-52:
//# programmable --sender A --inputs @A
//> 0: test::m1::priv();
//> iota::transfer::public_transfer<test::m1::Priv>(Result(0), Input(0));
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("transfer") }), indices: [], offsets: [] }), command: Some(1) } }

task 9, lines 54-56:
//# programmable
//> 0: test::m1::priv();
//> iota::transfer::public_share_object<test::m1::Priv>(Result(0));
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("transfer") }), indices: [], offsets: [] }), command: Some(1) } }

task 10, lines 58-60:
//# programmable
//> 0: test::m1::priv();
//> iota::transfer::public_freeze_object<test::m1::Priv>(Result(0));
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("transfer") }), indices: [], offsets: [] }), command: Some(1) } }
