processed 3 tasks

init:
A: object(0,0)

task 1, lines 10-14:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 3541600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-18:
//# programmable --inputs 0
//> test::m1::clean(Input(0));
//> test::m1::priv(Input(0));
mutated: object(0,1)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0
