processed 20 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-25:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5418800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 27-31:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 32-32:
created: object(3,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 4 'view-object'. lines 34-36:
Owner: Account Address ( A )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 1000u64}}

task 5 'programmable'. lines 37-39:
created: object(5,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 6 'view-object'. lines 41-41:
Owner: Account Address ( A )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 900u64}}

task 7 'view-object'. lines 43-46:
Owner: Account Address ( B )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 8 'programmable'. lines 47-49:
created: object(8,0), object(8,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3952000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 9 'view-object'. lines 51-51:
Owner: Account Address ( A )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 700u64}}

task 10 'view-object'. lines 53-53:
Owner: Account Address ( B )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 11 'view-object'. lines 55-57:
Owner: Account Address ( B )
Version: 5
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,1)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 12 'programmable'. lines 58-61:
created: object(12,0), object(12,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3952000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 13 'view-object'. lines 63-63:
Owner: Account Address ( A )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 500u64}}

task 14 'view-object'. lines 65-65:
Owner: Account Address ( B )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(12,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 15 'view-object'. lines 67-70:
Owner: Account Address ( B )
Version: 6
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(12,1)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 16 'programmable'. lines 71-75:
created: object(16,0), object(16,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3952000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 17 'view-object'. lines 77-77:
Owner: Account Address ( A )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 300u64}}

task 18 'view-object'. lines 79-79:
Owner: Account Address ( B )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(16,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 19 'view-object'. lines 81-81:
Owner: Account Address ( B )
Version: 7
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(16,1)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}
