processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-33:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6004000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 34-36:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 38-40:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(0,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 299999996720000u64}}

task 4 'programmable'. lines 41-44:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'view-object'. lines 46-48:
Owner: Account Address ( _ )
Version: 3
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(4,0)}}, value: 112u64}

task 6 'programmable'. lines 49-54:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 56-58:
Owner: Account Address ( B )
Version: 4
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}, value: 112u64}

task 8 'programmable'. lines 59-66:
created: object(8,0), object(8,1), object(8,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5388400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9 'view-object'. lines 68-68:
Owner: Account Address ( B )
Version: 5
Contents: test::m1::Cup<iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,0)}}}

task 10 'view-object'. lines 70-70:
Owner: Account Address ( B )
Version: 5
Contents: test::m1::Cup<test::m1::Pub> {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,1)}}}

task 11 'view-object'. lines 72-72:
Owner: Account Address ( B )
Version: 5
Contents: test::m1::Pub {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,2)}}, value: 112u64}
