name: Detect Changes in Turbo Workspace
description: Run e2e tests with specified branch

inputs:
  ref:
    description: "The branch to checkout and run e2e tests on"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      with:
        ref: ${{ inputs.ref }}
    # Disabled for now as it makes test runs take longer
    # - uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

    # TODO: we don't upload any releases to S3 yet
    # - name: Check s3 if binaries have been uploaded already
    #   continue-on-error: true
    #   id: check_s3
    #   run: |
    #     echo "Checking if s3 binaries have been built for ${{ github.sha }}"
    #     echo "s3_file_exist=$(curl -Is https://iota-releases.s3.us-east-1.amazonaws.com/${{ github.sha }}/debug/iota-test-validator | head -n 1 | grep '200 OK')" >> $GITHUB_ENV
    #   shell: bash

    - name: cargo build
      if: env.s3_file_exist == '' # if empty, we have not built and uploaded this binary to s3 yet
      run: |
        cargo build --bin iota-test-validator --bin iota
      shell: bash

    # TODO: we don't upload any releases to S3 yet
    # - name: Download from S3
    #   if: env.s3_file_exist != '' # only download if the s3 file exists
    #   working-directory: ./target/debug
    #   run: |
    #     mkdir -p $PWD/target/debug
    #     wget -O target/debug/iota-test-validator https://iota-releases.s3.us-east-1.amazonaws.com/${{ github.sha }}/debug/iota-test-validator
    #     chmod +x $PWD/target/debug/iota-test-validator
    #     wget -O target/debug/iota-test-validator https://iota-releases.s3.us-east-1.amazonaws.com/${{ github.sha }}/debug/iota
    #     chmod +x $PWD/target/debug/iota
    #   shell: bash

    # checkout current branch
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
      with:
        clean: false

    - name: Install Nodejs
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
      with:
        node-version: "18"
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Build explorer
      run: pnpm turbo --filter=iota-explorer build
      shell: bash
    - name: Install Playwright Browsers
      run: pnpm --filter iota-explorer playwright install --with-deps chromium
      shell: bash

    - name: Set env
      run: |
        echo "E2E_RUN_LOCAL_NET_CMD=(RUST_LOG=\"consensus=off\" $(echo $PWD/target/debug/iota-test-validator) --with-indexer --pg-port 5432 --pg-db-name iota_indexer_v2 --graphql-host 127.0.0.1 --graphql-port 9125)" >> $GITHUB_ENV
        echo "VITE_IOTA_BIN=$PWD/target/debug/iota" >> $GITHUB_ENV
      shell: bash

    - name: Run TS SDK e2e tests
      run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter @iota/iota.js --filter @iota/graphql-transport test:e2e'
      shell: bash

    - name: Run Explorer e2e tests
      run: pnpm --filter iota-explorer playwright test
      shell: bash

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-explorer
        path: apps/explorer/playwright-report/
        retention-days: 30
