processed 14 tasks

init:
P1: object(0,0), P2: object(0,1)

task 1, lines 9-54:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 7432800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 56-58:
//# programmable --sender P1 --inputs @P1
//> 0: test::m::a();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 60-61:
//# programmable --sender P1 --inputs object(2,0)
//> test::m::nop();
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 4, lines 63-64:
//# programmable --sender P1 --inputs object(2,0)
//> test::m::nop();
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 5, lines 66-69:
//# view-object 2,0
Owner: Account Address ( P1 )
Version: 4
Contents: test::m::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 6, lines 71-73:
//# programmable --sender P2 --inputs @P2
//> 0: test::m::b();
//> TransferObjects([Result(0)], Input(0))
created: object(6,0), object(6,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3663200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7, line 75:
//# view-object 6,0
Owner: Object ID: ( fake(6,1) )
Version: 2
Contents: iota::dynamic_field::Field<u64, u64> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(6,0),
        },
    },
    name: 0u64,
    value: 0u64,
}

task 8, lines 77-78:
//# programmable --sender P2 --inputs object(6,1)
//> 0: test::m::bump(Input(0));
mutated: object(0,1), object(6,0), object(6,1)
gas summary: computation_cost: 1000000, storage_cost: 3663200,  storage_rebate: 3663200, non_refundable_storage_fee: 0

task 9, lines 80-84:
//# view-object 6,0
Owner: Object ID: ( fake(6,1) )
Version: 3
Contents: iota::dynamic_field::Field<u64, u64> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(6,0),
        },
    },
    name: 0u64,
    value: 1u64,
}

task 10, lines 86-91:
//# programmable --sender P2 --inputs object(2,0)@4 object(6,1)@2 0 --dev-inspect
//> 0: test::m::append(Input(0), Input(1));
//> 1: test::m::check(Input(0), Input(2));
// checking that with version 3 we get the other value, then flip them to ensure
// they abort
created: object(10,0)
mutated: object(_), object(2,0)
wrapped: object(6,1)
gas summary: computation_cost: 500000, storage_cost: 4126800,  storage_rebate: 2416800, non_refundable_storage_fee: 0

task 11, lines 93-97:
//# programmable --sender P2 --inputs object(2,0)@4 object(6,1)@3 1 --dev-inspect
//> 0: test::m::append(Input(0), Input(1));
//> 1: test::m::check(Input(0), Input(2));
// @2 with value 1 aborts
created: object(10,0)
mutated: object(_), object(2,0)
wrapped: object(6,1)
gas summary: computation_cost: 500000, storage_cost: 4126800,  storage_rebate: 2416800, non_refundable_storage_fee: 0

task 12, lines 99-103:
//# programmable --sender P2 --inputs object(2,0)@4 object(6,1)@2 1 --dev-inspect
//> 0: test::m::append(Input(0), Input(1));
//> 1: test::m::check(Input(0), Input(2));
// @3 with value 0 aborts
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1

task 13, lines 105-107:
//# programmable --sender P2 --inputs object(2,0)@4 object(6,1)@3 0 --dev-inspect
//> 0: test::m::append(Input(0), Input(1));
//> 1: test::m::check(Input(0), Input(2));
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
