processed 29 tasks

init:
A: object(0,0)

task 1, line 9:
//# advance-epoch
Epoch advanced: 0

task 2, line 11:
//# create-checkpoint
Checkpoint created: 2

task 3, lines 13-38:
//# publish --sender A --gas-budget 9999999999
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 5912800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 40:
//# run P0::m::new --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, line 42:
//# run P0::m::new --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 44:
//# run P0::m::new --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 46:
//# run P0::m::new --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 48:
//# create-checkpoint
Checkpoint created: 3

task 9, line 50:
//# advance-epoch
Epoch advanced: 1

task 10, lines 52-63:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        }
      }
    }
  }
}

task 11, line 65:
//# run P0::m::new --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 67:
//# run P0::m::new --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 69:
//# run P0::m::new --sender A
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 14, line 71:
//# run P0::m::new --sender A
created: object(14,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 15, line 73:
//# run P0::m::new --sender A
created: object(15,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 16, line 75:
//# run P0::m::new --sender A
created: object(16,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 17, line 77:
//# run P0::m::new --sender A
created: object(17,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 18, line 79:
//# run P0::m::new --sender A
created: object(18,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 19, line 81:
//# run P0::m::new --sender A
created: object(19,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 20, line 83:
//# run P0::m::new --sender A
created: object(20,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 21, line 85:
//# run P0::m::new --sender A
created: object(21,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 22, line 87:
//# run P0::m::new --sender A
created: object(22,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 23, line 89:
//# run P0::m::new --sender A
created: object(23,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 24, line 91:
//# run P0::m::new --sender A
created: object(24,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 25, line 93:
//# run P0::m::new --sender A
created: object(25,0)
mutated: object(0,0)
gas summary: computation_cost: 1441000000, computation_cost_burned: 1441000000, storage_cost: 1932254400,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 26, line 95:
//# create-checkpoint
Checkpoint created: 5

task 27, lines 97-99:
//# advance-epoch
Epoch advanced: 2

task 28, lines 101-117:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0",
              "reportRecords": {
                "nodes": []
              }
            }
          ]
        }
      }
    }
  }
}
