processed 5 tasks

task 1, lines 7-29:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
      "sequenceNumber": 0
    }
  }
}

task 2, line 31:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# create-checkpoint
Checkpoint created: 2

task 4, lines 37-59:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "6SSpR1JWujKRTEB844us1vSSxjpD3RADCZ6HujXWx9a1",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "Ap4ddWHXeYVMSMcf8cQT9j7WUM1rGKw7rG3Q8rpsuaUd",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "6SSpR1JWujKRTEB844us1vSSxjpD3RADCZ6HujXWx9a1",
      "sequenceNumber": 2
    }
  }
}
