processed 5 tasks

task 1, lines 7-29:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
      "sequenceNumber": 0
    }
  }
}

task 2, line 31:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# create-checkpoint
Checkpoint created: 2

task 4, lines 37-59:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "7AeuzC9bvgWTqyx8DHTEmd6946NkTFyzq52kbERGSuP6",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "12SiJP1KTaGDQ5gYnZYPAuVuh6hmYq9z5FFYskDbYWBs",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "7AeuzC9bvgWTqyx8DHTEmd6946NkTFyzq52kbERGSuP6",
      "sequenceNumber": 2
    }
  }
}
