processed 1 task

task 0 'publish'. lines 6-14:
Error: Transaction Effects Status: IOTA Move Bytecode Verification Error. Please run the IOTA Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IOTAMoveVerificationError, source: Some("Invalid entry point parameter type. Clock must be passed by immutable reference. got: &mut iota::clock::Clock"), command: Some(0) } }
