processed 1 task

task 0, lines 7-15:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Invalid entry point parameter type. Clock must be passed by immutable reference. got: iota::clock::Clock"), command: Some(0) } }
