processed 1 task

task 0 'publish'. lines 5-14:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Invalid entry point parameter type. Expected primitive or object type. Got: vector<vector<T0>>"), command: Some(0) } }
