processed 2 tasks

task 0, lines 5-12:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3762000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1, lines 15-24:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4385200,  storage_rebate: 980400, non_refundable_storage_fee: 0
