processed 1 task

task 0 'publish'. lines 7-15:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Invalid entry point parameter type. Random must be passed by immutable reference. got: &mut iota::random::Random"), command: Some(0) } }
