processed 5 tasks

task 0, lines 7-14:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3959600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1, lines 16-23:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3967200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 2, lines 25-32:
//# publish
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3967200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 34-42:
//# publish
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4506800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, lines 44-52:
//# publish
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4522000,  storage_rebate: 988000, non_refundable_storage_fee: 0
