processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 11-73:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 21964000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 74-76:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(2,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 3, lines 77-79:
//# run test::regulated_coin::partial_wrap --args object(1,0) --sender A
created: object(3,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 4, lines 80-82:
//# run test::regulated_coin::partial_wrap --args object(1,0) --sender A
created: object(4,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 5, lines 83-85:
//# run iota::coin::deny_list_v2_enable_global_pause --args object(0x403) object(1,2) --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: iota, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: iota, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 98, 53, 49, 101, 54, 51, 102, 98, 102, 48, 101, 55, 57, 50, 102, 99, 55, 55, 56, 100, 50, 56, 48, 102, 54, 52, 56, 50, 55, 101, 100, 49, 100, 54, 51, 55, 54, 54, 49, 98, 49, 97, 55, 48, 54, 51, 52, 49, 50, 101, 57, 99, 55, 100, 100, 51, 97, 48, 49, 56, 54, 102, 97, 50, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 217, 21, 183, 252, 140, 153, 37, 23, 59, 178, 86, 46, 10, 245, 109, 11, 40, 24, 207, 249, 19, 236, 198, 173, 177, 13, 162, 98, 162, 120, 222, 237] }
created: object(5,0), object(5,1), object(5,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 11985200,  storage_rebate: 2774000, non_refundable_storage_fee: 0

task 6, lines 86-88:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) true --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, lines 89-91:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 8, lines 92-94:
//# transfer-object 2,0 --sender B --recipient A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 9, lines 95-98:
//# run iota::pay::split_and_transfer --args object(2,0) 1 @A --type-args test::regulated_coin::REGULATED_COIN --sender B
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 10, line 99:
//# run test::regulated_coin::unwrap --args object(3,0) --sender A
mutated: object(0,0)
unwrapped: object(10,0)
deleted: object(3,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 2644800, non_refundable_storage_fee: 0

task 11, lines 101-104:
//# advance-epoch
Epoch advanced: 1

task 12, lines 105-107:
//# run test::regulated_coin::unwrap --args object(4,0) --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 13, lines 108-110:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 14, lines 111-113:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) true --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 15, lines 114-116:
//# run iota::coin::deny_list_v2_disable_global_pause --args object(0x403) object(1,2) --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2), object(5,1)
gas summary: computation_cost: 1000000, storage_cost: 6657600,  storage_rebate: 6657600, non_refundable_storage_fee: 0

task 16, lines 117-119:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) false --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 17, lines 120-122:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 18, lines 123-126:
//# run test::regulated_coin::full_wrap --args object(1,0) --sender A
created: object(18,0)
mutated: object(0,0)
wrapped: object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2644800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 19, line 127:
//# run test::regulated_coin::unwrap --args object(18,0) --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 20, lines 129-131:
//# advance-epoch
Epoch advanced: 2

task 21, line 132:
//# run test::regulated_coin::unwrap --args object(18,0) --sender A
mutated: object(0,0)
unwrapped: object(1,0)
deleted: object(18,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 2644800, non_refundable_storage_fee: 0
