processed 6 tasks

init:
A: object(0,0)

task 1, lines 12-61:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5), object(1,6), object(1,7), object(1,8), object(1,9), object(1,10)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 34260800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 62-64:
//# view-object 1,0
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::regulated_coin1::REGULATED_COIN1> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,0),
        },
    },
    balance: iota::balance::Balance<test::regulated_coin1::REGULATED_COIN1> {
        value: 10000u64,
    },
}

task 3, lines 65-67:
//# view-object 1,1
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::regulated_coin2::REGULATED_COIN2> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,1),
        },
    },
    balance: iota::balance::Balance<test::regulated_coin2::REGULATED_COIN2> {
        value: 10000u64,
    },
}

task 4, line 68:
//# run iota::coin::deny_list_v2_add --args object(0x403) object(1,5) @A --type-args test::regulated_coin2::REGULATED_COIN2 --sender A
events: Event { package_id: iota, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: iota, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 98, 99, 101, 99, 51, 97, 97, 52, 51, 57, 100, 56, 51, 57, 52, 99, 99, 56, 55, 50, 57, 52, 99, 51, 51, 100, 57, 50, 102, 98, 50, 97, 48, 56, 101, 56, 52, 99, 52, 97, 102, 49, 97, 57, 101, 56, 102, 50, 100, 98, 51, 53, 50, 97, 50, 98, 101, 49, 99, 97, 48, 51, 56, 53, 55, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 50, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 50, 68, 67, 246, 17, 2, 86, 76, 77, 199, 216, 47, 146, 122, 161, 14, 129, 182, 84, 62, 166, 216, 143, 196, 120, 241, 122, 102, 188, 19, 225, 140, 163] }
created: object(4,0), object(4,1), object(4,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 12220800,  storage_rebate: 2789200, non_refundable_storage_fee: 0

task 5, lines 70-71:
//# programmable --sender A --inputs object(1,0) object(1,1) @A
//> TransferObjects([Input(0), Input(1)], Input(2))
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @A, coin_type: "object(1,10)::regulated_coin2::REGULATED_COIN2" }
