processed 11 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-49:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 19471200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 50-52:
//# view-object 1,2
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCapV2<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,2),
        },
    },
    allow_global_pause: false,
}

task 3, lines 53-55:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(3,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 4, lines 56-58:
//# run iota::coin::deny_list_v2_add --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: iota, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: iota, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 55, 97, 52, 102, 54, 97, 50, 98, 50, 49, 101, 97, 99, 51, 50, 101, 53, 101, 50, 102, 56, 51, 97, 101, 48, 102, 50, 98, 99, 99, 53, 51, 56, 55, 52, 100, 99, 98, 56, 101, 98, 101, 97, 100, 99, 48, 56, 98, 102, 101, 53, 49, 99, 50, 55, 51, 55, 56, 56, 102, 100, 102, 98, 100, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 210, 164, 228, 214, 92, 55, 18, 179, 28, 104, 46, 16, 150, 182, 108, 109, 19, 194, 116, 114, 253, 76, 160, 101, 93, 12, 252, 80, 7, 207, 163, 100] }
created: object(4,0), object(4,1), object(4,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 12190400,  storage_rebate: 2774000, non_refundable_storage_fee: 0

task 5, lines 59-61:
//# run test::regulated_coin::assert_address_deny_status --args immshared(0x403) @B true --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, lines 62-64:
//# transfer-object 3,0 --sender B --recipient A
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @B, coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 7, lines 65-67:
//# run iota::pay::split_and_transfer --args object(3,0) 1 @A --type-args test::regulated_coin::REGULATED_COIN --sender B
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @B, coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 8, lines 68-70:
//# run iota::coin::deny_list_v2_remove --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2)
deleted: object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 4400400,  storage_rebate: 6862800, non_refundable_storage_fee: 0

task 9, lines 71-73:
//# run test::regulated_coin::assert_address_deny_status --args immshared(0x403) @B false --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 74:
//# transfer-object 3,0 --sender B --recipient A
mutated: object(0,1), object(3,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 1474400, non_refundable_storage_fee: 0
