processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-30:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5791200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 36:
//# run Test::M1::create --args 1 @B --sender B
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 38:
//# run Test::M1::create --args 2 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, line 40:
//# run Test::M1::create --args 3 @B --sender B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 42:
//# run Test::M1::create --args 4 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 8, line 44:
//# create-checkpoint
Checkpoint created: 2

task 9, line 46:
//# run Test::M1::create --args 100 @B --sender B
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 10, line 48:
//# run Test::M1::create --args 101 @A --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 11, line 50:
//# run Test::M1::create --args 102 @B --sender B
created: object(11,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 12, line 52:
//# run Test::M1::create --args 103 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 13, line 54:
//# run Test::M1::create --args 104 @B --sender B
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 14, line 56:
//# create-checkpoint
Checkpoint created: 3

task 15, lines 58-79:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0IjozLCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "EnWpFFgRUBm3LbuTfjJ6oF3RXVcnzpth6L9nn4Q18RNk",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 16, lines 81-105:
//# run-graphql --cursors {"c":3,"t":3,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "digest": "613degbde4DuvwwAZcQngGJzZkZ6GZJ9g8CwygpA1s1a",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
          "node": {
            "digest": "AYmLYSfPbk4sVdBLcV76UmZgPTETP7XsVCaNKHTJ5qzs",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 17, lines 107-130:
//# run-graphql --cursors {"c":3,"t":3,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0Ijo0LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0Ijo1LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "digest": "613degbde4DuvwwAZcQngGJzZkZ6GZJ9g8CwygpA1s1a",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 18, lines 132-156:
//# run-graphql --cursors {"c":3,"t":6,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0Ijo3LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0Ijo4LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
          "node": {
            "digest": "4kA8BHJRwCdE8BjFTpTfSGt9nvoii37twZRM91uxMuvi",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 19, lines 158-185:
//# run-graphql --cursors {"c":3,"t":5,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjozLCJ0Ijo2LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
          "node": {
            "digest": "AYmLYSfPbk4sVdBLcV76UmZgPTETP7XsVCaNKHTJ5qzs",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
          "node": {
            "digest": "4kA8BHJRwCdE8BjFTpTfSGt9nvoii37twZRM91uxMuvi",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 20, lines 187-210:
//# run-graphql --cursors {"c":3,"t":8,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
        "endCursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "Dqi2D27TQ531EiXzEonQGrANt8kJh9w5JZ6SMtmRpm9b",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 21, lines 212-236:
//# run-graphql --cursors {"c":3,"t":8,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0Ijo5LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "Dqi2D27TQ531EiXzEonQGrANt8kJh9w5JZ6SMtmRpm9b",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}
