processed 11 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-38:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 18392000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 39-41:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(2,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 3, lines 42-44:
//# run iota::coin::deny_list_v1_add --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: iota, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: iota, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 57, 54, 51, 101, 51, 51, 55, 54, 100, 49, 48, 51, 98, 51, 50, 50, 99, 56, 50, 51, 53, 54, 51, 55, 55, 101, 100, 53, 54, 57, 51, 99, 50, 55, 51, 49, 53, 56, 48, 48, 52, 49, 53, 51, 54, 50, 57, 97, 97, 101, 50, 102, 100, 51, 56, 49, 49, 55, 50, 99, 56, 50, 100, 99, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 190, 151, 1, 134, 198, 237, 153, 240, 113, 249, 57, 50, 254, 147, 131, 191, 242, 203, 140, 120, 90, 188, 242, 88, 218, 175, 150, 221, 187, 90, 104, 81] }
created: object(3,0), object(3,1), object(3,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 12190400,  storage_rebate: 2774000, non_refundable_storage_fee: 0

task 4, line 45:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(4,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 5, lines 47-49:
//# advance-epoch
Epoch advanced: 1

task 6, lines 50-52:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 7, lines 53-55:
//# run iota::coin::deny_list_v1_remove --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 6862800, non_refundable_storage_fee: 0

task 8, line 56:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 9, lines 58-60:
//# advance-epoch
Epoch advanced: 2

task 10, line 61:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(10,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0
