processed 14 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-36:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 18316000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 38:
//# view-object 1,0
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,0),
        },
    },
    balance: iota::balance::Balance<test::regulated_coin::REGULATED_COIN> {
        value: 10000u64,
    },
}

task 3, line 40:
//# view-object 1,1
Owner: Immutable
Version: 2
Contents: iota::coin::CoinMetadata<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,1),
        },
    },
    decimals: 9u8,
    name: std::string::String {
        bytes: vector[
            82u8,
            69u8,
            71u8,
            85u8,
            76u8,
            65u8,
            84u8,
            69u8,
            68u8,
            95u8,
            67u8,
            79u8,
            73u8,
            78u8,
        ],
    },
    symbol: std::ascii::String {
        bytes: vector[
            82u8,
            67u8,
        ],
    },
    description: std::string::String {
        bytes: vector[
            65u8,
            32u8,
            110u8,
            101u8,
            119u8,
            32u8,
            114u8,
            101u8,
            103u8,
            117u8,
            108u8,
            97u8,
            116u8,
            101u8,
            100u8,
            32u8,
            99u8,
            111u8,
            105u8,
            110u8,
        ],
    },
    icon_url: std::option::Option<iota::url::Url> {
        vec: vector[],
    },
}

task 4, line 42:
//# view-object 1,2
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCap<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,2),
        },
    },
}

task 5, line 44:
//# view-object 1,3
Owner: Immutable
Version: 2
Contents: iota::coin::RegulatedCoinMetadata<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,3),
        },
    },
    coin_metadata_object: iota::object::ID {
        bytes: fake(1,1),
    },
    deny_cap_object: iota::object::ID {
        bytes: fake(1,2),
    },
}

task 6, line 46:
//# view-object 1,4
Owner: Immutable
Version: 2
Contents: iota::coin::TreasuryCap<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,4),
        },
    },
    total_supply: iota::balance::Supply<test::regulated_coin::REGULATED_COIN> {
        value: 10000u64,
    },
}

task 7, lines 48-50:
//# view-object 1,5
1,5::regulated_coin

task 8, lines 51-53:
//# run iota::pay::split_and_transfer --args object(1,0) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(8,0)
mutated: object(0,0), object(1,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2462400, non_refundable_storage_fee: 0

task 9, lines 54-56:
//# run iota::coin::deny_list_add --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(9,0), object(9,1)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 11415200,  storage_rebate: 2751200, non_refundable_storage_fee: 0

task 10, lines 57-59:
//# transfer-object 8,0 --sender B --recipient A
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @B, coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 11, lines 60-62:
//# run iota::pay::split_and_transfer --args object(8,0) 1 @A --type-args test::regulated_coin::REGULATED_COIN --sender B
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @B, coin_type: "object(1,5)::regulated_coin::REGULATED_COIN" }

task 12, lines 63-65:
//# run iota::coin::deny_list_remove --args object(0x403) object(1,2) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,2), object(9,1)
deleted: object(9,0)
gas summary: computation_cost: 1000000, storage_cost: 9522800,  storage_rebate: 11415200, non_refundable_storage_fee: 0

task 13, line 66:
//# transfer-object 8,0 --sender B --recipient A
mutated: object(0,1), object(8,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 1474400, non_refundable_storage_fee: 0
