processed 13 tasks

init:
A: object(0,0)

task 1, lines 9-48:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5), object(1,6)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 21766400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 50:
//# view-object 1,0
Owner: Account Address ( A )
Version: 2
Contents: test::regulated_coin::Wallet {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,0),
        },
    },
}

task 3, line 52:
//# view-object 1,1
Owner: Account Address ( fake(1,0) )
Version: 2
Contents: iota::coin::Coin<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,1),
        },
    },
    balance: iota::balance::Balance<test::regulated_coin::REGULATED_COIN> {
        value: 10000u64,
    },
}

task 4, line 54:
//# view-object 1,2
Owner: Immutable
Version: 2
Contents: iota::coin::CoinMetadata<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,2),
        },
    },
    decimals: 9u8,
    name: std::string::String {
        bytes: vector[
            82u8,
            69u8,
            71u8,
            85u8,
            76u8,
            65u8,
            84u8,
            69u8,
            68u8,
            95u8,
            67u8,
            79u8,
            73u8,
            78u8,
        ],
    },
    symbol: std::ascii::String {
        bytes: vector[
            82u8,
            67u8,
        ],
    },
    description: std::string::String {
        bytes: vector[
            65u8,
            32u8,
            110u8,
            101u8,
            119u8,
            32u8,
            114u8,
            101u8,
            103u8,
            117u8,
            108u8,
            97u8,
            116u8,
            101u8,
            100u8,
            32u8,
            99u8,
            111u8,
            105u8,
            110u8,
        ],
    },
    icon_url: std::option::Option<iota::url::Url> {
        vec: vector[],
    },
}

task 5, line 56:
//# view-object 1,3
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCap<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,3),
        },
    },
}

task 6, line 58:
//# view-object 1,4
Owner: Immutable
Version: 2
Contents: iota::coin::RegulatedCoinMetadata<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,4),
        },
    },
    coin_metadata_object: iota::object::ID {
        bytes: fake(1,2),
    },
    deny_cap_object: iota::object::ID {
        bytes: fake(1,3),
    },
}

task 7, line 60:
//# view-object 1,5
Owner: Immutable
Version: 2
Contents: iota::coin::TreasuryCap<test::regulated_coin::REGULATED_COIN> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(1,5),
        },
    },
    total_supply: iota::balance::Supply<test::regulated_coin::REGULATED_COIN> {
        value: 10000u64,
    },
}

task 8, lines 62-64:
//# view-object 1,6
1,6::regulated_coin

task 9, lines 65-67:
//# run iota::coin::deny_list_add --args object(0x403) object(1,3) @A --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(9,0), object(9,1)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 11415200,  storage_rebate: 2751200, non_refundable_storage_fee: 0

task 10, lines 68-70:
//# run test::regulated_coin::receive_coin --args object(1,0) receiving(1,1) --sender A
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @A, coin_type: "object(1,6)::regulated_coin::REGULATED_COIN" }

task 11, lines 71-73:
//# run iota::coin::deny_list_remove --args object(0x403) object(1,3) @A --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(9,1)
deleted: object(9,0)
gas summary: computation_cost: 1000000, storage_cost: 9522800,  storage_rebate: 11415200, non_refundable_storage_fee: 0

task 12, line 74:
//# run test::regulated_coin::receive_coin --args object(1,0) receiving(1,1) --sender A
mutated: object(0,0), object(1,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 3807600,  storage_rebate: 3807600, non_refundable_storage_fee: 0
