processed 9 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-68:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9317600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 70:
//# run test::object_basics::create --sender A --args 10 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 72:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: test::object_basics::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 10u64,
}

task 4, line 74:
//# run test::object_basics::transfer_ --sender A --args object(2,0) @B
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 2386400, non_refundable_storage_fee: 0

task 5, line 76:
//# view-object 2,0
Owner: Account Address ( B )
Version: 3
Contents: test::object_basics::Object {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 10u64,
}

task 6, line 78:
//# run test::object_basics::create --sender B --args 20 @B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7, line 80:
//# run test::object_basics::update --sender B --args object(2,0) object(6,0)
events: Event { package_id: test, transaction_module: Identifier("object_basics"), sender: B, type_: StructTag { address: test, module: Identifier("object_basics"), name: Identifier("NewValueEvent"), type_params: [] }, contents: [20, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1), object(2,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 3784800,  storage_rebate: 3784800, non_refundable_storage_fee: 0

task 8, line 82:
//# run test::object_basics::delete --sender B --args object(2,0)
mutated: object(0,1)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2386400, non_refundable_storage_fee: 0
