processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-39:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6946400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 41-41:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 43-43:
Owner: Account Address ( A )
Version: 3
Contents: test::object_basics::Object {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 4 'run'. lines 45-45:
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 1398400, non_refundable_storage_fee: 0

task 5 'run'. lines 47-47:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 2637200, non_refundable_storage_fee: 0

task 6 'view-object'. lines 49-49:
Owner: Immutable
Version: 5
Contents: test::object_basics::Object {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 10u64}
