processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 15-62:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7516400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 64-64:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'run'. lines 66-66:
created: object(3,0)
mutated: object(0,1)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 2386400, non_refundable_storage_fee: 0

task 4 'run'. lines 68-68:
mutated: object(0,1)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2637200, non_refundable_storage_fee: 0

task 5 'run'. lines 70-70:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'run'. lines 72-72:
mutated: object(0,1)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2637200, non_refundable_storage_fee: 0
