processed 7 tasks

init:
A: object(0,0)

task 1, lines 15-62:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7516400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 64:
//# run test::object_basics::create --args 10
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 66:
//# run test::object_basics::wrap --args object(2,0)
created: object(3,0)
mutated: object(0,1)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 2386400, non_refundable_storage_fee: 0

task 4, line 68:
//# run test::object_basics::unwrap_and_delete --args object(3,0)
mutated: object(0,1)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2637200, non_refundable_storage_fee: 0

task 5, line 70:
//# run test::object_basics::create_and_wrap --args 10
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 72:
//# run test::object_basics::unwrap_and_delete --args object(5,0)
mutated: object(0,1)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2637200, non_refundable_storage_fee: 0
