processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-34:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6194000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 36-36:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'run'. lines 38-38:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'run'. lines 40-40:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'run'. lines 42-42:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'run'. lines 44-44:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'programmable'. lines 46-50:
created: object(7,0)
mutated: object(0,0), object(2,0), object(3,0), object(4,0), object(5,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 6574000, non_refundable_storage_fee: 0

task 8 'run'. lines 52-52:
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 9 'create-checkpoint'. lines 54-54:
Checkpoint created: 1

task 10 'run-graphql'. lines 57-94:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "CxbWrhYuFJNpHyPBvfv55MFXbjspxDUWxyq7TQwsGAdo",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": false,
                "hasNextPage": false,
                "startCursor": "eyJpIjowLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "digest": "BhZV2woL6dxruabvZmG2UtGp1K1cLU6Qp1RWWTjZW445",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "create"
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "FED2QgkGbAjT8rwTRxh7pJCqJJxu5PFrw9toBQsQH2EM",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 96-133:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "CxbWrhYuFJNpHyPBvfv55MFXbjspxDUWxyq7TQwsGAdo",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": true,
                "hasNextPage": false,
                "startCursor": "eyJpIjoxLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "FED2QgkGbAjT8rwTRxh7pJCqJJxu5PFrw9toBQsQH2EM",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
