processed 12 tasks

init:
A: object(0,0)

task 1, lines 7-34:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6194000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# run Test::M1::create --args 2 @A
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 38:
//# run Test::M1::create --args 3 @A
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 40:
//# run Test::M1::create --args 4 @A
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 42:
//# run Test::M1::create --args 5 @A
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 44:
//# run Test::M1::create --args 6 @A
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, lines 46-50:
//# programmable --sender A --inputs object(2,0) object(3,0) object(4,0) object(5,0) object(6,0) @A
//> 0: Test::M1::sum(Input(0), Input(1));
//> 1: Test::M1::sum(Input(2), Input(3));
//> 2: Test::M1::sum(Input(0), Input(4));
//> 3: Test::M1::create(Result(2), Input(5));
created: object(7,0)
mutated: object(0,0), object(2,0), object(3,0), object(4,0), object(5,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 6574000, non_refundable_storage_fee: 0

task 8, line 52:
//# run Test::M1::increment --sender A --args object(7,0) 100
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 9, line 54:
//# create-checkpoint
Checkpoint created: 1

task 10, lines 57-94:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "G3zJ6KGNDB63vRVbV7qfzzxWXbxkQPXDimUQE484zdk8",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": false,
                "hasNextPage": false,
                "startCursor": "eyJpIjowLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "digest": "CWFW8Gbs1FhvtgReQVQGYaYqXAUxVrD3RCiZjxk6Kpww",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "GKY11WCjiXKjnfZcwyA6mtoqXRpLP7gAEtMrXWLppf2S",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "create"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 11, lines 96-133:
//# run-graphql --cursors {"i":0,"c":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "G3zJ6KGNDB63vRVbV7qfzzxWXbxkQPXDimUQE484zdk8",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": true,
                "hasNextPage": false,
                "startCursor": "eyJpIjoxLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "GKY11WCjiXKjnfZcwyA6mtoqXRpLP7gAEtMrXWLppf2S",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "create"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
