processed 1 task

task 0 'publish'. lines 7-17:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("Expected last (and at most second) parameter for _::mod::init to be &mut iota::tx_context::TxContext or &iota::tx_context::TxContext; optional first parameter must be of one-time witness type whose name is the same as the capitalized module name (_::mod::MOD) and which has no fields or a single field of type bool"), command: Some(0) } }
