processed 8 tasks

init:
A: object(0,0)

task 1, lines 7-60:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8937600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 62:
//# run test::m::parent --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2470000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 64:
//# run test::m::child --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 66:
//# run test::m::add_field --sender A --args object(2,0) object(3,0)
created: object(4,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6224400,  storage_rebate: 3769600, non_refundable_storage_fee: 0

task 5, line 68:
//# view-object 3,0
Owner: Object ID: ( fake(4,0) )
Version: 4
Contents: test::m::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 6, line 70:
//# run test::m::buy --sender A --args object(2,0)
created: object(6,0)
mutated: object(0,0), object(2,0), object(3,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 6224400, non_refundable_storage_fee: 0

task 7, line 72:
//# view-object 3,0
Owner: Account Address ( A )
Version: 5
Contents: test::m::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}
