processed 11 tasks

init:
A: object(0,0)

task 1, lines 10-78:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 12205600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 80:
//# run a::m::t0 --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 82:
//# run a::m::t1 --sender A --args object(2,0)
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6513200,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 4, line 84:
//# run a::m::t2 --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 5, line 86:
//# run a::m::t3 --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 6, line 88:
//# run a::m::t4 --sender A --args object(2,0)
mutated: object(0,0), object(2,0), object(3,0), object(3,1), object(3,2)
gas summary: computation_cost: 1000000, storage_cost: 6513200,  storage_rebate: 6513200, non_refundable_storage_fee: 0

task 7, line 90:
//# run a::m::t5 --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 8, line 92:
//# run a::m::t6 --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
deleted: object(3,1), object(3,2)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 5099600, non_refundable_storage_fee: 0

task 9, line 94:
//# run a::m::t7 --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 10, line 96:
//# run a::m::t8 --sender A --args object(2,0)
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2211600, non_refundable_storage_fee: 0
