processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 12-53:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9614000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 55-57:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2249600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 58-58:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2249600, non_refundable_storage_fee: 0

task 4 'run'. lines 60-62:
mutated: object(0,0), object(2,0), object(3,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3496000,  storage_rebate: 5950800, non_refundable_storage_fee: 0

task 5 'run'. lines 63-63:
created: object(3,0), object(5,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2249600, non_refundable_storage_fee: 0

task 6 'run'. lines 65-67:
mutated: object(0,0), object(2,0)
deleted: object(3,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2249600,  storage_rebate: 5950800, non_refundable_storage_fee: 0

task 7 'run'. lines 68-68:
created: object(3,0), object(7,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2249600, non_refundable_storage_fee: 0

task 8 'run'. lines 70-70:
mutated: object(0,0), object(2,0)
deleted: object(3,0)
wrapped: object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2492800,  storage_rebate: 5950800, non_refundable_storage_fee: 0
