processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-40:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7478400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 42-42:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4157200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 44-44:
created: object(3,1)
mutated: object(0,0), object(2,0)
unwrapped: object(3,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 4157200, non_refundable_storage_fee: 0

task 4 'view-object'. lines 46-46:
Owner: Object ID: ( fake(3,1) )
Version: 3
Contents: a::m::Obj {id: iota::object::UID {id: iota::object::ID {bytes: fake(3,0)}}}

task 5 'run'. lines 49-49:
created: object(5,0), object(5,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4157200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'run'. lines 51-51:
mutated: object(0,0), object(5,0)
deleted: object(5,1)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 4157200, non_refundable_storage_fee: 0

task 7 'run'. lines 54-54:
created: object(7,0), object(7,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4157200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8 'run'. lines 57-57:
mutated: object(0,0), object(7,0)
unwrapped: object(8,0)
deleted: object(7,1)
gas summary: computation_cost: 1000000, storage_cost: 3435200,  storage_rebate: 4157200, non_refundable_storage_fee: 0

task 9 'view-object'. lines 59-59:
Owner: Account Address ( A )
Version: 7
Contents: a::m::Obj {id: iota::object::UID {id: iota::object::ID {bytes: fake(7,0)}}}
