processed 10 tasks

init:
A: object(0,0)

task 1, lines 11-83:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10229600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 85:
//# run a::m::t0 --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 87:
//# run a::m::t1 --sender A --args object(2,0)
created: object(3,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4248400,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 4, line 89:
//# run a::m::t2 --sender A --args object(2,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 4248400,  storage_rebate: 4248400, non_refundable_storage_fee: 0

task 5, line 91:
//# run a::m::t3 --sender A --args object(2,0)
created: object(5,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2485200,  storage_rebate: 2211600, non_refundable_storage_fee: 0

task 6, line 93:
//# view-object 3,0
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: iota::dynamic_field::Field<u64, a::m::Counter> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    name: 0u64,
    value: a::m::Counter {
        id: iota::object::UID {
            id: iota::object::ID {
                bytes: _,
            },
        },
        count: 1u64,
    },
}

task 7, line 95:
//# run a::m::t4 --sender A --args object(5,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2485200,  storage_rebate: 2485200, non_refundable_storage_fee: 0

task 8, line 97:
//# run a::m::t5 --sender A --args object(5,0)
mutated: object(0,0)
deleted: object(5,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2485200, non_refundable_storage_fee: 0

task 9, line 99:
//# view-object 3,0
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: iota::dynamic_field::Field<u64, a::m::Counter> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(3,0),
        },
    },
    name: 0u64,
    value: a::m::Counter {
        id: iota::object::UID {
            id: iota::object::ID {
                bytes: _,
            },
        },
        count: 1u64,
    },
}
