processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-40:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7478400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 42-42:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 44-44:
Owner: Object ID: ( fake(2,2) )
Version: 2
Contents: a::m::Obj {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 4 'run'. lines 46-46:
created: object(4,0)
mutated: object(0,0), object(2,0)
deleted: object(2,2)
wrapped: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 4157200,  storage_rebate: 5890000, non_refundable_storage_fee: 0

task 5 'run'. lines 49-49:
created: object(5,0), object(5,1), object(5,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'view-object'. lines 51-51:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,2)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(5,1)}}

task 7 'run'. lines 53-53:
mutated: object(0,0), object(5,0)
deleted: object(5,1), object(5,2)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 5890000, non_refundable_storage_fee: 0

task 8 'run'. lines 56-56:
created: object(8,0), object(8,1), object(8,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9 'view-object'. lines 58-58:
Owner: Object ID: ( fake(8,0) )
Version: 6
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(8,2)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(8,1)}}

task 10 'run'. lines 60-60:
mutated: object(0,0), object(8,0), object(8,1)
deleted: object(8,2)
gas summary: computation_cost: 1000000, storage_cost: 3435200,  storage_rebate: 5890000, non_refundable_storage_fee: 0

task 11 'view-object'. lines 62-62:
No object at id 8,2
