processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 15-56:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8474000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 58-58:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 60-60:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 4 'run'. lines 62-62:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'view-object'. lines 64-64:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 6 'run'. lines 66-66:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'view-object'. lines 68-68:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 8 'run'. lines 70-70:
mutated: object(0,0), object(2,0)
deleted: object(4,0), object(4,1), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 8577360, non_refundable_storage_fee: 86640

task 9 'run'. lines 72-72:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 10 'create-checkpoint'. lines 74-74:
Checkpoint created: 1

task 11 'run-graphql'. lines 76-139:
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB9Wpt7yPiw0b+V7xu9MGQCsYq0OWQxFtQi4mPoC/7EnAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEWNwz4egf/t/Xiao6X/u+azGrcIwL/wI1WXG2m1cXFUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJYN/tdv+gaMRcH71OEsf4ipQtd6wX90joLI/yc3tpeZAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df123_removed": {
      "version": 5,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB9Wpt7yPiw0b+V7xu9MGQCsYq0OWQxFtQi4mPoC/7EnAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEWNwz4egf/t/Xiao6X/u+azGrcIwL/wI1WXG2m1cXFUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJYN/tdv+gaMRcH71OEsf4ipQtd6wX90joLI/yc3tpeZAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df456_added": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBxZ3uRM7nHLnpd3O44nxNtAbCYKgZOMXJYlse1n4oF3AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IB9Wpt7yPiw0b+V7xu9MGQCsYq0OWQxFtQi4mPoC/7EnAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEWNwz4egf/t/Xiao6X/u+azGrcIwL/wI1WXG2m1cXFUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IGxDUOw+5W7M0ZduJDeDy3qRSsyOo3LQhPCzBCtPB/etAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IG2UokriK5na2QV8pJyKrJdHBwcMCyhc8Gcf3Uiepfi+AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IJYN/tdv+gaMRcH71OEsf4ipQtd6wX90joLI/yc3tpeZAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      },
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}

task 12 'run-graphql'. lines 141-179:
Response: {
  "data": {
    "latest_owner": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB9Wpt7yPiw0b+V7xu9MGQCsYq0OWQxFtQi4mPoC/7EnAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEWNwz4egf/t/Xiao6X/u+azGrcIwL/wI1WXG2m1cXFUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJYN/tdv+gaMRcH71OEsf4ipQtd6wX90joLI/yc3tpeZAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}
