processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 15-59:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7949600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 61-63:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 65-65:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4 'run'. lines 67-67:
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5 'create-checkpoint'. lines 69-69:
Checkpoint created: 1

task 6 'run-graphql'. lines 71-128:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "INDhHYrfvNdCcG9BX6c0XhiOQnzLzQT07fefvnDZZMegAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "INDhHYrfvNdCcG9BX6c0XhiOQnzLzQT07fefvnDZZMegAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicObjectField": null
    }
  }
}

task 7 'run'. lines 130-130:
mutated: object(0,0), object(2,1)
deleted: object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 132-132:
Checkpoint created: 2

task 9 'run-graphql'. lines 134-185:
Response: {
  "data": {
    "latest": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_delete_dof": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 10 'run'. lines 187-187:
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 11 'create-checkpoint'. lines 189-189:
Checkpoint created: 3

task 12 'run-graphql'. lines 191-254:
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "version": 6,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "parent_version_6": {
      "version": 6,
      "dynamicObjectField": null
    },
    "parent_version_5": {
      "version": 5,
      "dynamicObjectField": null
    },
    "parent_version_4": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2fbddb59ced320e749a120c9351729b05a8e933746e94e2a929afb397dfddae9",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
