processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 20-59:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 61-63:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 65-65:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4 'create-checkpoint'. lines 67-67:
Checkpoint created: 1

task 5 'run-graphql'. lines 69-131:
Response: {
  "data": {
    "latest": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEki0I4UdteBAoGIb4p7F7jH6FZywodak8m48LQqsv2xAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEki0I4UdteBAoGIb4p7F7jH6FZywodak8m48LQqsv2xAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEki0I4UdteBAoGIb4p7F7jH6FZywodak8m48LQqsv2xAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    }
  }
}

task 6 'run'. lines 133-133:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 7 'create-checkpoint'. lines 135-135:
Checkpoint created: 2

task 8 'run-graphql'. lines 137-187:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_reclaim_and_transfer_dof": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x9dc01201599c493e6e02e7a4ce58df1aa3fe11ded754863c97d55c103e182252",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
