processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 19-58:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 60-63:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4924800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 65-65:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4 'run'. lines 67-67:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 5 'run'. lines 69-69:
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 6 'run'. lines 71-71:
mutated: object(0,0), object(2,0), object(2,2)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 7 'run'. lines 73-73:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 75-75:
Checkpoint created: 1

task 9 'run-graphql'. lines 77-157:
Response: {
  "data": {
    "latest": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB0EVYiI7WoMUZ2RSwKcfftZb0coxQhHiFvuQsWLtzOHAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB0EVYiI7WoMUZ2RSwKcfftZb0coxQhHiFvuQsWLtzOHAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
              "count": "0"
            }
          }
        }
      }
    },
    "v2": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v3": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB0EVYiI7WoMUZ2RSwKcfftZb0coxQhHiFvuQsWLtzOHAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
              "count": "0"
            }
          }
        }
      }
    },
    "v4": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v7": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IB0EVYiI7WoMUZ2RSwKcfftZb0coxQhHiFvuQsWLtzOHAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x2f9e2dea3e07af1878d3cd80632bfc574f9eb8c23c97cd9c35f7bbf6d30f9ee2",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
