processed 10 tasks

init:
A: object(0,0)

task 1, lines 19-58:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 60-63:
//# programmable --sender A --inputs @A
//> 0: Test::M1::child(Input(0));
//> 1: Test::M1::parent(Input(0));
//> 2: Test::M1::parent(Input(0));
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4924800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 65:
//# run Test::M1::add_child --sender A --args object(2,1) object(2,0) 42
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4, line 67:
//# run Test::M1::reclaim_and_transfer_child --sender A --args object(2,1) 42 @A
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 5, line 69:
//# run Test::M1::add_child --sender A --args object(2,2) object(2,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 6, line 71:
//# run Test::M1::reclaim_and_transfer_child --sender A --args object(2,2) 42 @A
mutated: object(0,0), object(2,0), object(2,2)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 7, line 73:
//# run Test::M1::add_child --sender A --args object(2,1) object(2,0) 42
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 8, line 75:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 77-157:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGwYH5v+7AWkcui2XgICiCBJE0IV0cDJpSvHs1P/j6uOAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGwYH5v+7AWkcui2XgICiCBJE0IV0cDJpSvHs1P/j6uOAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
              "count": "0"
            }
          }
        }
      }
    },
    "v2": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v3": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGwYH5v+7AWkcui2XgICiCBJE0IV0cDJpSvHs1P/j6uOAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
              "count": "0"
            }
          }
        }
      }
    },
    "v4": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v7": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGwYH5v+7AWkcui2XgICiCBJE0IV0cDJpSvHs1P/j6uOAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xceba7e0eb5c3dcfa4567dc4c3b19ef8c030e769cfce310fa6178a65bb3938d2e",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
