processed 9 tasks

init:
A: object(0,0)

task 1, lines 20-59:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 61-63:
//# programmable --sender A --inputs @A
//> 0: Test::M1::child(Input(0));
//> 1: Test::M1::parent(Input(0));
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 65:
//# run Test::M1::add_child --sender A --args object(2,1) object(2,0) 42
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4, line 67:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 69-131:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHXw7HKd1+5wVviB/aZV3hOHElzvVHueTKMKQQ7bL6+bAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHXw7HKd1+5wVviB/aZV3hOHElzvVHueTKMKQQ7bL6+bAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHXw7HKd1+5wVviB/aZV3hOHElzvVHueTKMKQQ7bL6+bAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    }
  }
}

task 6, line 133:
//# run Test::M1::reclaim_and_transfer_child --sender A --args object(2,1) 42 @A
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 7, line 135:
//# create-checkpoint
Checkpoint created: 2

task 8, lines 137-187:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_reclaim_and_transfer_dof": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x59ec032f03280718a543022037bfc541b929e2163fb01bfb3375e91e07dd46b9",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
