processed 35 tasks

init:
A: object(0,0)

task 1, lines 13-83:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 11012400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 85-87:
//# programmable --sender A --inputs @A 42
//> 0: Test::M1::parent(Input(0));
//> 1: Test::M1::child(Input(0));
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3549200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 89:
//# view-object 2,1
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 4, line 91:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 5, lines 93-95:
//# programmable --sender A --inputs object(2,1) object(2,0) 420
//> Test::M1::add_child(Input(0), Input(1), Input(2));
//> Test::M1::mutate_child_via_parent(Input(0), Input(2));
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6004000,  storage_rebate: 3549200, non_refundable_storage_fee: 0

task 6, line 97:
//# view-object 2,1
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 7, line 99:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
}

task 8, line 101:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 103-165:
//# run-graphql
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0x9b17c77897b11d25e53cc7463a81c1d9af23d84d8a5dd34870336d13bff9dfbb",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "child_version_2_no_parent": {
      "address": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0xb89417c448fb130a9fea7bc44997d1b87ae2c2ba76153e3db44a72e8779cfaa7"
        }
      }
    }
  }
}

task 10, lines 167-169:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::mutate_child_via_parent(Input(0), Input(1));
//> Test::M1::add_df(Input(0));
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9910400,  storage_rebate: 3549200, non_refundable_storage_fee: 0

task 11, line 171:
//# view-object 2,1
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 12, line 173:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 13, line 175:
//# create-checkpoint
Checkpoint created: 2

task 14, lines 177-237:
//# run-graphql --cursors @{obj_5_0,1} @{obj_5_0,2}
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFtgLwfbCz/3E//mzdSVpu4ez5fBp7KA5ltdR38IrI92AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "ILNCNL5tMmhrIjqkp6jCwD+VbCSLvcMmv5G/z0pietDPAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "ILP0gd7OZRIuOKQKAzembrtU1HN4JgcwfPKrx+U6mTkzAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15, lines 239-276:
//# run-graphql
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
              "count": "1"
            }
          }
        }
      },
      "dfNotAvailableYet": null
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
              "count": "2"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16, lines 279-280:
//# programmable --sender A --inputs object(2,1)
//> Test::M1::add_more_df(Input(0));
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 8603200,  storage_rebate: 2242000, non_refundable_storage_fee: 0

task 17, line 282:
//# view-object 2,1
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 18, line 284:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 19, line 286:
//# create-checkpoint
Checkpoint created: 3

task 20, lines 288-338:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,3}
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFtgLwfbCz/3E//mzdSVpu4ez5fBp7KA5ltdR38IrI92AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "ILNCNL5tMmhrIjqkp6jCwD+VbCSLvcMmv5G/z0pietDPAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "ILP0gd7OZRIuOKQKAzembrtU1HN4JgcwfPKrx+U6mTkzAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFtgLwfbCz/3E//mzdSVpu4ez5fBp7KA5ltdR38IrI92AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IGh9QdJmerULm2U0Vgl+dHTky2w8FY1yUcefsjV0tDrYAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILNCNL5tMmhrIjqkp6jCwD+VbCSLvcMmv5G/z0pietDPAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "ILP0gd7OZRIuOKQKAzembrtU1HN4JgcwfPKrx+U6mTkzAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    }
  }
}

task 21, lines 340-341:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::remove_df(Input(0));
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 8603200, non_refundable_storage_fee: 0

task 22, line 343:
//# view-object 2,1
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 23, line 345:
//# view-object 2,0
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 24, line 347:
//# create-checkpoint
Checkpoint created: 4

task 25, lines 349-399:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFtgLwfbCz/3E//mzdSVpu4ez5fBp7KA5ltdR38IrI92BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "ILNCNL5tMmhrIjqkp6jCwD+VbCSLvcMmv5G/z0pietDPBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "ILP0gd7OZRIuOKQKAzembrtU1HN4JgcwfPKrx+U6mTkzBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGh9QdJmerULm2U0Vgl+dHTky2w8FY1yUcefsjV0tDrYBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    }
  }
}

task 26, lines 401-432:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28, line 436:
//# create-checkpoint
Checkpoint created: 5

task 30, line 440:
//# create-checkpoint
Checkpoint created: 6

task 31, line 442:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 5
Objects snapshot updated to [0 to 5)

task 32, line 444:
//# create-checkpoint
Checkpoint created: 7

task 33, lines 446-496:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_outside_consistent_range": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IGh9QdJmerULm2U0Vgl+dHTky2w8FY1yUcefsjV0tDrYBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILiUF8RI+xMKn+p7xEmX0bh64sK6dhU+PbRKcuh3nPqnBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x02e810e035c69c934c04a5682db50c9927f3fd0e10767b19d415648df8cf7cb0",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IMXxmNuixDgFB3iNq2WVCHt6uyaNF4mprMCQV1yGDvwhBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IP9ZdEW4kSAmqHOsPwD086GsrTjnSVleaY7aiiokQfECBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 34,
          "column": 5
        }
      ],
      "path": [
        "parent_version_4_paginated_outside_consistent_range",
        "dynamicFields"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 34, lines 498-529:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4_outside_range": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
