processed 17 tasks

init:
A: object(0,0)

task 1, lines 21-69:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8770400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 71:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 73:
//# run Test::M1::child --sender A --args @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 75:
//# run Test::M1::child --sender A --args @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 77:
//# run Test::M1::add_child --sender A --args object(2,0) object(3,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 6, line 79:
//# run Test::M1::add_nested_child --sender A --args object(2,0) 42 object(4,0) 420
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 7, line 81:
//# run Test::M1::reclaim_and_freeze_child --sender A --args object(2,0) 42
mutated: object(0,0), object(2,0), object(3,0)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 8, line 83:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 85-115:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x09111ca47cc5d741e0b863376cd7aa9802eeaf0bd523d5e401e92fe6e285b285",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x09111ca47cc5d741e0b863376cd7aa9802eeaf0bd523d5e401e92fe6e285b285",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 117-147:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x09111ca47cc5d741e0b863376cd7aa9802eeaf0bd523d5e401e92fe6e285b285",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x09111ca47cc5d741e0b863376cd7aa9802eeaf0bd523d5e401e92fe6e285b285",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 149-179:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 12, lines 181-211:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 13, lines 213-240:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "parent": {
          "address": "0xc25bc87e84ba8bccb8ff343116b8a953561a21740b03a0ba7b5560351e939f9a"
        }
      },
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 14, lines 242-259:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 15, lines 261-288:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 16, lines 290-317:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x359748d588b708b35c5262a1f33aa1e0c255ee2cb5b413f93830965e662b9554",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
