processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 16-63:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8390400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 65-67:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 69-69:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 4 'run'. lines 71-71:
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2302800, non_refundable_storage_fee: 0

task 5 'create-checkpoint'. lines 73-73:
Checkpoint created: 1

task 6 'run-graphql'. lines 75-132:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICunAHo6kr5FYGqJtqWCzm+mrjxGNvDj1lTOEfITQUvXAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICunAHo6kr5FYGqJtqWCzm+mrjxGNvDj1lTOEfITQUvXAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicObjectField": null
    }
  }
}

task 7 'run'. lines 134-134:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6064800, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 136-136:
Checkpoint created: 2

task 9 'run-graphql'. lines 138-189:
Response: {
  "data": {
    "latest": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_reclaim_dof": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 10 'run'. lines 191-191:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 2295200, non_refundable_storage_fee: 0

task 11 'run'. lines 193-193:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 12 'create-checkpoint'. lines 195-195:
Checkpoint created: 3

task 13 'run-graphql'. lines 197-260:
Response: {
  "data": {
    "latest": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICunAHo6kr5FYGqJtqWCzm+mrjxGNvDj1lTOEfITQUvXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "1"
            }
          }
        }
      }
    },
    "owner_view": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICunAHo6kr5FYGqJtqWCzm+mrjxGNvDj1lTOEfITQUvXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "1"
            }
          }
        }
      }
    },
    "parent_version_6": null,
    "parent_version_5": {
      "version": 5,
      "dynamicObjectField": null
    },
    "parent_version_4": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3b4b81aa23428b84b9b3d494759a9fad25847fc90b201abd3a50343f84fb6fa0",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
