processed 17 tasks

init:
A: object(0,0)

task 1, lines 25-76:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8960400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 78:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 80:
//# run Test::M1::child --sender A --args @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 82:
//# run Test::M1::child --sender A --args @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 84:
//# run Test::M1::add_child --sender A --args object(2,0) object(3,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 6, line 86:
//# run Test::M1::add_nested_child --sender A --args object(2,0) 42 object(4,0) 420
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 7, line 88:
//# run Test::M1::mutate_child_on_parent --sender A --args object(2,0) 42
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 8, line 90:
//# run Test::M1::mutate_nested_child_on_parent --sender A --args object(2,0) 42 420
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3610000, non_refundable_storage_fee: 0

task 9, line 92:
//# create-checkpoint
Checkpoint created: 1

task 10, lines 94-124:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 126-156:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 158-188:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 13, lines 190-220:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xf4e2dff7ff1cd52e146de2dd609c6aea33a2f33e3d4b8c0083d18ed6491301f8",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                      "version": 8,
                      "contents": {
                        "json": {
                          "id": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                          "count": "1"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 14, lines 222-239:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 15, lines 241-258:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 16, lines 260-277:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x34749d6cf68ebb6c555d6ef2b25feb35e9cd7f0d2d698df39a17fe50fcdcd48b",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
