processed 6 tasks

task 1, lines 7-25:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5639200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 27:
//# run test::m::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 29:
//# run test::m::check --args object(2,0) 0
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0

task 4, line 31:
//# advance-epoch
Epoch advanced: 1

task 5, line 33:
//# run test::m::check --args object(2,0) 1
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 2257200, non_refundable_storage_fee: 0
