processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'create-checkpoint'. lines 14-14:
Checkpoint created: 1

task 2 'create-checkpoint'. lines 16-16:
Checkpoint created: 2

task 3 'advance-epoch'. lines 18-18:
Epoch advanced: 0

task 4 'run-graphql'. lines 20-35:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 3
    },
    "epoch": {
      "epochId": 0,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 0
          },
          {
            "sequenceNumber": 1
          },
          {
            "sequenceNumber": 2
          },
          {
            "sequenceNumber": 3
          }
        ]
      }
    }
  }
}

task 5 'create-checkpoint'. lines 37-37:
Checkpoint created: 4

task 6 'create-checkpoint'. lines 39-39:
Checkpoint created: 5

task 7 'create-checkpoint'. lines 41-41:
Checkpoint created: 6

task 8 'advance-epoch'. lines 43-43:
Epoch advanced: 1

task 9 'create-checkpoint'. lines 45-45:
Checkpoint created: 8

task 10 'create-checkpoint'. lines 47-47:
Checkpoint created: 9

task 11 'run-graphql'. lines 49-88:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 9
    },
    "epoch_0": {
      "epochId": 0,
      "checkpoints": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJzIjowfQ",
            "node": {
              "sequenceNumber": 0
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjoxfQ",
            "node": {
              "sequenceNumber": 1
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjoyfQ",
            "node": {
              "sequenceNumber": 2
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjozfQ",
            "node": {
              "sequenceNumber": 3
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "checkpoints": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJzIjo0fQ",
            "node": {
              "sequenceNumber": 4
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjo1fQ",
            "node": {
              "sequenceNumber": 5
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjo2fQ",
            "node": {
              "sequenceNumber": 6
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjo3fQ",
            "node": {
              "sequenceNumber": 7
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "checkpoints": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJzIjo4fQ",
            "node": {
              "sequenceNumber": 8
            }
          },
          {
            "cursor": "eyJjIjo5LCJzIjo5fQ",
            "node": {
              "sequenceNumber": 9
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 90-90:
Checkpoint created: 10

task 13 'run-graphql'. lines 92-123:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 0
          },
          {
            "sequenceNumber": 1
          },
          {
            "sequenceNumber": 2
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 4
          },
          {
            "sequenceNumber": 5
          },
          {
            "sequenceNumber": 6
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 8
          }
        ]
      }
    }
  }
}

task 14 'run-graphql'. lines 125-156:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 1
          },
          {
            "sequenceNumber": 2
          },
          {
            "sequenceNumber": 3
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 5
          },
          {
            "sequenceNumber": 6
          },
          {
            "sequenceNumber": 7
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 9
          }
        ]
      }
    }
  }
}

task 15 'run-graphql'. lines 158-189:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 2
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 6
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "checkpoints": {
        "nodes": []
      }
    }
  }
}
