processed 11 tasks

init:
A: object(0,0)

task 2, lines 11-13:
//# programmable --sender A --inputs 1 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 15:
//# create-checkpoint
Checkpoint created: 1

task 5, line 19:
//# create-checkpoint
Checkpoint created: 2

task 7, line 23:
//# create-checkpoint
Checkpoint created: 3

task 8, lines 25-37:
//# run-graphql
Response: {
  "data": {
    "c0": {
      "nodes": [
        {
          "digest": "C9TiGgKeeeNsuHBPq24sPmbmTqPgpKifXowxtLmY9zdx",
          "kind": {
            "__typename": "GenesisTransaction"
          }
        }
      ]
    },
    "c1": {
      "nodes": [
        {
          "digest": "BF9yHxJWj2LPv5y1rBNzAQz4YFyFNiRi7e8bB9a2mz1A",
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction"
          }
        },
        {
          "digest": "5NuqEYDLhdFh4oarijWEc6g8fmsEQRqnhQebzCDkcbHz",
          "kind": {
            "__typename": "ProgrammableTransactionBlock"
          }
        }
      ]
    },
    "c2": {
      "nodes": [
        {
          "digest": "DppACyzj6pqL4ERoLhKLK89FMpDKbtZpmkWRZi5y38dv",
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction"
          }
        }
      ]
    },
    "c3": {
      "nodes": [
        {
          "digest": "2fyunwjZdfqg3v7Xhb92cUdajFkCaqqUHmwuhQJ1phGX",
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction"
          }
        }
      ]
    },
    "c4": {
      "nodes": []
    }
  }
}

task 9, lines 39-51:
//# run-graphql
Response: {
  "data": {
    "c0": {
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "C9TiGgKeeeNsuHBPq24sPmbmTqPgpKifXowxtLmY9zdx",
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        ]
      }
    },
    "c1": {
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "BF9yHxJWj2LPv5y1rBNzAQz4YFyFNiRi7e8bB9a2mz1A",
            "kind": {
              "__typename": "ConsensusCommitPrologueTransaction"
            }
          },
          {
            "digest": "5NuqEYDLhdFh4oarijWEc6g8fmsEQRqnhQebzCDkcbHz",
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        ]
      }
    },
    "c2": {
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "DppACyzj6pqL4ERoLhKLK89FMpDKbtZpmkWRZi5y38dv",
            "kind": {
              "__typename": "ConsensusCommitPrologueTransaction"
            }
          }
        ]
      }
    },
    "c3": {
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "2fyunwjZdfqg3v7Xhb92cUdajFkCaqqUHmwuhQJ1phGX",
            "kind": {
              "__typename": "ConsensusCommitPrologueTransaction"
            }
          }
        ]
      }
    },
    "c4": null
  }
}

task 10, lines 53-64:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasNextPage": false
      },
      "nodes": [
        {
          "transactionBlocks": {
            "nodes": [
              {
                "digest": "C9TiGgKeeeNsuHBPq24sPmbmTqPgpKifXowxtLmY9zdx",
                "kind": {
                  "__typename": "GenesisTransaction"
                }
              }
            ]
          }
        },
        {
          "transactionBlocks": {
            "nodes": [
              {
                "digest": "BF9yHxJWj2LPv5y1rBNzAQz4YFyFNiRi7e8bB9a2mz1A",
                "kind": {
                  "__typename": "ConsensusCommitPrologueTransaction"
                }
              },
              {
                "digest": "5NuqEYDLhdFh4oarijWEc6g8fmsEQRqnhQebzCDkcbHz",
                "kind": {
                  "__typename": "ProgrammableTransactionBlock"
                }
              }
            ]
          }
        },
        {
          "transactionBlocks": {
            "nodes": [
              {
                "digest": "DppACyzj6pqL4ERoLhKLK89FMpDKbtZpmkWRZi5y38dv",
                "kind": {
                  "__typename": "ConsensusCommitPrologueTransaction"
                }
              }
            ]
          }
        },
        {
          "transactionBlocks": {
            "nodes": [
              {
                "digest": "2fyunwjZdfqg3v7Xhb92cUdajFkCaqqUHmwuhQJ1phGX",
                "kind": {
                  "__typename": "ConsensusCommitPrologueTransaction"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
