processed 8 tasks

task 1 'publish'. lines 7-12:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3663200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 14-15:
Error: Transaction Effects Status: Move Runtime Abort. Location: P0::m::boom (function index 1) at offset 1, Abort Code: 42
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: P0, name: Identifier("m") }, function: 1, instruction: 1, function_name: Some("boom") }, 42), source: Some(VMError { major_status: ABORTED, sub_status: Some(42), message: Some("P0::m::boom at offset 1"), exec_state: None, location: Module(ModuleId { address: P0, name: Identifier("m") }), indices: [], offsets: [(FunctionDefinitionIndex(1), 1)] }), command: Some(0) } }

task 3 'create-checkpoint'. lines 17-17:
Checkpoint created: 1

task 4 'run-graphql'. lines 19-31:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "status": "FAILURE",
            "errors": "Move Runtime Abort. Location: 764b07be3bf59740fe92e99140a9accc962da08fa44dd2caac7c15ac3245df51::m::boom (function index 1) at offset 1, Abort Code: 42 in 1st command."
          }
        }
      ]
    }
  }
}

task 5 'programmable'. lines 33-36:
Error: Transaction Effects Status: Move Runtime Abort. Location: P0::m::boom (function index 1) at offset 1, Abort Code: 42
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: P0, name: Identifier("m") }, function: 1, instruction: 1, function_name: Some("boom") }, 42), source: Some(VMError { major_status: ABORTED, sub_status: Some(42), message: Some("P0::m::boom at offset 1"), exec_state: None, location: Module(ModuleId { address: P0, name: Identifier("m") }), indices: [], offsets: [(FunctionDefinitionIndex(1), 1)] }), command: Some(2) } }

task 6 'create-checkpoint'. lines 38-38:
Checkpoint created: 2

task 7 'run-graphql'. lines 40-53:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "status": "FAILURE",
            "errors": "Move Runtime Abort. Location: 764b07be3bf59740fe92e99140a9accc962da08fa44dd2caac7c15ac3245df51::m::boom (function index 1) at offset 1, Abort Code: 42 in 3rd command."
          }
        }
      ]
    }
  }
}
