processed 6 tasks

task 1, line 7:
//# create-checkpoint
Checkpoint created: 1

task 2, lines 9-38:
//# run-graphql
Response: {
  "data": {
    "object": {
      "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
      "version": 1,
      "asMoveObject": {
        "contents": {
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
          },
          "json": {
            "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
            "inner": {
              "id": "0x6bbf96b04989567a44a053389c7020a7b234b54fe916b9b759fc94e08939d806",
              "version": "1"
            }
          }
        }
      }
    },
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "GenesisTransaction"
          }
        }
      ]
    }
  }
}

task 4, line 44:
//# create-checkpoint
Checkpoint created: 2

task 5, lines 46-61:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "RandomnessStateUpdateTransaction",
            "epoch": {
              "epochId": 0
            },
            "randomnessRound": 0,
            "randomBytes": "SGVsbG8gU3Vp",
            "randomnessObjInitialSharedVersion": 2
          }
        }
      ]
    }
  }
}
