processed 7 tasks

task 1, lines 7-23:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-26:
//# programmable --inputs immshared(1,0)
//> 0: P0::m::get(Input(0))
mutated: object(0,0)
unchanged_shared: object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 28-29:
//# programmable --inputs object(1,0)
//> 0: P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2272400, non_refundable_storage_fee: 0

task 4, lines 31-33:
//# programmable --inputs object(1,0)
//> 0: P0::m::get(Input(0));
//> P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2272400, non_refundable_storage_fee: 0

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaada297702741254a16048a46191b6d73e697ece387343fa7d57e93ccbe3a6fe",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0x003e9261fcd0f64b951a21ae77f470803b0e801a350e7a8934165b2201052f1c",
                  "version": 2,
                  "digest": "GfMkk6R7jooB9pyD6kUGHEpK66By21gpKrTAPZxkFSMS",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xaada297702741254a16048a46191b6d73e697ece387343fa7d57e93ccbe3a6fe::m::Foo"
                        },
                        "json": {
                          "id": "0x003e9261fcd0f64b951a21ae77f470803b0e801a350e7a8934165b2201052f1c",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaada297702741254a16048a46191b6d73e697ece387343fa7d57e93ccbe3a6fe",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xaada297702741254a16048a46191b6d73e697ece387343fa7d57e93ccbe3a6fe",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xaada297702741254a16048a46191b6d73e697ece387343fa7d57e93ccbe3a6fe",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
