processed 8 tasks

task 1, lines 9-103:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "2B5WCAR8XmpU5mGFe225Jk8bhnh5oXNjfyfaX72VELvJ",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbl9tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "coin_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW0iLCJjIjowfQ",
                            "node": {
                              "name": "iota_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW1fc3RhdGVfaW5uZXIiLCJjIjowfQ",
                            "node": {
                              "name": "iota_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tlZF9zdGFraW5nIiwiYyI6MH0",
                            "node": {
                              "name": "timelocked_staking"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::iota_system::IotaSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x3f92eceed239ba443daf612dcdf621f85feba71f3698d53c9f2a6e4b4246b1c6",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x799c22e253a384f3545724b35277ac6b27595603f051828e5f4cece335c1cf1c",
                            "size": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzc191bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "address_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXMiLCJjIjowfQ",
                            "node": {
                              "name": "alias"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "alias_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFzaWNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "basic_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXhwaXJhdGlvbl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "expiration_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaXJjMjciLCJjIjowfQ",
                            "node": {
                              "name": "irc27"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0IiwiYyI6MH0",
                            "node": {
                              "name": "nft"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0X291dHB1dCIsImMiOjB9",
                            "node": {
                              "name": "nft_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhcmR1c3RfdXBncmFkZV9sYWJlbCIsImMiOjB9",
                            "node": {
                              "name": "stardust_upgrade_label"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9kZXBvc2l0X3JldHVybl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "storage_deposit_return_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tfdW5sb2NrX2NvbmRpdGlvbiIsImMiOjB9",
                            "node": {
                              "name": "timelock_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXRpbGl0aWVzIiwiYyI6MH0",
                            "node": {
                              "name": "utilities"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x1b19651d3c2723e7f6c1eca23c13b72cd7f274524223391e75994dad311828df",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0x1b19651d3c2723e7f6c1eca23c13b72cd7f274524223391e75994dad311828df",
                          "name": "0",
                          "value": {
                            "iota_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x27982f48a697a9f61e3f738993c2d00e16b89938eedb74af1849ba6c6d82303b",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x27982f48a697a9f61e3f738993c2d00e16b89938eedb74af1849ba6c6d82303b",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::iota_system_state_inner::IotaSystemStateV1>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "1",
                            "system_state_version": "1",
                            "iota_treasury_cap": {
                              "inner": {
                                "id": "0x509e22a8bb835eeb98bed81a1a50c196383345279d4238f47714f2301c9bfbe6",
                                "total_supply": {
                                  "value": "31800000000000000"
                                }
                              }
                            },
                            "validators": {
                              "total_stake": "1500000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "iota_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                                    "authority_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "protocol_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      146,
                                      189,
                                      89,
                                      74,
                                      29,
                                      175,
                                      203,
                                      128,
                                      64,
                                      181,
                                      156,
                                      97,
                                      250,
                                      67,
                                      71,
                                      1,
                                      183,
                                      54,
                                      131,
                                      205,
                                      9,
                                      153,
                                      183,
                                      92,
                                      197,
                                      160,
                                      192,
                                      111,
                                      216,
                                      8,
                                      35,
                                      211,
                                      26,
                                      222,
                                      255,
                                      142,
                                      137,
                                      6,
                                      130,
                                      140,
                                      153,
                                      155,
                                      252,
                                      79,
                                      139,
                                      240,
                                      222,
                                      153
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8003/http",
                                    "next_epoch_authority_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "extra_fields": {
                                      "id": "0x6c8759462593f9ef531bbec3f6402e9a9d53e369ecb7982b59635843471eb271",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0xa0f947f895ffe5715ab529ed16659e9c099bee48524f56c8d5a2eab8e842bd99",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x7aea65806e468642f39bb0a0f7a40a4b16afc9588d1980e8d9a9d20936541b7e",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "iota_balance": "1500000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "1500000000000000",
                                    "exchange_rates": {
                                      "id": "0x044bc64e9c5eaa0143019c38bea813b1c288dc66272d74cf8a1821bf0eeac85f",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_iota_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0xcc8c44fff5e1f3fdc63bd2597685dba922cce4809e2f960c8128dcbcb76c3712",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "1500000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0x9a75ea182d4788588f2e81034a8a57034da6284a66159cd3289cb352e3a845aa",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0x31b89b7b349cf41a62274ebd1ef2c2789fa86b68270d9feefb7a62741d1f8e86",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x6025058d2b6287ffad433b714c9a573fe15ba477a4f47862b5088ca5938cded3",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0xaaf430f2910eb82232f946c1bda701ecb8f2c1f6928a9099ae80f5afc85fb69c",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0xd2789ba6e8f5c3241a6d12bedc3055e57aeac6e92bf182ef7737c6533d7a22f9",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x62d408b9b0b3c458c8424f68a6622c534d3023ce93368b5a412bd4dc665a8ebf",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "min_validator_count": "4",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "2000000000000000",
                              "validator_low_stake_threshold": "1500000000000000",
                              "validator_very_low_stake_threshold": "1000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0x61b4baf4a2f43504215e4131c43852e24775aa0afeef0628a113228ef41c7813",
                                "size": "0"
                              }
                            },
                            "iota_system_admin_cap": {
                              "dummy_field": false
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "safe_mode": false,
                            "safe_mode_storage_charges": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0x5dc4c87d84a69a6b0f51a38b24cd4c9833b79c2a2e249dc1f24794961bfc76c1",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0xa0f947f895ffe5715ab529ed16659e9c099bee48524f56c8d5a2eab8e842bd99",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0xa0f947f895ffe5715ab529ed16659e9c099bee48524f56c8d5a2eab8e842bd99",
                          "authorizer_validator_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0xbb5caa62668e66be9dd0a5a74534814bf789fd6ab6335e08eff62a58ee1f287e",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0xbb5caa62668e66be9dd0a5a74534814bf789fd6ab6335e08eff62a58ee1f287e",
                          "name": "0x7aea65806e468642f39bb0a0f7a40a4b16afc9588d1980e8d9a9d20936541b7e",
                          "value": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0xc28024efc650d31011065697e676b6738732dad9f709e54a13b116672c298f25",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xc28024efc650d31011065697e676b6738732dad9f709e54a13b116672c298f25",
                          "decimals": 9,
                          "name": "IOTA",
                          "symbol": "IOTA",
                          "description": "The main (gas)token of the IOTA Network.",
                          "icon_url": {
                            "url": "https://iota.org/logo.png"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0xc928f6f78781333f87efac974403df5a8565e3accb3c16a891a60a18dd2f2f42",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::Display<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
                        },
                        "json": {
                          "id": "0xc928f6f78781333f87efac974403df5a8565e3accb3c16a891a60a18dd2f2f42",
                          "fields": {
                            "contents": [
                              {
                                "key": "name",
                                "value": "{immutable_metadata.name}"
                              },
                              {
                                "key": "image_url",
                                "value": "{immutable_metadata.uri}"
                              },
                              {
                                "key": "description",
                                "value": "{immutable_metadata.description}"
                              },
                              {
                                "key": "creator",
                                "value": "{immutable_metadata.issuer_name}"
                              },
                              {
                                "key": "version",
                                "value": "{immutable_metadata.version}"
                              },
                              {
                                "key": "media_type",
                                "value": "{immutable_metadata.media_type}"
                              },
                              {
                                "key": "collection_name",
                                "value": "{immutable_metadata.collection_name}"
                              },
                              {
                                "key": "immutable_issuer",
                                "value": "{immutable_issuer}"
                              }
                            ]
                          },
                          "version": 1
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0xdd6b3a50df67a765e8c59bd37030224138f36bba296535846f490d8dede3c502",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedIota"
                        },
                        "json": {
                          "id": "0xdd6b3a50df67a765e8c59bd37030224138f36bba296535846f490d8dede3c502",
                          "pool_id": "0x7aea65806e468642f39bb0a0f7a40a4b16afc9588d1980e8d9a9d20936541b7e",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "1500000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0xe9ee601e69a2f4274ca5f23c16190823a7af496b5b9f2eac0d2c2645634b2737",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0xe9ee601e69a2f4274ca5f23c16190823a7af496b5b9f2eac0d2c2645634b2737",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xf22e2f7e20b84f57fdcf1f44c79c321533b922fa9488c23556356ae3f906b0bb",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0xf22e2f7e20b84f57fdcf1f44c79c321533b922fa9488c23556356ae3f906b0bb",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                },
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "ENjiFoxPrZM9nyeHuhGaWKLQmUaW7AGumKmKAtYRAkMx"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "25LNU4kgDKzmLynUBdNydovvBxmFcaqytbpP4v1uDeUb"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "Hp85vhPRftDufuLYqnkgsj6NXkjqBjAAFTt8Y1kTvi7E"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "BHCkaFS2xS78pxZH9p8zi5thePij2x57c9svkPEGm3KZ"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "CTBkMWme6atVxkSS7PgV55smTTQKWk84yNT2mqUuJYte"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "DSwZ4FmppSRBHwCQPuiuWFeiQ1DWA8XifY26iMoijDpP"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "3p6UjMn8i1hnqDYz8Y6ES6MB7Af2tgss6FPhXCyeLSPi"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "E3jwUuD8t2nzrDBTv6noK2PUyyvuVAysVUqW7KqnbfCc"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "digest": "3cUy8tgrqu5Xk1wgBkDz8ZUes4r9ezn3rx1aJcEEcpo4"
                  }
                },
                {
                  "address": "0x1b19651d3c2723e7f6c1eca23c13b72cd7f274524223391e75994dad311828df",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1b19651d3c2723e7f6c1eca23c13b72cd7f274524223391e75994dad311828df",
                    "digest": "6nG9sPDXR5jHQaGWhbbAX3rUg7EXtmWe1DxAzaGCoRG5"
                  }
                },
                {
                  "address": "0x27982f48a697a9f61e3f738993c2d00e16b89938eedb74af1849ba6c6d82303b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x27982f48a697a9f61e3f738993c2d00e16b89938eedb74af1849ba6c6d82303b",
                    "digest": "emzdESgN7RfkPjnaP1pvcyQDjVbU5U6iRrhAxLmMCq9"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "7HLikfNn3xnU7J3BZWtbdtX4sjceNmeM8qZdXgJvGWK4"
                  }
                },
                {
                  "address": "0xa0f947f895ffe5715ab529ed16659e9c099bee48524f56c8d5a2eab8e842bd99",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xa0f947f895ffe5715ab529ed16659e9c099bee48524f56c8d5a2eab8e842bd99",
                    "digest": "5HqXsg38zJApoSepyKxKMGjkzXgC2mpXJB7TWTmu3jqm"
                  }
                },
                {
                  "address": "0xbb5caa62668e66be9dd0a5a74534814bf789fd6ab6335e08eff62a58ee1f287e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xbb5caa62668e66be9dd0a5a74534814bf789fd6ab6335e08eff62a58ee1f287e",
                    "digest": "GbpQCkRKETYZ1mZaCXD1dDVencXtFgjjGHTDLLZLmyKs"
                  }
                },
                {
                  "address": "0xc28024efc650d31011065697e676b6738732dad9f709e54a13b116672c298f25",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc28024efc650d31011065697e676b6738732dad9f709e54a13b116672c298f25",
                    "digest": "uxV9PrgZ8ufgYxPKEbYoND3RVHajt2ggHn2p3biNM9z"
                  }
                },
                {
                  "address": "0xc928f6f78781333f87efac974403df5a8565e3accb3c16a891a60a18dd2f2f42",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc928f6f78781333f87efac974403df5a8565e3accb3c16a891a60a18dd2f2f42",
                    "digest": "9htprPEX2u5fQquygzgGj9nP6UaNBP31J6PVSwxwcmwk"
                  }
                },
                {
                  "address": "0xdd6b3a50df67a765e8c59bd37030224138f36bba296535846f490d8dede3c502",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xdd6b3a50df67a765e8c59bd37030224138f36bba296535846f490d8dede3c502",
                    "digest": "EwNpAgeEnd1fEmfUDf3xquRkE4RsA7QBetPGvbfAx78q"
                  }
                },
                {
                  "address": "0xe9ee601e69a2f4274ca5f23c16190823a7af496b5b9f2eac0d2c2645634b2737",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xe9ee601e69a2f4274ca5f23c16190823a7af496b5b9f2eac0d2c2645634b2737",
                    "digest": "CKk9xibx6DCsz5frc1ponJCY85Wp1TC71NpkJd4TPL6q"
                  }
                },
                {
                  "address": "0xf22e2f7e20b84f57fdcf1f44c79c321533b922fa9488c23556356ae3f906b0bb",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xf22e2f7e20b84f57fdcf1f44c79c321533b922fa9488c23556356ae3f906b0bb",
                    "digest": "CQvMCiaVuXqqwk8rLcEzYycJkLGkx1K3fKsrWxA5vovf"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "2B5WCAR8XmpU5mGFe225Jk8bhnh5oXNjfyfaX72VELvJ"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 107:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 109-184:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2B5WCAR8XmpU5mGFe225Jk8bhnh5oXNjfyfaX72VELvJ"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "7uXNaHWi3mgndvU5ucJ5SompTEpJAgV9TKY8c6H5tH2R"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 188:
//# advance-epoch
Epoch advanced: 0

task 7, lines 190-277:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "7PLwaqn6pg198VkYmVKERZ2Qad3vDEWhfB7VRv5qDSc7",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 1,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2B5WCAR8XmpU5mGFe225Jk8bhnh5oXNjfyfaX72VELvJ"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "Do9BxST2vAmc7ZRsxohXXg5S3QLzmgUYYQnP2ejXtP93"
                  }
                },
                {
                  "address": "0x0d8feaf1c714777ad5401781c55794e0b8f6dda166924176279914bed08951e0",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0d8feaf1c714777ad5401781c55794e0b8f6dda166924176279914bed08951e0",
                    "digest": "DXX64y9MQSS9WD6oemyeURG3ui88kg4Cm4wirWqx9Uzy"
                  }
                },
                {
                  "address": "0x4509fa198370254af0418248c9718bb206e810e1bce9fc8ffd0c500aef972f4d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4509fa198370254af0418248c9718bb206e810e1bce9fc8ffd0c500aef972f4d",
                    "digest": "BeJhqfZpuFRhdM55Fhu6KUCSz2173Ea6Kmm9NSsUoLvR"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "XMY7xLE7B9ucBNQsgHgjYJ1vDHfEie94oV7yM46VD5C"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "7PLwaqn6pg198VkYmVKERZ2Qad3vDEWhfB7VRv5qDSc7"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
