processed 8 tasks

task 1, lines 9-103:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "owLtYqnC2bar8fdBAVvprwpXyqAHifDfLzhA8wnH3zp",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbl9tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "coin_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW0iLCJjIjowfQ",
                            "node": {
                              "name": "iota_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaW90YV9zeXN0ZW1fc3RhdGVfaW5uZXIiLCJjIjowfQ",
                            "node": {
                              "name": "iota_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tlZF9zdGFraW5nIiwiYyI6MH0",
                            "node": {
                              "name": "timelocked_staking"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::iota_system::IotaSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x73d2208772e20289fb1cea42594854c50a2501e61b90d183ef41ee2bb505bb60",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0xf709144cfedfa72d2d85de81ad94f8190f7df64d5cfa413ccbe61d278fbe94de",
                            "size": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzc191bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "address_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXMiLCJjIjowfQ",
                            "node": {
                              "name": "alias"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWxpYXNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "alias_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFzaWNfb3V0cHV0IiwiYyI6MH0",
                            "node": {
                              "name": "basic_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXhwaXJhdGlvbl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "expiration_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaXJjMjciLCJjIjowfQ",
                            "node": {
                              "name": "irc27"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0IiwiYyI6MH0",
                            "node": {
                              "name": "nft"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibmZ0X291dHB1dCIsImMiOjB9",
                            "node": {
                              "name": "nft_output"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhcmR1c3RfdXBncmFkZV9sYWJlbCIsImMiOjB9",
                            "node": {
                              "name": "stardust_upgrade_label"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9kZXBvc2l0X3JldHVybl91bmxvY2tfY29uZGl0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "storage_deposit_return_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidGltZWxvY2tfdW5sb2NrX2NvbmRpdGlvbiIsImMiOjB9",
                            "node": {
                              "name": "timelock_unlock_condition"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXRpbGl0aWVzIiwiYyI6MH0",
                            "node": {
                              "name": "utilities"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiY2xvYiIsImMiOjB9",
                            "node": {
                              "name": "clob"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvYl92MiIsImMiOjB9",
                            "node": {
                              "name": "clob_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3JpdGJpdCIsImMiOjB9",
                            "node": {
                              "name": "critbit"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuIiwiYyI6MH0",
                            "node": {
                              "name": "custodian"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuX3YyIiwiYyI6MH0",
                            "node": {
                              "name": "custodian_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWF0aCIsImMiOjB9",
                            "node": {
                              "name": "math"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3JkZXJfcXVlcnkiLCJjIjowfQ",
                            "node": {
                              "name": "order_query"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x1dc43a801f3b30fb779bd47503a3c10d63633bcfe223a561d44d8f6b6f4edfe8",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x1dc43a801f3b30fb779bd47503a3c10d63633bcfe223a561d44d8f6b6f4edfe8",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x3e18371fd14fd50a737310ad7d46f0df700c574d740d4f3543e479921c39fe29",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0x3e18371fd14fd50a737310ad7d46f0df700c574d740d4f3543e479921c39fe29",
                          "name": "0",
                          "value": {
                            "iota_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<vector<u8>,0x0000000000000000000000000000000000000000000000000000000000000002::timelock::SystemTimelockCap>"
                        },
                        "json": {
                          "id": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                          "name": [
                            115,
                            121,
                            115,
                            95,
                            116,
                            105,
                            109,
                            101,
                            108,
                            111,
                            99,
                            107,
                            95,
                            99,
                            97,
                            112
                          ],
                          "value": {
                            "dummy_field": false
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::iota_system_state_inner::IotaSystemStateInner>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "1",
                            "system_state_version": "1",
                            "iota_treasury_cap": {
                              "inner": {
                                "id": "0xabdc3f9844e5778f3e474965fa886fbc424d5682b8f6436c74369b3aa81b52c3",
                                "total_supply": {
                                  "value": "31800000000000000"
                                }
                              }
                            },
                            "validators": {
                              "total_stake": "1500000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "iota_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80",
                                    "protocol_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "worker_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      146,
                                      189,
                                      89,
                                      74,
                                      29,
                                      175,
                                      203,
                                      128,
                                      64,
                                      181,
                                      156,
                                      97,
                                      250,
                                      67,
                                      71,
                                      1,
                                      183,
                                      54,
                                      131,
                                      205,
                                      9,
                                      153,
                                      183,
                                      92,
                                      197,
                                      160,
                                      192,
                                      111,
                                      216,
                                      8,
                                      35,
                                      211,
                                      26,
                                      222,
                                      255,
                                      142,
                                      137,
                                      6,
                                      130,
                                      140,
                                      153,
                                      155,
                                      252,
                                      79,
                                      139,
                                      240,
                                      222,
                                      153
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                    "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_worker_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "next_epoch_worker_address": null,
                                    "extra_fields": {
                                      "id": "0xf0b025bdd4b353cf2b6e501bd7cc3c3b778a613972775cf01d07a31e39bf05c1",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x7c9e49546cd2142c972f06f9c486abbacf2262e61a0c394389ff2f0545ccf087",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0xc9b7ce1abbfde8770d0dd2551ac0d388c76a4ff21c0e0eba854080f189dc4ebb",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "iota_balance": "1500000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "1500000000000000",
                                    "exchange_rates": {
                                      "id": "0xa9a4cc26fd90138b983541dae21074538cfe8133671d35fedf9a92431aefb6d9",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_iota_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0xfbddd19fd376f49c98b2876c329ce300854fff90f4a720a61a9ef4d0af009fd4",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "1500000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xf45606f5eb6619922bf4b5a05a7e461f9e18945c55268a8eed85770c1ac2254f",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0xe2d3e47ce2ed1eecc022dcaba38f424a9a74d98650e80e5bf160c8375d12f93a",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x6b0ee53436127e69f4fb595aeb427e12a4f8d8c97e91b102cbacc276ea9bfee8",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0xd75de20e144498b010384bcb7fd6f4078a0fe8ce81d0b6d07fea5a5185d437d4",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0x387cbdc22eada4358ad65a26bc078b0e56f9e6ed21ea3f989390689497a77e93",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x939ef64aa0879fdce71e506d6323535101d487d3d582821abc0cb99772cd4cd1",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "2000000000000000",
                              "validator_low_stake_threshold": "1500000000000000",
                              "validator_very_low_stake_threshold": "1000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0x4bcc19eccc7a2d8ff2502b68350518ae52d65029da0cd2ebb78543904c125469",
                                "size": "0"
                              }
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "safe_mode": false,
                            "safe_mode_storage_charges": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0x0ba8dd4ee7a4202d5fe195a105625c2ebde20e1ffd7e18a6b915080c6fdfda14",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x786236d69253100dbb83238530c069614796e195f16097c59608a28a685a1e8c",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "json": {
                          "id": "0x786236d69253100dbb83238530c069614796e195f16097c59608a28a685a1e8c",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x7c9e49546cd2142c972f06f9c486abbacf2262e61a0c394389ff2f0545ccf087",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x7c9e49546cd2142c972f06f9c486abbacf2262e61a0c394389ff2f0545ccf087",
                          "authorizer_validator_address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x8ae1f957f276825012bb5a0f2197bf236de443e50bd37c4b9df7aec9da5f2e55",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x8ae1f957f276825012bb5a0f2197bf236de443e50bd37c4b9df7aec9da5f2e55",
                          "name": "0xc9b7ce1abbfde8770d0dd2551ac0d388c76a4ff21c0e0eba854080f189dc4ebb",
                          "value": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0x8c3316c411399ffb49190b5c863f3237e9701aa86fa77815d7ea59df4b6e72f5",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0x8c3316c411399ffb49190b5c863f3237e9701aa86fa77815d7ea59df4b6e72f5",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0x938db1b5009f24cdb40282f7d265059fd8501482ba6bb8fb775b874022c083d1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::display::Display<0x000000000000000000000000000000000000000000000000000000000000107a::nft::Nft>"
                        },
                        "json": {
                          "id": "0x938db1b5009f24cdb40282f7d265059fd8501482ba6bb8fb775b874022c083d1",
                          "fields": {
                            "contents": [
                              {
                                "key": "name",
                                "value": "{immutable_metadata.name}"
                              },
                              {
                                "key": "image_url",
                                "value": "{immutable_metadata.uri}"
                              },
                              {
                                "key": "description",
                                "value": "{immutable_metadata.description}"
                              },
                              {
                                "key": "creator",
                                "value": "{immutable_metadata.issuer_name}"
                              },
                              {
                                "key": "version",
                                "value": "{immutable_metadata.version}"
                              },
                              {
                                "key": "media_type",
                                "value": "{immutable_metadata.media_type}"
                              },
                              {
                                "key": "collection_name",
                                "value": "{immutable_metadata.collection_name}"
                              },
                              {
                                "key": "immutable_issuer",
                                "value": "{immutable_issuer}"
                              }
                            ]
                          },
                          "version": 1
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0xb9de5e3384a317daee1d3f82506bb98b4c437d4b6258fa70c2943abc80fa4dff",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedIota"
                        },
                        "json": {
                          "id": "0xb9de5e3384a317daee1d3f82506bb98b4c437d4b6258fa70c2943abc80fa4dff",
                          "pool_id": "0xc9b7ce1abbfde8770d0dd2551ac0d388c76a4ff21c0e0eba854080f189dc4ebb",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "1500000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0x28f02a953f3553f51a9365593c7d4bd0643d2085f004b18c6ca9de51682b2c80"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                },
                {
                  "owner": {
                    "address": "0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "sFg1pHf1Yoqd9K9CP15YtMLU8hAhPU36eKGmk7Pw3E9"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "5FAz2JA6odzcE1cu489CLgzrhLocFR3x4K6C6UitstSB"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "HxvFVDme2xu6zPnpnRPpQJd4n2ABeyZHKYfEDA5CZPHP"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "Fh5g7WNPbWFZcE6Q1Jtgyvv7DLU1obHCcdtgfYeffazc"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "99rmPpLtYZHMLhR5feQwATN1jAFcgjuYcB8iNgXwwH2U"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "EeB9AW4zSnyB4wP4wYY21ivCVuxw3yqENvrFTsEywebm"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "ADRyanAPLoqDoro9BDx89MqRim3468dS69G2MgAUETCz"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "495Kwyn3f6hSV5Khc6mZ9BcpUxbXiWQKCEgG9Kmn7E6m"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000107a",
                    "digest": "9PodjT27h5puuBrku7A6eioN1ThGM6FWDT5wzeT83BKJ"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "digest": "H61aB9WnfioznJCFBYrjxK71SRbg3Kv8YZHZmEyhu7FT"
                  }
                },
                {
                  "address": "0x1dc43a801f3b30fb779bd47503a3c10d63633bcfe223a561d44d8f6b6f4edfe8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1dc43a801f3b30fb779bd47503a3c10d63633bcfe223a561d44d8f6b6f4edfe8",
                    "digest": "3xNuPZV9QuDYQEecYZCY9XCXfE1mgPMzGfVZ6mjyEw4v"
                  }
                },
                {
                  "address": "0x3e18371fd14fd50a737310ad7d46f0df700c574d740d4f3543e479921c39fe29",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3e18371fd14fd50a737310ad7d46f0df700c574d740d4f3543e479921c39fe29",
                    "digest": "DTQGijTEFZ1bLr422cjssssAAJ7AmeLUhxZbeY2EYG4s"
                  }
                },
                {
                  "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5a6383eb592bab4ff7c037a2118c514149ba9a86cf5a3b019c7034686365183f",
                    "digest": "8zbH5ogmJDiJ5F496CARkr7CngxJtwRL9fNJSTvNXC7X"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "FtwynMtuxAVQoXGupxNvSe6rfi32y42aXV8UrxcpFKqD"
                  }
                },
                {
                  "address": "0x786236d69253100dbb83238530c069614796e195f16097c59608a28a685a1e8c",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x786236d69253100dbb83238530c069614796e195f16097c59608a28a685a1e8c",
                    "digest": "B4EUvJNbi359tcHC4rYq87smKf1BKAjGvQh7JDtBXYRi"
                  }
                },
                {
                  "address": "0x7c9e49546cd2142c972f06f9c486abbacf2262e61a0c394389ff2f0545ccf087",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7c9e49546cd2142c972f06f9c486abbacf2262e61a0c394389ff2f0545ccf087",
                    "digest": "HcNDvS1dvBxS59oXiN39R7fVtByBrTPJLyKsmKoycdRy"
                  }
                },
                {
                  "address": "0x8ae1f957f276825012bb5a0f2197bf236de443e50bd37c4b9df7aec9da5f2e55",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x8ae1f957f276825012bb5a0f2197bf236de443e50bd37c4b9df7aec9da5f2e55",
                    "digest": "5xig8jfsttR9vXD8egEftfd53unofFQWZuxHRw9CdCyg"
                  }
                },
                {
                  "address": "0x8c3316c411399ffb49190b5c863f3237e9701aa86fa77815d7ea59df4b6e72f5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x8c3316c411399ffb49190b5c863f3237e9701aa86fa77815d7ea59df4b6e72f5",
                    "digest": "JDWYXRKJjZWJkqxqV7SUxuTDJW9ACMsnMC88AHFaB69z"
                  }
                },
                {
                  "address": "0x938db1b5009f24cdb40282f7d265059fd8501482ba6bb8fb775b874022c083d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x938db1b5009f24cdb40282f7d265059fd8501482ba6bb8fb775b874022c083d1",
                    "digest": "AjVTEwmErY9xnRA2VQ8RiYiFxagy6yP5wjFiypnXF1E6"
                  }
                },
                {
                  "address": "0xb9de5e3384a317daee1d3f82506bb98b4c437d4b6258fa70c2943abc80fa4dff",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb9de5e3384a317daee1d3f82506bb98b4c437d4b6258fa70c2943abc80fa4dff",
                    "digest": "3CJhQCSewmT8DWBAcnC4u6iTF4y5Y8dfRWVepQKRHkgQ"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "owLtYqnC2bar8fdBAVvprwpXyqAHifDfLzhA8wnH3zp"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 107:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 109-184:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "owLtYqnC2bar8fdBAVvprwpXyqAHifDfLzhA8wnH3zp"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "7uXNaHWi3mgndvU5ucJ5SompTEpJAgV9TKY8c6H5tH2R"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "83hbgTuUUsGBjrUDigjrfebf2U8Ue1gBFGL87mzYe2fK"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 188:
//# advance-epoch
Epoch advanced: 0

task 7, lines 190-277:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "7PLwaqn6pg198VkYmVKERZ2Qad3vDEWhfB7VRv5qDSc7",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 1,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "owLtYqnC2bar8fdBAVvprwpXyqAHifDfLzhA8wnH3zp"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "CGyGKFu385GVbKPD57rNrb1fPoLg1G3trazCFvfNWFXF"
                  }
                },
                {
                  "address": "0x4509fa198370254af0418248c9718bb206e810e1bce9fc8ffd0c500aef972f4d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x4509fa198370254af0418248c9718bb206e810e1bce9fc8ffd0c500aef972f4d",
                    "digest": "3eBwAXMbPYHRkTXRpQ4t8yeear6e3z8hPdUTAywcUgmy"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "AyeuDRQCcE7s4mYAYTaezYdusYYreW4LVKK2cvTAtsYv"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                },
                {
                  "address": "0xb82f4e12f31dada221b5f9d3ffd3f47c875a7a7286c11fcdaa71ab95bb2cbf6e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xb82f4e12f31dada221b5f9d3ffd3f47c875a7a7286c11fcdaa71ab95bb2cbf6e",
                    "digest": "H3rniney6Mi2U9JDoWbg1M2c97mq3pHMkUicCS9uxnE6"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "7PLwaqn6pg198VkYmVKERZ2Qad3vDEWhfB7VRv5qDSc7"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
