processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-26:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5783600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run test::m::mint_s --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 32:
//# transfer-object 2,0 --sender A --recipient B
Error: Transaction Effects Status: Invalid Transfer Object, object does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: Some(0) } }

task 5, lines 34-37:
//# view-object 2,0
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 6, line 39:
//# run test::m::mint_cup --type-args test::m::S --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2500400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 41:
//# view-object 6,0
Owner: Account Address ( A )
Version: 4
Contents: test::m::Cup<test::m::S> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(6,0),
        },
    },
}

task 8, line 43:
//# transfer-object 6,0 --sender A --recipient B
Error: Transaction Effects Status: Invalid Transfer Object, object does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: Some(0) } }

task 9, line 45:
//# view-object 6,0
Owner: Account Address ( A )
Version: 5
Contents: test::m::Cup<test::m::S> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(6,0),
        },
    },
}
