processed 20 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-78:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9659600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 80-80:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3442800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 82-82:
Owner: Account Address ( A )
Version: 2
Contents: test::m::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'view-object'. lines 84-84:
Owner: Account Address ( fake(2,0) )
Version: 2
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 5 'programmable'. lines 86-88:
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 3442800, non_refundable_storage_fee: 0

task 6 'run'. lines 90-90:
created: object(6,0), object(6,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3465600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 92-92:
Owner: Account Address ( fake(6,1) )
Version: 4
Contents: test::m::Cup<u64> {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}}

task 8 'view-object'. lines 94-94:
Owner: Account Address ( A )
Version: 4
Contents: test::m::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,1)}}}

task 9 'programmable'. lines 96-100:
mutated: object(0,0), object(6,1)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 3465600, non_refundable_storage_fee: 0

task 10 'run'. lines 102-102:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3442800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11 'view-object'. lines 104-104:
Owner: Account Address ( A )
Version: 6
Contents: test::m::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(10,0)}}}

task 12 'view-object'. lines 106-106:
Owner: Account Address ( fake(10,0) )
Version: 6
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(10,1)}}}

task 13 'programmable'. lines 108-110:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("transfer") }), indices: [], offsets: [] }), command: Some(1) } }

task 14 'programmable'. lines 112-118:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::receive. Use the public variant instead, iota::transfer::public_receive"), command: Some(1) } }

task 15 'run'. lines 120-120:
created: object(15,0), object(15,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3473200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16 'view-object'. lines 122-122:
Owner: Account Address ( A )
Version: 9
Contents: test::m::Parent {id: iota::object::UID {id: iota::object::ID {bytes: fake(15,0)}}}

task 17 'view-object'. lines 124-124:
Owner: Account Address ( fake(15,0) )
Version: 9
Contents: test::m::Store {id: iota::object::UID {id: iota::object::ID {bytes: fake(15,1)}}}

task 18 'programmable'. lines 126-130:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call iota::transfer::receive. Use the public variant instead, iota::transfer::public_receive"), command: Some(1) } }

task 19 'programmable'. lines 131-135:
mutated: object(0,0)
deleted: object(15,0), object(15,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 3473200, non_refundable_storage_fee: 0
