processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-26:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5905200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 28-28:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 30-30:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'transfer-object'. lines 32-32:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 5 'view-object'. lines 34-37:
Owner: Account Address ( B )
Version: 3
Contents: test::m::S {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 6 'run'. lines 39-39:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2500400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 41-41:
Owner: Account Address ( A )
Version: 4
Contents: test::m::Cup<test::m::S> {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}}

task 8 'transfer-object'. lines 43-43:
mutated: object(0,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2500400,  storage_rebate: 2500400, non_refundable_storage_fee: 0

task 9 'view-object'. lines 45-45:
Owner: Account Address ( B )
Version: 5
Contents: test::m::Cup<test::m::S> {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}}
