processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-11:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3176800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 14-14:
1,0::m

task 3 'transfer-object'. lines 16-16:
Error: Error checking transaction input objects: MovePackageAsObject { object_id: object(1,0) }

task 4 'view-object'. lines 18-18:
1,0::m
