processed 5 tasks

init:
A: object(0,0), B: object(0,1), C: object(0,2)

task 1 'programmable'. lines 9-10:
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 12-12:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(0,2)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 299999998012000u64}}

task 3 'transfer-object'. lines 14-14:
mutated: object(0,0), object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'view-object'. lines 16-16:
Owner: Account Address ( B )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(0,2)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 299999998012000u64}}
