processed 8 tasks

init:
A: object(0,0)

task 1, lines 9-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6224400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 42:
//# run a::m::mint --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 44:
//# view-object 2,0
Owner: Account Address ( A )
Version: 2
Contents: a::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 46:
//# run a::m::wrap --sender A --args object(2,0)
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2439600,  storage_rebate: 2196400, non_refundable_storage_fee: 0

task 5, line 48:
//# view-object 4,0
Owner: Account Address ( A )
Version: 3
Contents: a::m::T {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,0),
        },
    },
    s: a::m::S {
        id: iota::object::UID {
            id: iota::object::ID {
                bytes: fake(2,0),
            },
        },
    },
}

task 6, line 50:
//# run a::m::unwrap --sender A --args object(4,0)
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2196400,  storage_rebate: 2439600, non_refundable_storage_fee: 0

task 7, line 52:
//# view-object 2,0
Owner: Account Address ( A )
Version: 4
Contents: a::m::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}
