processed 6 tasks

task 1, lines 7-32:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6262400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 34:
//# run Test::f::create_and_test
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 36:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 3
Contents: Test::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V1{},
}

task 4, line 38:
//# run Test::f::update_inner --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2264800,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 5, line 40:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 4
Contents: Test::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V4{
        x: 42u64,
    },
}
