processed 3 tasks

init:
A: object(0,0)

task 1, lines 7-49:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 9522800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 51-53:
//# programmable --sender A --inputs 10 @A
//> 0: Test::f::create_iota(Gas, Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 988000, non_refundable_storage_fee: 0
