processed 10 tasks

init:
A: object(0,0)

task 1, lines 7-32:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7896400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 34:
//# run Test::f::create_and_test
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 36:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 2
Contents: Test::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V1{},
}

task 4, line 38:
//# run Test::f::update_inner --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2264800,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 5, line 40:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 3
Contents: Test::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V4{
        x: 42u64,
    },
}

task 6, lines 42-71:
//# upgrade --package Test --upgrade-capability 1,1 --sender A
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 8314400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 7, line 73:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 3
Contents: fake(1,0)::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: fake(1,0)::f::F::V4{
        x: 42u64,
    },
}

task 8, line 75:
//# run Test::f::update_inner2 --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 2264800, non_refundable_storage_fee: 0

task 9, line 77:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 4
Contents: fake(1,0)::f::S {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    data: fake(1,0)::f::F::V3{
        pos0: 42u64,
        pos1: 43u64,
    },
}
