processed 3 tasks

task 1, lines 7-16:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 4628400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 18:
//# run Test::f::test
mutated: object(0,0)
gas summary: computation_cost: 1000000, computation_cost_burned: 1000000, storage_cost: 980400,  storage_rebate: 980400, non_refundable_storage_fee: 0
