processed 6 tasks

task 1, lines 7-32:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6756400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 34:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 36-39:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::send_back(Input(0), Input(1))
// Duplicate object ref in input
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 3420000, non_refundable_storage_fee: 0

task 4, lines 40-43:
//# programmable --inputs object(2,0) receiving(2,1) receiving(2,1)
//> tto::M1::send_back(Input(0), Input(1))
// Invalid signature for the receiving object since we try to use it as a normal input
Error: Error checking transaction input objects: DuplicateObjectRefInput

task 5, lines 44-45:
//# programmable --inputs object(2,1) receiving(2,1)
//> tto::M1::send_back(Input(0), Input(1))
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,1) is owned by account address object(2,0), but given owner/signer address is 0x8cca4e1ce0ba5904cea61df9242da2f7d29e3ef328fb7ec07c086b3bf47ca61a" }
