processed 14 tasks

task 1 'publish'. lines 7-64:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10579200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 66-66:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 68-68:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'view-object'. lines 70-70:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 5 'view-object'. lines 72-72:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}}

task 6 'view-object'. lines 74-74:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::C {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}}

task 7 'view-object'. lines 76-78:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::C {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,4)}}}

task 8 'programmable'. lines 79-82:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 9 'programmable'. lines 83-87:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 10 'programmable'. lines 88-93:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 11 'programmable'. lines 94-98:
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::transfer::receive_impl (function index 12) at offset 0, Abort Code: 2
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 2), source: Some(VMError { major_status: ABORTED, sub_status: Some(2), message: None, exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(1) } }

task 12 'programmable'. lines 99-101:
Error: Transaction Effects Status: Invalid command argument at 4. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 4, kind: TypeMismatch }, source: None, command: Some(1) } }

task 13 'programmable'. lines 103-106:
Error: Transaction Effects Status: Invalid command argument at 4. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 4, kind: TypeMismatch }, source: None, command: Some(2) } }
