processed 6 tasks

task 1, lines 7-33:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7174400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 35:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 37:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, lines 39-41:
//# view-object 2,1
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5, lines 42-44:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::pass_through(Input(1));
//> tto::M1::receiver(Input(0), Input(1));
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 3420000, non_refundable_storage_fee: 0
