processed 13 tasks

task 1, lines 7-51:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8937600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 53:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 55:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, lines 57-60:
//# view-object 2,1
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5, lines 61-63:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through(Input(1));
//> tto::M1::receiver(Input(0), Result(0));
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 3420000, non_refundable_storage_fee: 0

task 6, lines 65-67:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_a(Input(1));
//> tto::M1::receiver(Input(0), Result(0));
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 7, lines 69-71:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_mut_ref_a(Input(1));
//> tto::M1::receiver(Input(0), Input(1));
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 8, lines 73-77:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_ref_a(Input(1));
//> tto::M1::receiver(Input(0), Input(1));
// make vec, then unpack it and make sure the type is fixed
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 9, lines 78-80:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<iota::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_b(Result(0));
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 10, lines 82-87:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<iota::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_a(Result(0));
//> 2: tto::M1::receiver(Input(0), Result(1));
// This is fine since we are going A -> A in the unpack. But we should fail the call.
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(2) } }

task 11, lines 88-93:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<iota::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_generic<tto::M1::A>(Result(0));
//> 2: tto::M1::receiver(Input(0), Result(1));
// This should fail since we're going A -> B in the unpack.
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(2) } }

task 12, lines 94-96:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<iota::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_generic<tto::M1::B>(Result(0));
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }
