processed 11 tasks

init:
A: object(0,0)

task 1, lines 7-37:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7835600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 39:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3541600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 41:
//# view-object 2,0
Owner: Account Address ( fake(2,1) )
Version: 3
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 4, line 43:
//# view-object 2,1
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5, line 45:
//# run tto::M1::receive --args object(2,1) receiving(2,0)
created: object(5,0), object(5,1), object(5,2)
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9728000,  storage_rebate: 3541600, non_refundable_storage_fee: 0

task 6, line 47:
//# view-object 2,0
Owner: Object ID: ( fake(5,1) )
Version: 4
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 100u64,
}

task 7, line 49:
//# view-object 2,1
Owner: Account Address ( _ )
Version: 4
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 8, line 51:
//# view-object 5,0
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,0),
        },
    },
    name: iota::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: iota::object::ID {
        bytes: fake(5,2),
    },
}

task 9, line 53:
//# view-object 5,1
Owner: Object ID: ( fake(2,1) )
Version: 4
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,1),
        },
    },
    name: iota::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: iota::object::ID {
        bytes: fake(2,0),
    },
}

task 10, line 55:
//# view-object 5,2
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: tto::M1::A {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,2),
        },
    },
    value: 100u64,
}
