processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-29:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5996400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 33-33:
Owner: Object ID: ( fake(2,2) )
Version: 2
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,1)}}

task 4 'view-object'. lines 35-35:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'view-object'. lines 37-39:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 6 'run'. lines 40-42:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,1), parent_id: object(2,0) }

task 7 'run'. lines 43-43:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,0), parent_id: object(2,2) }
