processed 9 tasks

task 1 'publish'. lines 7-45:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8071200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 47-47:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4636000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 49-49:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'view-object'. lines 51-51:
Owner: Account Address ( fake(2,2) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 5 'view-object'. lines 53-55:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}}

task 6 'programmable'. lines 56-59:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 7 'programmable'. lines 60-64:
Error: Error checking transaction input objects: DuplicateObjectRefInput

task 8 'programmable'. lines 65-68:
mutated: object(0,0), object(2,0), object(2,1), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 4636000,  storage_rebate: 4636000, non_refundable_storage_fee: 0
