processed 22 tasks

task 1 'publish'. lines 7-78:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 11286000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 80-80:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 82-82:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 4 'view-object'. lines 84-84:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 5 'view-object'. lines 86-86:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}}

task 6 'view-object'. lines 88-88:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}}

task 7 'view-object'. lines 90-92:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,4)}}}

task 8 'programmable'. lines 93-96:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 9 'programmable'. lines 97-101:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2204000,  storage_rebate: 2204000, non_refundable_storage_fee: 0

task 10 'programmable'. lines 102-106:
mutated: object(0,0), object(2,0), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 5852000,  storage_rebate: 5852000, non_refundable_storage_fee: 0

task 11 'programmable'. lines 107-112:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 12 'programmable'. lines 113-118:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 13 'programmable'. lines 119-124:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 14 'programmable'. lines 125-130:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 15 'programmable'. lines 131-136:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 16 'programmable'. lines 137-139:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 7068000,  storage_rebate: 7068000, non_refundable_storage_fee: 0

task 17 'view-object'. lines 141-141:
Owner: Account Address ( _ )
Version: 12
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}

task 18 'view-object'. lines 143-143:
Owner: Account Address ( _ )
Version: 12
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 19 'view-object'. lines 145-145:
Owner: Account Address ( _ )
Version: 12
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,2)}}}

task 20 'view-object'. lines 147-147:
Owner: Account Address ( _ )
Version: 12
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,3)}}}

task 21 'view-object'. lines 149-149:
Owner: Account Address ( _ )
Version: 12
Contents: tto::M1::B {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,4)}}}
