processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-37:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7835600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 39-39:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3541600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 41-41:
Owner: Account Address ( fake(2,1) )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 4 'view-object'. lines 43-43:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'run'. lines 45-45:
created: object(5,0), object(5,1), object(5,2)
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9728000,  storage_rebate: 3541600, non_refundable_storage_fee: 0

task 6 'view-object'. lines 47-47:
Owner: Object ID: ( fake(5,1) )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, value: 100u64}

task 7 'view-object'. lines 49-49:
Owner: Account Address ( _ )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 8 'view-object'. lines 51-51:
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,0)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(5,2)}}

task 9 'view-object'. lines 53-53:
Owner: Object ID: ( fake(2,1) )
Version: 4
Contents: iota::dynamic_field::Field<iota::dynamic_object_field::Wrapper<u64>, iota::object::ID> {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,1)}}, name: iota::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: iota::object::ID {bytes: fake(2,0)}}

task 10 'view-object'. lines 55-55:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: tto::M1::A {id: iota::object::UID {id: iota::object::ID {bytes: fake(5,2)}}, value: 100u64}
