processed 3 tasks

task 1, lines 7-25:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5844400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 27:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3397200,  storage_rebate: 980400, non_refundable_storage_fee: 0
