processed 10 tasks

task 1, lines 9-19:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::t. Invalid call to 'iota::event::emit' with an event type 'iota::coin::CurrencyCreated<u64>'. The event's type must be defined in the current module"), command: Some(0) } }

task 2, lines 21-30:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::t. Invalid call to 'iota::event::emit' with an event type 'T0'. The event's type must be defined in the current module"), command: Some(0) } }

task 3, lines 32-41:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::t. Invalid call to 'iota::event::emit' with an event type 'u64'. The event's type must be defined in the current module"), command: Some(0) } }

task 4, lines 43-56:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::t. Invalid call to 'iota::event::emit' with an event type 'vector<_::m::X>'. The event's type must be defined in the current module"), command: Some(0) } }

task 5, lines 58-71:
//# publish
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::t. Invalid call to 'iota::event::emit' with an event type 'vector<_::m::X>'. The event's type must be defined in the current module"), command: Some(0) } }

task 6, lines 73-82:
//# publish
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3990000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, lines 86-96:
//# publish --dependencies test
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::t::t. Invalid call to 'iota::event::emit' with an event type 'test::m::X'. The event's type must be defined in the current module"), command: Some(0) } }

task 9, lines 98-108:
//# publish --dependencies test
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::t::t. Invalid call to 'iota::event::emit' with an event type 'test::m::Y'. The event's type must be defined in the current module"), command: Some(0) } }
