processed 4 tasks

task 0 'publish'. lines 8-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4689200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 25-40:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4377600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 2 'publish'. lines 42-57:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4370000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'publish'. lines 59-77:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4826000,  storage_rebate: 988000, non_refundable_storage_fee: 0
