processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-30:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# create-checkpoint
Checkpoint created: 1

task 3, line 34:
//# run Test::M1::create --args 0 @B --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 36:
//# run Test::M1::create --args 1 @B --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 38:
//# run Test::M1::create --args 2 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 40:
//# run Test::M1::create --args 3 @A --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 42:
//# run Test::M1::create --args 4 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 44:
//# create-checkpoint
Checkpoint created: 2

task 9, line 46:
//# run Test::M1::create --args 100 @B --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 48:
//# run Test::M1::create --args 101 @A --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11, line 50:
//# run Test::M1::create --args 102 @B --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12, line 52:
//# run Test::M1::create --args 103 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 13, line 54:
//# run Test::M1::create --args 104 @B --sender A
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 14, line 56:
//# create-checkpoint
Checkpoint created: 3

task 15, lines 58-80:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "GmBEWseRb1joXnVDikehNNmdjyjQayjpsRnyaxeMur6X",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "9pNF8sfuEAqXyu1xQXEVuu3DkFYpjpx9sedsdma552cU",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
          "node": {
            "digest": "CPFzvNqckYD7wL4GBBR5qhe7rqmfbmrg1uSktB9vSQUe",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
          "node": {
            "digest": "7tsArK1HH2TXCedEEHXqieqivF4E4d1iN4Y77BdPVKS2",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "D99Ery5N7Ux82hfqH9qBt3xCfek73pxoNGyAeFFsKLpt",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 16, lines 83-107:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false,
        "startCursor": "eyJjIjozLCJ0IjoxMCwiaSI6dHJ1ZX0",
        "endCursor": "eyJjIjozLCJ0IjoxMSwiaSI6dHJ1ZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjozLCJ0IjoxMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "D99Ery5N7Ux82hfqH9qBt3xCfek73pxoNGyAeFFsKLpt",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 17, lines 109-133:
//# run-graphql --cursors {"c":4,"t":10,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0Ijo5LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0Ijo5LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0Ijo5LCJpIjpmYWxzZX0",
          "node": {
            "digest": "7tsArK1HH2TXCedEEHXqieqivF4E4d1iN4Y77BdPVKS2",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 18, lines 135-159:
//# run-graphql --cursors {"c":4,"t":9,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0Ijo2LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0Ijo4LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0Ijo3LCJpIjpmYWxzZX0",
          "node": {
            "digest": "CPFzvNqckYD7wL4GBBR5qhe7rqmfbmrg1uSktB9vSQUe",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 19, lines 161-185:
//# run-graphql --cursors {"c":4,"t":6,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0Ijo0LCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0Ijo1LCJpIjp0cnVlfQ"
      },
      "edges": []
    }
  }
}

task 20, lines 187-210:
//# run-graphql --cursors {"c":4,"t":4,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "eyJjIjo0LCJ0IjoyLCJpIjp0cnVlfQ",
        "endCursor": "eyJjIjo0LCJ0IjozLCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "GmBEWseRb1joXnVDikehNNmdjyjQayjpsRnyaxeMur6X",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "9pNF8sfuEAqXyu1xQXEVuu3DkFYpjpx9sedsdma552cU",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 21, lines 213-236:
//# run-graphql --cursors {"c":4,"t":2,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false,
        "startCursor": null,
        "endCursor": null
      },
      "edges": []
    }
  }
}
