processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-21:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7668400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 22-36:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7683600,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3 'upgrade'. lines 37-61:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 8907200,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4 'upgrade'. lines 62-84:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 9834400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 5 'run'. lines 86-86:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6 'run'. lines 88-88:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2432000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 90-90:
Owner: Account Address ( A )
Version: 3
Contents: V0::base_module::Object {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}, field0: 10u64, field1: 10u64}
