processed 9 tasks

init:
A: object(0,0)

task 1, lines 7-57:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 11308800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 58-109:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A --policy dep_only
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }

task 3, lines 110-161:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A --policy additive
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }

task 4, lines 162-212:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A --policy additive
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 11308800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 5, lines 213-265:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A --policy dep_only
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }

task 6, lines 266-318:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A --policy additive
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 12084000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 7, lines 319-371:
//# upgrade --package V2 --upgrade-capability 1,1 --sender A --policy dep_only
created: object(7,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 12084000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 8, lines 372-422:
//# upgrade --package V3 --upgrade-capability 1,1 --sender A --policy additive
created: object(8,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 12084000,  storage_rebate: 2622000, non_refundable_storage_fee: 0
