processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-13:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6216800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 15-25:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6520800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3 'publish'. lines 27-33:
created: object(3,0), object(3,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6201600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'upgrade'. lines 35-42:
created: object(4,0)
mutated: object(0,0), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2622000, non_refundable_storage_fee: 0
