processed 10 tasks

init:
A: object(0,0)

task 1, lines 7-10:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5038800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 12-15:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5054000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3, lines 17-20:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4, lines 22-25:
//# upgrade --package V2 --upgrade-capability 1,1 --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 5, lines 27-30:
//# upgrade --package V3 --upgrade-capability 1,1 --sender A
created: object(5,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6, lines 32-34:
//# upgrade --package V4 --upgrade-capability 1,1 --sender A
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 4856400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 7, lines 36-39:
//# upgrade --package V5 --upgrade-capability 1,1 --sender A
created: object(7,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 8, lines 41-44:
//# upgrade --package V6 --upgrade-capability 1,1 --sender A
created: object(8,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 9, lines 46-49:
//# upgrade --package V7 --upgrade-capability 1,1 --sender A
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }
