processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-10:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5038800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 12-15:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5054000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3 'upgrade'. lines 17-20:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4 'upgrade'. lines 22-25:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 5 'upgrade'. lines 27-30:
created: object(5,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6 'upgrade'. lines 32-34:
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 4856400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 7 'upgrade'. lines 36-39:
created: object(7,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 8 'upgrade'. lines 41-44:
created: object(8,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 9 'upgrade'. lines 46-49:
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }
