processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-17:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8557600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 19-34:
//# upgrade --package A0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7691200,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3, line 36:
//# run A1::m::test --type-args A0::m::A --args object(1,0) --sender A
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2812000,  storage_rebate: 2812000, non_refundable_storage_fee: 0

task 4, line 38:
//# run A1::m::test --type-args A1::m::B --args object(1,0) --sender A
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2812000,  storage_rebate: 2812000, non_refundable_storage_fee: 0
