processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-17:
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8557600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 19-34:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7691200,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3 'run'. lines 36-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2812000,  storage_rebate: 2812000, non_refundable_storage_fee: 0

task 4 'run'. lines 38-38:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2812000,  storage_rebate: 2812000, non_refundable_storage_fee: 0
