processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-13:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6216800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 16-22:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6216800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3 'upgrade'. lines 24-34:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6520800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4 'publish'. lines 37-43:
created: object(4,0), object(4,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6201600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'upgrade'. lines 45-51:
created: object(5,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 6201600,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6 'upgrade'. lines 53-60:
created: object(6,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2622000, non_refundable_storage_fee: 0
