processed 7 tasks

init:
A: object(0,0)

task 1, lines 7-13:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6216800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-22:
//# upgrade --package Test_DepV1 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6216800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3, lines 24-34:
//# upgrade --package Test_DepV2 --upgrade-capability 1,1 --sender A
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6520800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4, lines 37-43:
//# publish --upgradeable --dependencies Test_DepV1 --sender A
created: object(4,0), object(4,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6201600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 45-51:
//# upgrade --package Test_V1 --upgrade-capability 4,1 --dependencies Test_DepV2 --sender A
created: object(5,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 6201600,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6, lines 53-60:
//# upgrade --package Test_V2 --upgrade-capability 4,1 --dependencies Test_DepV3 --sender A
created: object(6,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2622000, non_refundable_storage_fee: 0
