processed 20 tasks

init:
A: object(0,0)

task 1, lines 7-17:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6581600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 19-31:
//# upgrade --package A0 --upgrade-capability 1,0 --sender A
created: object(2,0)
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 7280800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3, lines 33-63:
//# upgrade --package A1 --upgrade-capability 1,0 --sender A
created: object(3,0)
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 9902800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4, line 65:
//# run A2::m::canary --type-args A0::m::A --args true --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, line 67:
//# run A2::m::canary --type-args A1::m::B --args true --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, line 69:
//# run A2::m::canary --type-args A0::m::A --args false --sender A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 71:
//# run A2::m::canary --type-args A1::m::B --args false --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 8, line 73:
//# run A2::m::canary --type-args A0::m::EA --args true --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9, line 75:
//# run A2::m::canary --type-args A1::m::EB --args true --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 77:
//# run A2::m::canary --type-args A0::m::EA --args false --sender A
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11, line 79:
//# run A2::m::canary --type-args A1::m::EB --args false --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2728400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12, line 81:
//# view-object 4,0
Owner: Account Address ( A )
Version: 5
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 13, line 83:
//# view-object 5,0
Owner: Account Address ( A )
Version: 6
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(5,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 14, line 85:
//# view-object 6,0
Owner: Account Address ( A )
Version: 7
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(6,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 15, line 87:
//# view-object 7,0
Owner: Account Address ( A )
Version: 8
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(7,0),
        },
    },
    addr: vector[
        98u8,
        98u8,
        98u8,
        56u8,
        49u8,
        52u8,
        50u8,
        48u8,
        55u8,
        54u8,
        48u8,
        57u8,
        49u8,
        55u8,
        54u8,
        57u8,
        54u8,
        100u8,
        52u8,
        54u8,
        100u8,
        55u8,
        51u8,
        49u8,
        57u8,
        99u8,
        97u8,
        48u8,
        53u8,
        56u8,
        102u8,
        102u8,
        50u8,
        51u8,
        101u8,
        49u8,
        51u8,
        57u8,
        56u8,
        100u8,
        53u8,
        56u8,
        49u8,
        50u8,
        57u8,
        56u8,
        101u8,
        56u8,
        51u8,
        97u8,
        97u8,
        102u8,
        98u8,
        99u8,
        102u8,
        97u8,
        48u8,
        102u8,
        100u8,
        98u8,
        100u8,
        54u8,
        101u8,
        55u8,
    ],
}

task 16, line 89:
//# view-object 8,0
Owner: Account Address ( A )
Version: 9
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(8,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 17, line 91:
//# view-object 9,0
Owner: Account Address ( A )
Version: 10
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(9,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 18, line 93:
//# view-object 10,0
Owner: Account Address ( A )
Version: 11
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(10,0),
        },
    },
    addr: vector[
        101u8,
        102u8,
        54u8,
        98u8,
        51u8,
        97u8,
        56u8,
        51u8,
        97u8,
        97u8,
        56u8,
        102u8,
        53u8,
        53u8,
        99u8,
        55u8,
        49u8,
        52u8,
        101u8,
        101u8,
        53u8,
        99u8,
        102u8,
        56u8,
        56u8,
        100u8,
        102u8,
        52u8,
        100u8,
        99u8,
        48u8,
        53u8,
        49u8,
        100u8,
        102u8,
        98u8,
        53u8,
        97u8,
        49u8,
        98u8,
        102u8,
        51u8,
        97u8,
        55u8,
        99u8,
        102u8,
        101u8,
        98u8,
        50u8,
        49u8,
        98u8,
        53u8,
        51u8,
        48u8,
        57u8,
        48u8,
        54u8,
        97u8,
        53u8,
        101u8,
        54u8,
        49u8,
        48u8,
        52u8,
    ],
}

task 19, line 95:
//# view-object 11,0
Owner: Account Address ( A )
Version: 12
Contents: A0::m::Canary {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(11,0),
        },
    },
    addr: vector[
        98u8,
        98u8,
        98u8,
        56u8,
        49u8,
        52u8,
        50u8,
        48u8,
        55u8,
        54u8,
        48u8,
        57u8,
        49u8,
        55u8,
        54u8,
        57u8,
        54u8,
        100u8,
        52u8,
        54u8,
        100u8,
        55u8,
        51u8,
        49u8,
        57u8,
        99u8,
        97u8,
        48u8,
        53u8,
        56u8,
        102u8,
        102u8,
        50u8,
        51u8,
        101u8,
        49u8,
        51u8,
        57u8,
        56u8,
        100u8,
        53u8,
        56u8,
        49u8,
        50u8,
        57u8,
        56u8,
        101u8,
        56u8,
        51u8,
        97u8,
        97u8,
        102u8,
        98u8,
        99u8,
        102u8,
        97u8,
        48u8,
        102u8,
        100u8,
        98u8,
        100u8,
        54u8,
        101u8,
        55u8,
    ],
}
