processed 15 tasks

init:
A: object(0,0)

task 1, lines 7-13:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5646800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 14-17:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5016000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 3, lines 19-21:
//# run iota::package::only_additive_upgrades --args object(1,1) --sender A
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 4, lines 22-27:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A --policy compatible
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::package::authorize_upgrade (function index 21) at offset 24, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("package") }, function: 21, instruction: 24, function_name: Some("authorize_upgrade") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: Some("iota::package::authorize_upgrade at offset 24"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("package") }), indices: [], offsets: [(FunctionDefinitionIndex(21), 24)] }), command: Some(0) } }

task 5, lines 28-33:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A --policy additive
created: object(5,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5016000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6, lines 34-37:
//# upgrade --package V2 --upgrade-capability 1,1 --sender A --policy dep_only
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5016000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 7, lines 39-41:
//# run iota::package::only_dep_upgrades --args object(1,1) --sender A
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 8, lines 42-47:
//# upgrade --package V3 --upgrade-capability 1,1 --sender A --policy compatible
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::package::authorize_upgrade (function index 21) at offset 24, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("package") }, function: 21, instruction: 24, function_name: Some("authorize_upgrade") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: Some("iota::package::authorize_upgrade at offset 24"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("package") }), indices: [], offsets: [(FunctionDefinitionIndex(21), 24)] }), command: Some(0) } }

task 9, lines 48-53:
//# upgrade --package V3 --upgrade-capability 1,1 --sender A --policy additive
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::package::authorize_upgrade (function index 21) at offset 24, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("package") }, function: 21, instruction: 24, function_name: Some("authorize_upgrade") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: Some("iota::package::authorize_upgrade at offset 24"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("package") }), indices: [], offsets: [(FunctionDefinitionIndex(21), 24)] }), command: Some(0) } }

task 10, lines 54-59:
//# upgrade --package V3 --upgrade-capability 1,1 --sender A --policy dep_only
created: object(10,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5016000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 11, lines 60-62:
//# run iota::package::only_additive_upgrades --args object(1,1) --sender A
Error: Transaction Effects Status: Move Runtime Abort. Location: iota::package::restrict (function index 23) at offset 10, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: iota, name: Identifier("package") }, function: 23, instruction: 10, function_name: Some("restrict") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: Some("iota::package::restrict at offset 10"), exec_state: None, location: Module(ModuleId { address: iota, name: Identifier("package") }), indices: [], offsets: [(FunctionDefinitionIndex(23), 10)] }), command: Some(0) } }

task 12, line 63:
//# run iota::package::make_immutable --args object(1,1) --sender A
mutated: object(0,0)
deleted: object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 13, lines 65-67:
//# view-object 1,1
No object at id 1,1

task 14, lines 68-71:
//# upgrade --package V4 --upgrade-capability 1,1 --sender A --policy dep_only
Error: INVALID TEST. Could not load object argument object(1,1)
