processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-26:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6665200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 27-30:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3260400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 32-32:
Owner: Account Address ( _ )
Version: 2
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 4 'view-object'. lines 34-36:
Owner: Account Address ( A )
Version: 2
Contents: test::m1::CoolMarker {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,1)}}}

task 5 'programmable'. lines 37-42:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 1, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 1, secondary_idx: 0 }, source: None, command: None } }

task 6 'programmable'. lines 43-48:
created: object(6,0), object(6,1), object(6,2), object(6,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5532800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7 'view-object'. lines 50-50:
Owner: Account Address ( _ )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 8 'view-object'. lines 52-52:
Owner: Account Address ( _ )
Version: 4
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,1)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 100u64}}

task 9 'view-object'. lines 54-54:
Owner: Account Address ( A )
Version: 4
Contents: test::m1::CoolMarker {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,2)}}}

task 10 'view-object'. lines 56-56:
Owner: Account Address ( A )
Version: 4
Contents: test::m1::CoolMarker {id: iota::object::UID {id: iota::object::ID {bytes: fake(6,3)}}}
