processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-30:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6034400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# run t2::o2::create
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 34:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, lines 36-38:
//# programmable --sender A --inputs object(2,0)
//> 0: MakeMoveVec<t2::o2::Obj2>([Input(0)]);
//> t2::o2::consume(Result(0))
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 1238800, non_refundable_storage_fee: 0
