processed 5 tasks

init:
A: object(0,0)

task 1, lines 9-18:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4826000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 20:
//# run test::m1::mint_shared
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 22:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 4, lines 24-25:
//# programmable --sender A --inputs object(2,0)
//> MergeCoins(Gas, [Input(0)])
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0
