processed 5 tasks

init:
A: object(0,0)

task 1, lines 9-27:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5198400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run test::m1::mint_shared
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 31:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: test::m1::Coin {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 1000000u64,
}

task 4, lines 33-34:
//# programmable --sender A --inputs object(2,0)
//> MergeCoins(Gas, [Input(0)])
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Debug of error: CommandArgumentError { arg_idx: 1, kind: TypeMismatch } at command Some(0)
