processed 11 tasks

init:
A: object(0,0)

task 3 'programmable'. lines 29-34:
created: object(3,0), object(3,1), object(3,2), object(3,3), object(3,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'view-object'. lines 36-36:
3,3::m

task 5 'view-object'. lines 38-38:
3,4::{m, n}

task 8 'programmable'. lines 44-46:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9 'publish'. lines 48-53:
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5221200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 10 'run'. lines 55-55:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0
