processed 4 tasks

task 1 'publish'. lines 7-24:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6224400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 26-30:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2249600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'view-object'. lines 32-32:
Owner: Account Address ( _ )
Version: 3
Contents: test::m1::Witness {id: iota::object::UID {id: iota::object::ID {bytes: fake(2,0)}}}
