processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-19:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5008400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 21-23:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 25-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5 'view-object'. lines 31-33:
Owner: Shared
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {id: iota::object::UID {id: iota::object::ID {bytes: fake(4,0)}}, balance: iota::balance::Balance<iota::iota::IOTA> {value: 0u64}}

task 6 'programmable'. lines 34-38:
created: object(6,0)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 7 'programmable'. lines 39-42:
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
