processed 8 tasks

init:
A: object(0,0)

task 1, lines 7-19:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5008400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-23:
//# programmable --sender A --inputs 10
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: iota::transfer::public_share_object<iota::coin::Coin<iota::iota::IOTA>>(Result(0));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 25-27:
//# programmable --sender A --inputs 10
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: p::m::sharer<iota::coin::Coin<iota::iota::IOTA>>(Result(0));
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, line 29:
//# run p::m::mint_shared
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 31-33:
//# view-object 4,0
Owner: Shared( 3 )
Version: 3
Contents: iota::coin::Coin<iota::iota::IOTA> {
    id: iota::object::UID {
        id: iota::object::ID {
            bytes: fake(4,0),
        },
    },
    balance: iota::balance::Balance<iota::iota::IOTA> {
        value: 0u64,
    },
}

task 6, lines 34-38:
//# programmable --sender A --inputs 0 object(4,0) @A
//> 0: SplitCoins(Input(1), [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(2));
// This is not OK -- split off from a shared object and transfer shared object
created: object(6,0)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 7, lines 39-42:
//# programmable --sender A --inputs 0 object(4,0) @A
//> 0: SplitCoins(Input(1), [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(2));
//> 2: TransferObjects([Input(1)], Input(2));
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
