processed 11 tasks

init:
A: object(0,0)

task 1, lines 9-19:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4354800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-24:
//# publish --upgradeable --sender A
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5076800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 26-29:
//# publish
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3442800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 37-42:
//# programmable --sender A --inputs 10 @A object(2,0) 0u8 digest(q_2)
//> 0: iota::package::authorize_upgrade(Input(2), Input(3), Input(4));
//> 1: SplitCoins(Gas, [Input(0)]);
//> 2: Upgrade(q_2, [iota,std,r], q, Result(0));
//> TransferObjects([Result(1)], Input(1));
//> iota::package::commit_upgrade(Input(2), Result(2))
created: object(5,0), object(5,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 7052800,  storage_rebate: 2622000, non_refundable_storage_fee: 0

task 6, lines 44-46:
//# programmable --sender A
//> 0: q::m::x();
//> p::m::foo(Result(0))
Error: Transaction Effects Status: Move Runtime Abort. Location: p::n::bar (function index 0) at offset 6, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: p, name: Identifier("n") }, function: 0, instruction: 6, function_name: Some("bar") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: Some("p::n::bar at offset 6"), exec_state: None, location: Module(ModuleId { address: p, name: Identifier("n") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 6)] }), command: Some(1) } }

task 8, lines 50-52:
//# programmable --sender A
//> 0: q_2::m::x();
//> p::m::foo(Result(0))
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9, lines 54-59:
//# publish --dependencies p q_2 r
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5768400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 10, line 61:
//# run s::all::foo_x
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 988000, non_refundable_storage_fee: 0
