name: Deploy for Explorer

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.EXPLORER_VERCEL_PROJECT_ID }}
  EXPLORER_VERCEL_PROJECT_STAGING_URL: ${{ secrets.EXPLORER_VERCEL_PROJECT_STAGING_URL }}

on:
  workflow_dispatch:
    inputs:
      isProd:
        type: boolean
        required: true
      isStaging:
        type: boolean
        required: true
  workflow_call:
    inputs:
      isProd:
        type: boolean
        required: true
      isStaging:
        type: boolean
        required: true

jobs:
  deploy:
    permissions:
      contents: read
      pull-requests: write
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4
      - name: Install Nodejs
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # pin@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Prod Flag
        id: setup_prod_flags
        run: |
          if [[ "${{ inputs.isProd }}" = "true" ]]; then
            echo "PROD_FLAG=--prod" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
            echo "VERCEL_OUTPUT=" >> $GITHUB_OUTPUT
          else
            echo "PROD_FLAG=" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=preview" >> $GITHUB_OUTPUT
            echo "VERCEL_OUTPUT=> vercel_output.txt" >> $GITHUB_OUTPUT
          fi
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # pin@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-
      - name: Install Vercel CLI
        run: pnpm add --global vercel@canary
      - name: Pull Vercel Env variables (network configs)
        run: vercel pull --yes --environment=${{steps.setup_prod_flags.outputs.ENVIRONMENT}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Copy the .env file
        run: cp ./.vercel/.env.${{steps.setup_prod_flags.outputs.ENVIRONMENT}}.local ./sdk/.env
      - name: Build Explorer
        run: pnpm explorer build
      - name: Build Vercel Project Artifacts
        run: vercel build ${{steps.setup_prod_flags.outputs.PROD_FLAG}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy ${{steps.setup_prod_flags.outputs.PROD_FLAG}} --prebuilt --token=${{ secrets.VERCEL_TOKEN }} ${{ steps.setup_prod_flags.outputs.VERCEL_OUTPUT }}
      - name: Extract Deploy URL
        id: deploy_url
        if: ${{ inputs.isProd == false }}
        run: echo "DEPLOY_URL=$(cat vercel_output.txt | awk 'END{print}')" >> $GITHUB_OUTPUT
      - name: Alias Staging deploy
        if: ${{ inputs.isStaging }}
        run: vercel alias ${{ steps.deploy_url.outputs.DEPLOY_URL }} $EXPLORER_VERCEL_PROJECT_STAGING_URL --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_SCOPE }}
      - name: Comment on pull request
        if: ${{ inputs.isProd == false && inputs.isStaging == false }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const DEPLOY_URL = '${{ steps.deploy_url.outputs.DEPLOY_URL }}'
            const COMMIT_SHA = '${{ github.event.pull_request.head.sha }}'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This pull request has been deployed to Vercel.\n\n\nLatest commit: ${COMMIT_SHA}\n\n:white_check_mark: Preview: ${DEPLOY_URL}`
            })
