processed 16 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-55:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5), object(1,6), object(1,7), object(1,8), object(1,9), object(1,10)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 33082800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 57-57:
1,0::{first_coin, second_coin}

task 3 'view-object'. lines 59-59:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::first_coin::FIRST_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,1)}}, balance: iota::balance::Balance<test::first_coin::FIRST_COIN> {value: 10000u64}}

task 4 'view-object'. lines 61-61:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::Coin<test::second_coin::SECOND_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,2)}}, balance: iota::balance::Balance<test::second_coin::SECOND_COIN> {value: 10000u64}}

task 5 'view-object'. lines 63-63:
Owner: Immutable
Version: 2
Contents: iota::coin::CoinMetadata<test::first_coin::FIRST_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,3)}}, decimals: 9u8, name: std::string::String {bytes: vector[82u8, 69u8, 71u8, 85u8, 76u8, 65u8, 84u8, 69u8, 68u8, 95u8, 67u8, 79u8, 73u8, 78u8]}, symbol: std::ascii::String {bytes: vector[82u8, 67u8]}, description: std::string::String {bytes: vector[65u8, 32u8, 110u8, 101u8, 119u8, 32u8, 114u8, 101u8, 103u8, 117u8, 108u8, 97u8, 116u8, 101u8, 100u8, 32u8, 99u8, 111u8, 105u8, 110u8]}, icon_url: std::option::Option<iota::url::Url> {vec: vector[]}}

task 6 'view-object'. lines 65-65:
Owner: Immutable
Version: 2
Contents: iota::coin::CoinMetadata<test::second_coin::SECOND_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,4)}}, decimals: 9u8, name: std::string::String {bytes: vector[82u8, 69u8, 71u8, 85u8, 76u8, 65u8, 84u8, 69u8, 68u8, 95u8, 67u8, 79u8, 73u8, 78u8]}, symbol: std::ascii::String {bytes: vector[82u8, 67u8]}, description: std::string::String {bytes: vector[65u8, 32u8, 110u8, 101u8, 119u8, 32u8, 114u8, 101u8, 103u8, 117u8, 108u8, 97u8, 116u8, 101u8, 100u8, 32u8, 99u8, 111u8, 105u8, 110u8]}, icon_url: std::option::Option<iota::url::Url> {vec: vector[]}}

task 7 'view-object'. lines 67-67:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCap<test::first_coin::FIRST_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,5)}}}

task 8 'view-object'. lines 69-69:
Owner: Account Address ( A )
Version: 2
Contents: iota::coin::DenyCap<test::second_coin::SECOND_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,6)}}}

task 9 'view-object'. lines 71-71:
Owner: Immutable
Version: 2
Contents: iota::coin::RegulatedCoinMetadata<test::first_coin::FIRST_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,7)}}, coin_metadata_object: iota::object::ID {bytes: fake(1,3)}, deny_cap_object: iota::object::ID {bytes: fake(1,5)}}

task 10 'view-object'. lines 73-73:
Owner: Immutable
Version: 2
Contents: iota::coin::RegulatedCoinMetadata<test::second_coin::SECOND_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,8)}}, coin_metadata_object: iota::object::ID {bytes: fake(1,4)}, deny_cap_object: iota::object::ID {bytes: fake(1,6)}}

task 11 'view-object'. lines 75-75:
Owner: Immutable
Version: 2
Contents: iota::coin::TreasuryCap<test::first_coin::FIRST_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,9)}}, total_supply: iota::balance::Supply<test::first_coin::FIRST_COIN> {value: 10000u64}}

task 12 'view-object'. lines 77-79:
Owner: Immutable
Version: 2
Contents: iota::coin::TreasuryCap<test::second_coin::SECOND_COIN> {id: iota::object::UID {id: iota::object::ID {bytes: fake(1,10)}}, total_supply: iota::balance::Supply<test::second_coin::SECOND_COIN> {value: 10000u64}}

task 13 'run'. lines 80-82:
created: object(13,0), object(13,1)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 11293600,  storage_rebate: 2690400, non_refundable_storage_fee: 0

task 14 'transfer-object'. lines 83-85:
Error: Error checking transaction input objects: AddressDeniedForCoin { address: @A, coin_type: "object(1,0)::first_coin::FIRST_COIN" }

task 15 'transfer-object'. lines 86-86:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2416800,  storage_rebate: 2416800, non_refundable_storage_fee: 0
