processed 4 tasks

init:
A: object(0,0)

task 1, lines 7-34:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 38-86:
//# run-graphql
Response: {
  "data": {
    "iotaCoins": {
      "edges": [
        {
          "cursor": "IFWIszDYouqyV5FHmkjHL8VomWv4zfT9PeNSxpAcCjH7AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "IKAh5Dwcyc/kwt5ZIi7j9i0+5VOEhni5CiLnWNgvOlisAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        },
        {
          "cursor": "ILvZCg1Mz3zj3t29+KJ3JJdhvtfE79wdbj6VlrZgQ21OAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IMylKIZ2RJ3yz2r1X/fRLN00OhpfEv4x/ZFhIG+/fMpQAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xfc060d55fe18ece1944ee4395008a9c09d893dbb30880052acf23d3d1ffb56b5::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IN/u1Oaq78H+r+vyT7pKHqY/K3Zp47bishEsQXymiGE5AQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xfc060d55fe18ece1944ee4395008a9c09d893dbb30880052acf23d3d1ffb56b5::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IPRYQvyvi5GnfnmpWB0yjvjM9PWhmsPGIMIBKJKhr1XgAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xfc060d55fe18ece1944ee4395008a9c09d893dbb30880052acf23d3d1ffb56b5::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IFWIszDYouqyV5FHmkjHL8VomWv4zfT9PeNSxpAcCjH7AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHhmYzA2MGQ1NWZlMThlY2UxOTQ0ZWU0Mzk1MDA4YTljMDlkODkzZGJiMzA4ODAwNTJhY2YyM2QzZDFmZmI1NmI1OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0xfc060d55fe18ece1944ee4395008a9c09d893dbb30880052acf23d3d1ffb56b5::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjppb3RhOjpJT1RBIiwiYyI6MX0"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHhmYzA2MGQ1NWZlMThlY2UxOTQ0ZWU0Mzk1MDA4YTljMDlkODkzZGJiMzA4ODAwNTJhY2YyM2QzZDFmZmI1NmI1OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
