processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x978be5e7629f7d75c29b5b62ad5f84689df6bd5732710db5f5536675bcaa5d18::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  97,
                                  93,
                                  215,
                                  24,
                                  228,
                                  168,
                                  1,
                                  172,
                                  56,
                                  40,
                                  236,
                                  236,
                                  19,
                                  138,
                                  18,
                                  164,
                                  226,
                                  88,
                                  41,
                                  39,
                                  189,
                                  180,
                                  87,
                                  193,
                                  70,
                                  75,
                                  211,
                                  210,
                                  3,
                                  175,
                                  61,
                                  213
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  97,
                                  93,
                                  215,
                                  24,
                                  228,
                                  168,
                                  1,
                                  172,
                                  56,
                                  40,
                                  236,
                                  236,
                                  19,
                                  138,
                                  18,
                                  164,
                                  226,
                                  88,
                                  41,
                                  39,
                                  189,
                                  180,
                                  87,
                                  193,
                                  70,
                                  75,
                                  211,
                                  210,
                                  3,
                                  175,
                                  61,
                                  213
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      97,
                                      93,
                                      215,
                                      24,
                                      228,
                                      168,
                                      1,
                                      172,
                                      56,
                                      40,
                                      236,
                                      236,
                                      19,
                                      138,
                                      18,
                                      164,
                                      226,
                                      88,
                                      41,
                                      39,
                                      189,
                                      180,
                                      87,
                                      193,
                                      70,
                                      75,
                                      211,
                                      210,
                                      3,
                                      175,
                                      61,
                                      213
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x615dd718e4a801ac3828ecec138a12a4e2582927bdb457c1464bd3d203af3dd5",
                          "f0": "0x615dd718e4a801ac3828ecec138a12a4e2582927bdb457c1464bd3d203af3dd5",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x615dd718e4a801ac3828ecec138a12a4e2582927bdb457c1464bd3d203af3dd5"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  187,
                                  217,
                                  10,
                                  13,
                                  76,
                                  207,
                                  124,
                                  227,
                                  222,
                                  221,
                                  189,
                                  248,
                                  162,
                                  119,
                                  36,
                                  151,
                                  97,
                                  190,
                                  215,
                                  196,
                                  239,
                                  220,
                                  29,
                                  110,
                                  62,
                                  149,
                                  150,
                                  182,
                                  96,
                                  67,
                                  109,
                                  78
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988454400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xbbd90a0d4ccf7ce3deddbdf8a277249761bed7c4efdc1d6e3e9596b660436d4e",
                          "balance": {
                            "value": "299999988454400"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
