processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  106,
                                  114,
                                  115,
                                  142,
                                  205,
                                  93,
                                  65,
                                  142,
                                  153,
                                  244,
                                  254,
                                  49,
                                  173,
                                  53,
                                  74,
                                  186,
                                  136,
                                  119,
                                  85,
                                  130,
                                  146,
                                  57,
                                  139,
                                  132,
                                  69,
                                  211,
                                  242,
                                  170,
                                  66,
                                  47,
                                  191,
                                  222
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988454400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x6a72738ecd5d418e99f4fe31ad354aba8877558292398b8445d3f2aa422fbfde",
                          "balance": {
                            "value": "299999988454400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0f67d8cbf985b27c76b05ba409aa34fc894dd5f60b4f1e536e639a0e354ff821::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  136,
                                  96,
                                  91,
                                  32,
                                  162,
                                  5,
                                  225,
                                  221,
                                  192,
                                  193,
                                  80,
                                  227,
                                  39,
                                  20,
                                  72,
                                  44,
                                  237,
                                  215,
                                  101,
                                  228,
                                  73,
                                  218,
                                  169,
                                  233,
                                  11,
                                  14,
                                  243,
                                  226,
                                  58,
                                  74,
                                  171,
                                  86
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  136,
                                  96,
                                  91,
                                  32,
                                  162,
                                  5,
                                  225,
                                  221,
                                  192,
                                  193,
                                  80,
                                  227,
                                  39,
                                  20,
                                  72,
                                  44,
                                  237,
                                  215,
                                  101,
                                  228,
                                  73,
                                  218,
                                  169,
                                  233,
                                  11,
                                  14,
                                  243,
                                  226,
                                  58,
                                  74,
                                  171,
                                  86
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      136,
                                      96,
                                      91,
                                      32,
                                      162,
                                      5,
                                      225,
                                      221,
                                      192,
                                      193,
                                      80,
                                      227,
                                      39,
                                      20,
                                      72,
                                      44,
                                      237,
                                      215,
                                      101,
                                      228,
                                      73,
                                      218,
                                      169,
                                      233,
                                      11,
                                      14,
                                      243,
                                      226,
                                      58,
                                      74,
                                      171,
                                      86
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x88605b20a205e1ddc0c150e32714482cedd765e449daa9e90b0ef3e23a4aab56",
                          "f0": "0x88605b20a205e1ddc0c150e32714482cedd765e449daa9e90b0ef3e23a4aab56",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x88605b20a205e1ddc0c150e32714482cedd765e449daa9e90b0ef3e23a4aab56"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
