processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-40:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 42-44:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 46:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 48-69:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  170,
                                  212,
                                  47,
                                  104,
                                  113,
                                  214,
                                  41,
                                  87,
                                  182,
                                  75,
                                  84,
                                  5,
                                  146,
                                  116,
                                  80,
                                  26,
                                  219,
                                  128,
                                  104,
                                  195,
                                  134,
                                  119,
                                  251,
                                  10,
                                  165,
                                  125,
                                  72,
                                  55,
                                  239,
                                  15,
                                  141,
                                  222
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988454400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xaad42f6871d62957b64b54059274501adb8068c38677fb0aa57d4837ef0f8dde",
                          "balance": {
                            "value": "299999988454400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xd248789446238af5613671903583c199dec9cfc814e7678ddd73346d31829d85::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  197,
                                  149,
                                  190,
                                  248,
                                  151,
                                  94,
                                  46,
                                  178,
                                  144,
                                  173,
                                  7,
                                  106,
                                  10,
                                  99,
                                  127,
                                  31,
                                  5,
                                  206,
                                  215,
                                  205,
                                  78,
                                  253,
                                  239,
                                  31,
                                  159,
                                  14,
                                  35,
                                  162,
                                  155,
                                  39,
                                  180,
                                  134
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  197,
                                  149,
                                  190,
                                  248,
                                  151,
                                  94,
                                  46,
                                  178,
                                  144,
                                  173,
                                  7,
                                  106,
                                  10,
                                  99,
                                  127,
                                  31,
                                  5,
                                  206,
                                  215,
                                  205,
                                  78,
                                  253,
                                  239,
                                  31,
                                  159,
                                  14,
                                  35,
                                  162,
                                  155,
                                  39,
                                  180,
                                  134
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      197,
                                      149,
                                      190,
                                      248,
                                      151,
                                      94,
                                      46,
                                      178,
                                      144,
                                      173,
                                      7,
                                      106,
                                      10,
                                      99,
                                      127,
                                      31,
                                      5,
                                      206,
                                      215,
                                      205,
                                      78,
                                      253,
                                      239,
                                      31,
                                      159,
                                      14,
                                      35,
                                      162,
                                      155,
                                      39,
                                      180,
                                      134
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xc595bef8975e2eb290ad076a0a637f1f05ced7cd4efdef1f9f0e23a29b27b486",
                          "f0": "0xc595bef8975e2eb290ad076a0a637f1f05ced7cd4efdef1f9f0e23a29b27b486",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xc595bef8975e2eb290ad076a0a637f1f05ced7cd4efdef1f9f0e23a29b27b486"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
