processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x06a6545ddc2d380720e3639a402b1deb624dbd229a48c24d4054cf8997caac4f::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  75,
                                  194,
                                  4,
                                  128,
                                  167,
                                  122,
                                  247,
                                  88,
                                  165,
                                  245,
                                  242,
                                  89,
                                  22,
                                  223,
                                  140,
                                  40,
                                  224,
                                  148,
                                  248,
                                  115,
                                  33,
                                  231,
                                  31,
                                  43,
                                  201,
                                  8,
                                  74,
                                  123,
                                  42,
                                  129,
                                  91,
                                  146
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  75,
                                  194,
                                  4,
                                  128,
                                  167,
                                  122,
                                  247,
                                  88,
                                  165,
                                  245,
                                  242,
                                  89,
                                  22,
                                  223,
                                  140,
                                  40,
                                  224,
                                  148,
                                  248,
                                  115,
                                  33,
                                  231,
                                  31,
                                  43,
                                  201,
                                  8,
                                  74,
                                  123,
                                  42,
                                  129,
                                  91,
                                  146
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      75,
                                      194,
                                      4,
                                      128,
                                      167,
                                      122,
                                      247,
                                      88,
                                      165,
                                      245,
                                      242,
                                      89,
                                      22,
                                      223,
                                      140,
                                      40,
                                      224,
                                      148,
                                      248,
                                      115,
                                      33,
                                      231,
                                      31,
                                      43,
                                      201,
                                      8,
                                      74,
                                      123,
                                      42,
                                      129,
                                      91,
                                      146
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x4bc20480a77af758a5f5f25916df8c28e094f87321e71f2bc9084a7b2a815b92",
                          "f0": "0x4bc20480a77af758a5f5f25916df8c28e094f87321e71f2bc9084a7b2a815b92",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x4bc20480a77af758a5f5f25916df8c28e094f87321e71f2bc9084a7b2a815b92"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  187,
                                  217,
                                  10,
                                  13,
                                  76,
                                  207,
                                  124,
                                  227,
                                  222,
                                  221,
                                  189,
                                  248,
                                  162,
                                  119,
                                  36,
                                  151,
                                  97,
                                  190,
                                  215,
                                  196,
                                  239,
                                  220,
                                  29,
                                  110,
                                  62,
                                  149,
                                  150,
                                  182,
                                  96,
                                  67,
                                  109,
                                  78
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xbbd90a0d4ccf7ce3deddbdf8a277249761bed7c4efdc1d6e3e9596b660436d4e",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
