processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x568a165e39bb16857fe2ecb9b06f85fbfc23ab2220db21d84fb8420f6e95b137::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  58,
                                  7,
                                  23,
                                  30,
                                  242,
                                  105,
                                  145,
                                  94,
                                  98,
                                  226,
                                  202,
                                  163,
                                  29,
                                  149,
                                  249,
                                  159,
                                  32,
                                  172,
                                  193,
                                  213,
                                  112,
                                  74,
                                  227,
                                  201,
                                  198,
                                  31,
                                  171,
                                  214,
                                  184,
                                  110,
                                  76,
                                  254
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  58,
                                  7,
                                  23,
                                  30,
                                  242,
                                  105,
                                  145,
                                  94,
                                  98,
                                  226,
                                  202,
                                  163,
                                  29,
                                  149,
                                  249,
                                  159,
                                  32,
                                  172,
                                  193,
                                  213,
                                  112,
                                  74,
                                  227,
                                  201,
                                  198,
                                  31,
                                  171,
                                  214,
                                  184,
                                  110,
                                  76,
                                  254
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      58,
                                      7,
                                      23,
                                      30,
                                      242,
                                      105,
                                      145,
                                      94,
                                      98,
                                      226,
                                      202,
                                      163,
                                      29,
                                      149,
                                      249,
                                      159,
                                      32,
                                      172,
                                      193,
                                      213,
                                      112,
                                      74,
                                      227,
                                      201,
                                      198,
                                      31,
                                      171,
                                      214,
                                      184,
                                      110,
                                      76,
                                      254
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x3a07171ef269915e62e2caa31d95f99f20acc1d5704ae3c9c61fabd6b86e4cfe",
                          "f0": "0x3a07171ef269915e62e2caa31d95f99f20acc1d5704ae3c9c61fabd6b86e4cfe",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x3a07171ef269915e62e2caa31d95f99f20acc1d5704ae3c9c61fabd6b86e4cfe"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  65,
                                  4,
                                  216,
                                  38,
                                  175,
                                  162,
                                  249,
                                  235,
                                  133,
                                  9,
                                  129,
                                  215,
                                  211,
                                  227,
                                  71,
                                  92,
                                  114,
                                  194,
                                  220,
                                  254,
                                  14,
                                  227,
                                  201,
                                  121,
                                  42,
                                  230,
                                  11,
                                  160,
                                  170,
                                  19,
                                  240,
                                  59
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x4104d826afa2f9eb850981d7d3e3475c72c2dcfe0ee3c9792ae60ba0aa13f03b",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
