processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-55:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 57-59:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 61:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 63-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  50,
                                  92,
                                  147,
                                  107,
                                  228,
                                  135,
                                  250,
                                  51,
                                  126,
                                  141,
                                  178,
                                  52,
                                  79,
                                  83,
                                  201,
                                  167,
                                  16,
                                  213,
                                  81,
                                  163,
                                  207,
                                  236,
                                  134,
                                  201,
                                  107,
                                  64,
                                  28,
                                  110,
                                  244,
                                  35,
                                  31,
                                  191
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x325c936be487fa337e8db2344f53c9a710d551a3cfec86c96b401c6ef4231fbf",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xc5f5b24b7d768e043a955eaf03f4dcb1b688c147d74cb8e947db8d26996c00f8::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  208,
                                  212,
                                  64,
                                  221,
                                  218,
                                  239,
                                  14,
                                  234,
                                  181,
                                  211,
                                  165,
                                  150,
                                  57,
                                  235,
                                  56,
                                  214,
                                  114,
                                  209,
                                  118,
                                  28,
                                  254,
                                  179,
                                  127,
                                  231,
                                  142,
                                  118,
                                  162,
                                  158,
                                  232,
                                  23,
                                  159,
                                  44
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  208,
                                  212,
                                  64,
                                  221,
                                  218,
                                  239,
                                  14,
                                  234,
                                  181,
                                  211,
                                  165,
                                  150,
                                  57,
                                  235,
                                  56,
                                  214,
                                  114,
                                  209,
                                  118,
                                  28,
                                  254,
                                  179,
                                  127,
                                  231,
                                  142,
                                  118,
                                  162,
                                  158,
                                  232,
                                  23,
                                  159,
                                  44
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      208,
                                      212,
                                      64,
                                      221,
                                      218,
                                      239,
                                      14,
                                      234,
                                      181,
                                      211,
                                      165,
                                      150,
                                      57,
                                      235,
                                      56,
                                      214,
                                      114,
                                      209,
                                      118,
                                      28,
                                      254,
                                      179,
                                      127,
                                      231,
                                      142,
                                      118,
                                      162,
                                      158,
                                      232,
                                      23,
                                      159,
                                      44
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xd0d440dddaef0eeab5d3a59639eb38d672d1761cfeb37fe78e76a29ee8179f2c",
                          "f0": "0xd0d440dddaef0eeab5d3a59639eb38d672d1761cfeb37fe78e76a29ee8179f2c",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xd0d440dddaef0eeab5d3a59639eb38d672d1761cfeb37fe78e76a29ee8179f2c"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
