processed 15 tasks

task 1, lines 7-20:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, lines 25-26:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4, lines 28-29:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 5, lines 31-32:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6, lines 34-35:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 7, line 37:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 39-49:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICX6kO+NNdmV03GzieZuGXzdkz+yg2KHaSvmj6Hj8cWQAQAAAAAAAAA="
          },
          {
            "cursor": "ICcBl0AEG48NrzqwFJFwHglDQW+MRDKuK74gJ80F1+GKAQAAAAAAAAA="
          },
          {
            "cursor": "IE4/Lyl0XVh6bwwhkTUUyvxap8fCENmJqp+D2LL89/cbAQAAAAAAAAA="
          },
          {
            "cursor": "IGtvShjRsIhJv1W8PSE/adgtP+dt7GI5Vnhu+Ivd+98zAQAAAAAAAAA="
          },
          {
            "cursor": "IKv5yJhwXba9C470obT7zLqZWUScIDaHFAY9hpMrT1KWAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 51-61:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICX6kO+NNdmV03GzieZuGXzdkz+yg2KHaSvmj6Hj8cWQAQAAAAAAAAA="
          },
          {
            "cursor": "ICcBl0AEG48NrzqwFJFwHglDQW+MRDKuK74gJ80F1+GKAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 63-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ICX6kO+NNdmV03GzieZuGXzdkz+yg2KHaSvmj6Hj8cWQAQAAAAAAAAA=",
            "node": {
              "address": "0x25fa90ef8d35d995d371b389e66e197cdd933fb2836287692be68fa1e3f1c590"
            }
          },
          {
            "cursor": "ICcBl0AEG48NrzqwFJFwHglDQW+MRDKuK74gJ80F1+GKAQAAAAAAAAA=",
            "node": {
              "address": "0x27019740041b8f0daf3ab01491701e0943416f8c4432ae2bbe2027cd05d7e18a"
            }
          },
          {
            "cursor": "IE4/Lyl0XVh6bwwhkTUUyvxap8fCENmJqp+D2LL89/cbAQAAAAAAAAA=",
            "node": {
              "address": "0x4e3f2f29745d587a6f0c21913514cafc5aa7c7c210d989aa9f83d8b2fcf7f71b"
            }
          },
          {
            "cursor": "IGtvShjRsIhJv1W8PSE/adgtP+dt7GI5Vnhu+Ivd+98zAQAAAAAAAAA=",
            "node": {
              "address": "0x6b6f4a18d1b08849bf55bc3d213f69d82d3fe76dec623956786ef88bddfbdf33"
            }
          },
          {
            "cursor": "IKv5yJhwXba9C470obT7zLqZWUScIDaHFAY9hpMrT1KWAQAAAAAAAAA=",
            "node": {
              "address": "0xabf9c898705db6bd0b8ef4a1b4fbccba9959449c20368714063d86932b4f5296"
            }
          }
        ]
      }
    },
    "obj_3_0": {
      "address": "0x25fa90ef8d35d995d371b389e66e197cdd933fb2836287692be68fa1e3f1c590"
    },
    "obj_5_0": {
      "address": "0x6b6f4a18d1b08849bf55bc3d213f69d82d3fe76dec623956786ef88bddfbdf33"
    },
    "obj_6_0": {
      "address": "0x4e3f2f29745d587a6f0c21913514cafc5aa7c7c210d989aa9f83d8b2fcf7f71b"
    },
    "obj_4_0": {
      "address": "0xabf9c898705db6bd0b8ef4a1b4fbccba9959449c20368714063d86932b4f5296"
    },
    "obj_2_0": {
      "address": "0x27019740041b8f0daf3ab01491701e0943416f8c4432ae2bbe2027cd05d7e18a"
    }
  }
}

task 11, lines 94-106:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKv5yJhwXba9C470obT7zLqZWUScIDaHFAY9hpMrT1KWAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 108-118:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 13, lines 120-130:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    }
  }
}

task 14, lines 132-144:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IGtvShjRsIhJv1W8PSE/adgtP+dt7GI5Vnhu+Ivd+98zAQAAAAAAAAA=",
            "node": {
              "address": "0x6b6f4a18d1b08849bf55bc3d213f69d82d3fe76dec623956786ef88bddfbdf33"
            }
          },
          {
            "cursor": "IKv5yJhwXba9C470obT7zLqZWUScIDaHFAY9hpMrT1KWAQAAAAAAAAA=",
            "node": {
              "address": "0xabf9c898705db6bd0b8ef4a1b4fbccba9959449c20368714063d86932b4f5296"
            }
          }
        ]
      }
    }
  }
}
