processed 15 tasks

task 1, lines 7-20:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5168000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 3, lines 25-26:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 4, lines 28-29:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 5, lines 31-32:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 6, lines 34-35:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 980400, non_refundable_storage_fee: 0

task 7, line 37:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 39-49:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAXGOxelPyat2ktykI7yExbqPi0zGAJwpEL4QOtk4i5JAQAAAAAAAAA="
          },
          {
            "cursor": "IIhXgyfJmpDjfYgKcvjwnz8XljbqK8kWTshmtGAa1JcrAQAAAAAAAAA="
          },
          {
            "cursor": "IIuOKDIL3ox4W0vwl9Iys+UJ+hOhYIxg9QXA1kvE02x1AQAAAAAAAAA="
          },
          {
            "cursor": "IKaEPeEks1/XBPKzfdNHH89Pmqm8lXcmxDqL2W0EAEsyAQAAAAAAAAA="
          },
          {
            "cursor": "ILL8PT6CGnkMV6rhl3RwEvqsdGHGUNh5XsuxI1STMnrZAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 51-61:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAXGOxelPyat2ktykI7yExbqPi0zGAJwpEL4QOtk4i5JAQAAAAAAAAA="
          },
          {
            "cursor": "IIhXgyfJmpDjfYgKcvjwnz8XljbqK8kWTshmtGAa1JcrAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 63-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAXGOxelPyat2ktykI7yExbqPi0zGAJwpEL4QOtk4i5JAQAAAAAAAAA=",
            "node": {
              "address": "0x05c63b17a53f26adda4b72908ef21316ea3e2d33180270a442f840eb64e22e49"
            }
          },
          {
            "cursor": "IIhXgyfJmpDjfYgKcvjwnz8XljbqK8kWTshmtGAa1JcrAQAAAAAAAAA=",
            "node": {
              "address": "0x88578327c99a90e37d880a72f8f09f3f179636ea2bc9164ec866b4601ad4972b"
            }
          },
          {
            "cursor": "IIuOKDIL3ox4W0vwl9Iys+UJ+hOhYIxg9QXA1kvE02x1AQAAAAAAAAA=",
            "node": {
              "address": "0x8b8e28320bde8c785b4bf097d232b3e509fa13a1608c60f505c0d64bc4d36c75"
            }
          },
          {
            "cursor": "IKaEPeEks1/XBPKzfdNHH89Pmqm8lXcmxDqL2W0EAEsyAQAAAAAAAAA=",
            "node": {
              "address": "0xa6843de124b35fd704f2b37dd3471fcf4f9aa9bc957726c43a8bd96d04004b32"
            }
          },
          {
            "cursor": "ILL8PT6CGnkMV6rhl3RwEvqsdGHGUNh5XsuxI1STMnrZAQAAAAAAAAA=",
            "node": {
              "address": "0xb2fc3d3e821a790c57aae197747012faac7461c650d8795ecbb1235493327ad9"
            }
          }
        ]
      }
    },
    "obj_3_0": {
      "address": "0x88578327c99a90e37d880a72f8f09f3f179636ea2bc9164ec866b4601ad4972b"
    },
    "obj_5_0": {
      "address": "0xa6843de124b35fd704f2b37dd3471fcf4f9aa9bc957726c43a8bd96d04004b32"
    },
    "obj_6_0": {
      "address": "0xb2fc3d3e821a790c57aae197747012faac7461c650d8795ecbb1235493327ad9"
    },
    "obj_4_0": {
      "address": "0x8b8e28320bde8c785b4bf097d232b3e509fa13a1608c60f505c0d64bc4d36c75"
    },
    "obj_2_0": {
      "address": "0x05c63b17a53f26adda4b72908ef21316ea3e2d33180270a442f840eb64e22e49"
    }
  }
}

task 11, lines 94-106:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "ILL8PT6CGnkMV6rhl3RwEvqsdGHGUNh5XsuxI1STMnrZAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 108-118:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKaEPeEks1/XBPKzfdNHH89Pmqm8lXcmxDqL2W0EAEsyAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 13, lines 120-130:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IAXGOxelPyat2ktykI7yExbqPi0zGAJwpEL4QOtk4i5JAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 14, lines 132-144:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKaEPeEks1/XBPKzfdNHH89Pmqm8lXcmxDqL2W0EAEsyAQAAAAAAAAA=",
            "node": {
              "address": "0xa6843de124b35fd704f2b37dd3471fcf4f9aa9bc957726c43a8bd96d04004b32"
            }
          },
          {
            "cursor": "ILL8PT6CGnkMV6rhl3RwEvqsdGHGUNh5XsuxI1STMnrZAQAAAAAAAAA=",
            "node": {
              "address": "0xb2fc3d3e821a790c57aae197747012faac7461c650d8795ecbb1235493327ad9"
            }
          }
        ]
      }
    }
  }
}
