processed 5 tasks

init:
A: object(0,0)

task 1, lines 7-27:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 29-32:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> 1: P0::m::bar();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3435200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3, line 34:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 36-54:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe5b2eaebcea299e2a55ee5d2daebb15e71f47ed83ea0e9702359e55f26a6da0d::m::Bar"
                        }
                      },
                      "hasPublicTransfer": false
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe5b2eaebcea299e2a55ee5d2daebb15e71f47ed83ea0e9702359e55f26a6da0d::m::Foo"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
