processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-27:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 29-32:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3435200,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 34-34:
Checkpoint created: 1

task 4 'run-graphql'. lines 36-54:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe3e7383383372fdc62d0d0fc4edc6ebaad1e2cd390a914c24c9c8cd5e223ed27::m::Foo"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe3e7383383372fdc62d0d0fc4edc6ebaad1e2cd390a914c24c9c8cd5e223ed27::m::Bar"
                        }
                      },
                      "hasPublicTransfer": false
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
