processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 7-27:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 29-32:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3435200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 34-34:
Checkpoint created: 1

task 4 'run-graphql'. lines 36-54:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe38f60bd8a4ddf0e69b0426cd3acddd52e00b5800d0bd4c64c9568d7254c0d6f::m::Foo"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::iota::IOTA>"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xe38f60bd8a4ddf0e69b0426cd3acddd52e00b5800d0bd4c64c9568d7254c0d6f::m::Bar"
                        }
                      },
                      "hasPublicTransfer": false
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
