processed 5 tasks

task 1 'run-graphql'. lines 7-16:
Response: {
  "data": {
    "object": {
      "receivedTransactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 2 'publish'. lines 18-28:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6353600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 4 'run-graphql'. lines 32-41:
Response: {
  "data": {
    "object": {
      "receivedTransactionBlocks": {
        "nodes": [
          {
            "digest": "498oFQyxHNepwoJEvZ3hAnuGQHNb4XvgJSEe2f97NNVo"
          }
        ]
      }
    }
  }
}
