processed 7 tasks

init:
C: object(0,0)

task 1, lines 7-32:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IIKDDWMJEQ0SaqegqoUwd4Tud0KewlpG9UzxKvz4b+AFAAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 2, lines 34-36:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 38:
//# run 0x3::iota_system::request_add_stake --args object(0x5) object(2,0) @validator_0 --sender C
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [195, 31, 89, 68, 25, 110, 110, 130, 15, 151, 96, 218, 107, 188, 216, 30, 11, 194, 226, 183, 85, 68, 74, 206, 105, 101, 238, 219, 200, 86, 235, 41, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 14523600,  storage_rebate: 1976000, non_refundable_storage_fee: 0

task 4, line 40:
//# create-checkpoint
Checkpoint created: 1

task 5, line 42:
//# advance-epoch
Epoch advanced: 0

task 6, lines 44-70:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "ICzSs8gJrEchdo/v0DdIPKJpx37IypILVMI4TvKng3QUAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "10000000000",
                "poolId": "0xc31f5944196e6e820f9760da6bbcd81e0bc2e2b755444ace6965eedbc856eb29"
              }
            }
          }
        },
        {
          "cursor": "IIKDDWMJEQ0SaqegqoUwd4Tud0KewlpG9UzxKvz4b+AFAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "1500000000000000",
                "poolId": "0xc31f5944196e6e820f9760da6bbcd81e0bc2e2b755444ace6965eedbc856eb29"
              }
            }
          }
        },
        {
          "cursor": "ILVYziRMbmfeQ0alyypl2nA4gTpsnVI0/mNu+O2M0UcwAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "15340000000000",
                "poolId": "0xc31f5944196e6e820f9760da6bbcd81e0bc2e2b755444ace6965eedbc856eb29"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "ICzSs8gJrEchdo/v0DdIPKJpx37IypILVMI4TvKng3QUAgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
