processed 7 tasks

init:
C: object(0,0)

task 1 'run-graphql'. lines 7-32:
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IKOKNal8FcPh5Uq7PRaM8fItWmzEoBHKrVR0wCfRvCEnAAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "20000000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": []
      }
    }
  }
}

task 2 'programmable'. lines 34-36:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 38-38:
events: Event { package_id: iota_system, transaction_module: Identifier("iota_system"), sender: C, type_: StructTag { address: iota_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [224, 254, 135, 74, 173, 170, 72, 210, 205, 206, 11, 96, 21, 79, 25, 36, 170, 113, 10, 64, 232, 245, 75, 115, 20, 97, 24, 171, 22, 151, 46, 165, 175, 163, 158, 79, 0, 218, 226, 120, 249, 119, 199, 198, 147, 10, 94, 44, 118, 232, 93, 23, 165, 38, 215, 36, 187, 206, 15, 184, 31, 176, 125, 76, 140, 202, 78, 28, 224, 186, 89, 4, 206, 166, 29, 249, 36, 45, 162, 247, 210, 158, 62, 243, 40, 251, 126, 192, 124, 8, 107, 59, 244, 124, 166, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 15108800,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 4 'create-checkpoint'. lines 40-40:
Checkpoint created: 1

task 5 'advance-epoch'. lines 42-42:
Epoch advanced: 0

task 6 'run-graphql'. lines 44-70:
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IGNUSo0Wtii8qNLV2YiihYoo1wW0NXNyv5S+3AvklredAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "10000000000",
                "poolId": "0xe0fe874aadaa48d2cdce0b60154f1924aa710a40e8f54b73146118ab16972ea5"
              }
            }
          }
        },
        {
          "cursor": "IKOKNal8FcPh5Uq7PRaM8fItWmzEoBHKrVR0wCfRvCEnAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "20000000000000000",
                "poolId": "0xe0fe874aadaa48d2cdce0b60154f1924aa710a40e8f54b73146118ab16972ea5"
              }
            }
          }
        },
        {
          "cursor": "IK6pLxDQJ4OeOk8fJx336RYKxgNwh9P7ns/8ruXqgIRAAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedIota": {
                "principal": "40000",
                "poolId": "0xe0fe874aadaa48d2cdce0b60154f1924aa710a40e8f54b73146118ab16972ea5"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedIotas": {
        "edges": [
          {
            "cursor": "IGNUSo0Wtii8qNLV2YiihYoo1wW0NXNyv5S+3AvklredAgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
