processed 7 tasks

init:
A: object(0,0)

task 1, lines 7-35:
//# publish --sender A
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4187600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 37:
//# run P0::m::t_a
Error: Transaction Effects Status: Move Runtime Abort. Location: P0::m::t_a (function index 0) at offset 1, Abort Code: 9223372131344056319
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: P0, name: Identifier("m") }, function: 0, instruction: 1, function_name: Some("t_a") }, 9223372131344056319), source: Some(VMError { major_status: ABORTED, sub_status: Some(9223372131344056319), message: Some("P0::m::t_a at offset 1"), exec_state: None, location: Module(ModuleId { address: P0, name: Identifier("m") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 1)] }), command: Some(0) } }

task 3, line 39:
//# run P0::m::t_calls_a
Error: Transaction Effects Status: Move Runtime Abort. Location: P0::m::t_calls_a (function index 1) at offset 1, Abort Code: 9223372144228958207
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: P0, name: Identifier("m") }, function: 1, instruction: 1, function_name: Some("t_calls_a") }, 9223372144228958207), source: Some(VMError { major_status: ABORTED, sub_status: Some(9223372144228958207), message: Some("P0::m::t_calls_a at offset 1"), exec_state: None, location: Module(ModuleId { address: P0, name: Identifier("m") }), indices: [], offsets: [(FunctionDefinitionIndex(1), 1)] }), command: Some(0) } }

task 4, line 41:
//# run P0::m::t_const_assert
Error: Transaction Effects Status: Move Runtime Abort. Location: P0::m::t_const_assert (function index 2) at offset 1, Abort Code: 9223372079804448769
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: P0, name: Identifier("m") }, function: 2, instruction: 1, function_name: Some("t_const_assert") }, 9223372079804448769), source: Some(VMError { major_status: ABORTED, sub_status: Some(9223372079804448769), message: Some("P0::m::t_const_assert at offset 1"), exec_state: None, location: Module(ModuleId { address: P0, name: Identifier("m") }), indices: [], offsets: [(FunctionDefinitionIndex(2), 1)] }), command: Some(0) } }

task 5, line 43:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 45-55:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "status": "FAILURE",
            "errors": "Error in 1st command, from '0x1892a647f981d763ff1f6a2f372a1936401ddd233985c3c7ac0d17d220cf883f::m::t_a' (line 21)"
          }
        },
        {
          "effects": {
            "status": "FAILURE",
            "errors": "Error in 1st command, from '0x1892a647f981d763ff1f6a2f372a1936401ddd233985c3c7ac0d17d220cf883f::m::t_calls_a' (line 24)"
          }
        },
        {
          "effects": {
            "status": "FAILURE",
            "errors": "Error in 1st command, from '0x1892a647f981d763ff1f6a2f372a1936401ddd233985c3c7ac0d17d220cf883f::m::t_const_assert' (line 10), abort 'EMsg': This is a string"
          }
        }
      ]
    }
  }
}
